#!/usr/bin/env python3
# NOTICE: Generated by an LLM coding agent. Review/edit/test before relying on it.
"""Post-process a Quarto reveal.js slide deck.

For .ipynb notebooks:
  1. Remove YAML frontmatter from the first markdown cell.
  2. Add <!-- slide N --> comment before each level-1 heading.
  3. Insert a compilation timestamp into the Sources slide.

For .qmd / .md files:
  3. Insert a compilation timestamp into the Sources slide.
     (Replaces stamp_source_note.py for standalone use.)

Usage:
  python3 postprocess_slides.py deck.ipynb
  python3 postprocess_slides.py deck.qmd
"""
import json
import re
import sys
from datetime import datetime
from zoneinfo import ZoneInfo

NOTE_PREFIX = "Last modified and compiled "
FRONTMATTER_RE = re.compile(r'\A---\n.*?\n---\n', re.DOTALL)
SLIDE_SEP_RE = re.compile(r'(?m)^---[ \t]*$')
HEADING_RE = re.compile(r'(?m)^# .+')


# ── shared helpers ───────────────────────────────────────────────────────────

def _now_stamp():
    dt = datetime.now(ZoneInfo("America/Chicago"))
    return f"{NOTE_PREFIX}{dt:%B} {dt.day}, {dt:%H:%M}h Central (Chicago) time."


def _list_marker(line):
    """Return (indent, marker, spacing) for a markdown list item, or None."""
    m = re.match(r'^(\s*)([0-9]+[.)]|[-*+])(\s+)', line)
    if not m:
        return None
    indent, mk, sp = m.group(1), m.group(2), m.group(3)
    if mk[-1] in '.)':
        mk = '1' + mk[-1]
    return indent, mk, sp


def _stamp_lines(lines, note):
    """Insert timestamp after the GitHub source line (or best fallback).

    Operates on a list of strings (lines without trailing newline for the last,
    with \\n for the rest — or just plain lines). Mutates in place.
    """
    start = next(
        (i for i, l in enumerate(lines)
         if l.lstrip().startswith('#') and '.sources' in l),
        None,
    )
    if start is None:
        return

    end = next(
        (i for i in range(start + 1, len(lines)) if lines[i].strip() == '---'),
        len(lines),
    )
    block = range(start + 1, end)

    def insert_after(idx, mk):
        indent, marker, sp = mk
        lines.insert(idx + 1, f'{indent}{marker}{sp}{note}')

    # 1) After the GitHub source bullet
    for i in block:
        mk = _list_marker(lines[i])
        if 'GitHub source:' in lines[i] and mk:
            insert_after(i, mk)
            return

    # 2) After the "built with Quarto" line
    for i in block:
        if 'Quarto' in lines[i] and 'built' in lines[i].lower():
            mk = _list_marker(lines[i]) or ('', '1.', ' ')
            insert_after(i, mk)
            return

    # 3) After the last list item in the slide
    last = max((i for i in block if _list_marker(lines[i])), default=None)
    if last is not None:
        insert_after(last, _list_marker(lines[last]))
        return

    # 4) Fallback: before slide end
    lines.insert(end, note)


# ── .qmd / .md ───────────────────────────────────────────────────────────────

def process_qmd(path):
    text = open(path, encoding='utf-8').read()
    if NOTE_PREFIX in text:
        return
    note = _now_stamp()
    lines = text.split('\n')
    _stamp_lines(lines, note)
    open(path, 'w', encoding='utf-8').write('\n'.join(lines))


# ── .ipynb ────────────────────────────────────────────────────────────────────

def _src(cell):
    return ''.join(cell.get('source', []))


def _set_src(cell, text):
    """Write source back as a list of lines (preserving notebook conventions)."""
    if not text:
        cell['source'] = []
        return
    lines = text.split('\n')
    # Each line except the last gets a trailing \n, matching nbformat conventions.
    result = [line + '\n' for line in lines[:-1]]
    if lines[-1]:
        result.append(lines[-1])
    cell['source'] = result


def process_ipynb(path):
    nb = json.loads(open(path, encoding='utf-8').read())
    cells = nb['cells']

    # 1. Replace YAML frontmatter in the first markdown cell with only the
    #    title: and jupyter: lines, then skip to the first # heading.
    for cell in cells:
        if cell['cell_type'] == 'markdown':
            src = _src(cell)
            m = FRONTMATTER_RE.match(src)
            if m:
                fm = m.group(0)
                kept = [
                    ln for ln in fm.splitlines()
                    if ln.startswith('title:') or ln.startswith('jupyter:')
                ]
                after_fm = src[m.end():]
                h1 = HEADING_RE.search(after_fm)
                rest = after_fm[h1.start():] if h1 else after_fm.lstrip('\n')
                _set_src(cell, '\n'.join(kept) + '\n\n' + rest)
            break

    # 2. Walk cells to identify slide numbers.
    slide_num = 0
    slide_meta = []  # {num, cell_idx}

    for i, cell in enumerate(cells):
        if cell['cell_type'] == 'markdown':
            for _ in HEADING_RE.finditer(_src(cell)):
                slide_num += 1
                slide_meta.append({'num': slide_num, 'cell_idx': i})

    # 3. Annotate markdown cells: number headings.
    from collections import defaultdict
    by_cell = defaultdict(list)
    for s in slide_meta:
        by_cell[s['cell_idx']].append(s)

    for i, cell in enumerate(cells):
        if cell['cell_type'] != 'markdown' or i not in by_cell:
            continue

        src = _src(cell)
        cell_slides = by_cell[i]
        slide_ptr = 0

        # Split on standalone --- lines; rejoin with the separator after editing.
        parts = SLIDE_SEP_RE.split(src)
        new_parts = []

        for part in parts:
            hm = HEADING_RE.search(part)
            if hm:
                sl = cell_slides[slide_ptr]
                slide_ptr += 1

                # Prepend slide-number comment before the heading.
                part = (
                    part[:hm.start()]
                    + f'<!-- slide {sl["num"]} -->\n'
                    + part[hm.start():]
                )

            new_parts.append(part)

        _set_src(cell, '---'.join(new_parts))

    # 4. Stamp timestamp in the Sources slide (idempotent).
    note = _now_stamp()
    for cell in cells:
        if cell['cell_type'] != 'markdown':
            continue
        src = _src(cell)
        if NOTE_PREFIX in src:
            break
        if '.sources' in src:
            lines = src.split('\n')
            _stamp_lines(lines, note)
            _set_src(cell, '\n'.join(lines))
            break

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)

    print(f'[postprocess] {path}: {slide_num} slides', file=sys.stderr)


# ── entry point ───────────────────────────────────────────────────────────────

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(f'Usage: {sys.argv[0]} <deck.ipynb|deck.qmd|deck.md>')
    path = sys.argv[1]
    if path.endswith('.ipynb'):
        process_ipynb(path)
    else:
        process_qmd(path)
