#!/usr/bin/env python3
# NOTICE: Modified by an LLM coding agent.
"""Sync the "Supporting ... code" links in the slides index.

Every deck that runs code gets a downloadable artifact linked from index.html:

  * Jupyter decks (`jupyter: python3`) keep their executed notebook as
    weekN.ipynb (see keep-ipynb in _quarto.yml), so they link that.
  * knitr decks (`engine: knitr`, e.g. an R + Python deck driving Python
    through reticulate) cannot produce a notebook at all, so they link the
    weekN.qmd source instead. That source *is* the full code, hidden setup
    chunks included, and it can never drift from the deck it built.

Each generated line carries MARKER, so re-running replaces the previous line
rather than stacking duplicates. Weeks with no entry in the index (e.g. week 0,
which is linked from the intro paragraph instead) are skipped.

Note the .qmd download resolves only because the Pages workflow copies slide
sources into _site after Jekyll runs -- docs/_config.yml deliberately excludes
slides/*.qmd so Jekyll cannot render one over the real deck.

Usage:
  python3 sync_slide_links.py [slides-dir]
"""
import os
import re
import sys

MARKER = '<!-- code link: generated by sync_slide_links.py -->'
REPO_BLOB = 'https://github.com/jackbandy/data-science-fun/blob/main/docs/slides'
# Any line the generator owns, including the hand-written links it replaced.
STALE_RE = re.compile(r'Supporting [\w +]*code|' + re.escape(MARKER))


def languages(source_text):
    """Human-readable list of the languages this deck executes, R first."""
    langs = [
        name for tag, name in (('r', 'R'), ('python', 'Python'))
        if re.search(r'^```\{' + tag + r'[ ,}]', source_text, re.MULTILINE)
    ]
    return ' + '.join(langs)


def line_for(week, indent, target, kind, langs):
    """The managed <li>: a site download plus the GitHub view of the same file."""
    return (
        f'{indent}<li>{MARKER}Supporting {langs} code: '
        f'<a href="{target}">download {kind}</a> | '
        f'<a href="{REPO_BLOB}/{target}">view on GitHub</a></li>'
    )


def strip_existing(text):
    return '\n'.join(ln for ln in text.split('\n') if not STALE_RE.search(ln))


def insert(text, week, line):
    """Append the managed <li> to week N's nested <ul>. No-op if absent."""
    head = re.search(rf'^([ \t]*)Week {week} Slide Deck:', text, re.MULTILINE)
    if not head:
        return text, False
    # The deck's detail bullets are the first nested list after the heading line.
    open_ul = text.find('<ul>', head.end())
    close_ul = text.find('</ul>', open_ul)
    if open_ul == -1 or close_ul == -1:
        return text, False
    ul_indent = re.search(r'([ \t]*)<ul>', text[max(0, open_ul - 40):open_ul + 4])
    indent = (ul_indent.group(1) + '  ') if ul_indent else '      '
    line_start = text.rfind('\n', 0, close_ul) + 1
    return text[:line_start] + line(indent) + '\n' + text[line_start:], True


def artifact_for(slides_dir, week):
    """(target, kind, languages) for a deck, or None when it runs no code."""
    src = os.path.join(slides_dir, f'week{week}.qmd')
    if not os.path.exists(src):
        return None
    text = open(src, encoding='utf-8').read()
    langs = languages(text)
    if not langs:
        return None
    # A notebook exists only for the jupyter engine; knitr decks fall back to
    # the source, which is the artifact that actually reproduces the deck.
    if os.path.exists(os.path.join(slides_dir, f'week{week}.ipynb')):
        return f'week{week}.ipynb', 'notebook', langs
    return f'week{week}.qmd', 'source', langs


def main(slides_dir):
    index = os.path.join(slides_dir, 'index.html')
    original = open(index, encoding='utf-8').read()

    weeks = sorted(
        int(m.group(1))
        for f in os.listdir(slides_dir)
        for m in [re.fullmatch(r'week(\d+)\.qmd', f)]
        if m
    )

    text = strip_existing(original)
    linked, skipped = [], []
    for week in weeks:
        artifact = artifact_for(slides_dir, week)
        if not artifact:
            continue
        target, kind, langs = artifact
        text, placed = insert(
            text, week, lambda i, t=target, k=kind, l=langs: line_for(week, i, t, k, l)
        )
        (linked if placed else skipped).append(f'{week}:{kind}')

    if text != original:
        open(index, 'w', encoding='utf-8').write(text)
    note = f'; no index entry for week {", ".join(skipped)}' if skipped else ''
    print(f'[sync-links] linked {len(linked)}: {" ".join(linked)}{note}', file=sys.stderr)


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__)))
