#!/usr/bin/env python3
# NOTICE: Modified by an LLM coding agent.
"""Generate the per-deck detail bullets in the slides index.

Everything nested under "Week N Slide Deck:" in index.html is written by this
script, from the deck sources sitting next to it. Two kinds of bullet:

  * Topics -- one per `{.section-header}` heading, linked to that slide. Those
    headings are already the deck's table of contents, so the deck source stays
    the single place the wording is edited.
  * A code link -- the downloadable artifact for decks that run code. Jupyter
    decks (`jupyter: python3`) keep their executed notebook as weekN.ipynb (see
    keep-ipynb in _quarto.yml). knitr decks (`engine: knitr`, e.g. an R deck
    driving Python through reticulate) cannot produce a notebook at all, so
    they link the source instead. That source *is* the full code, hidden setup
    chunks included, and it can never drift from the deck it built.

Because the script owns the whole nested <ul>, it rewrites that block outright
instead of tracking individual lines, which makes re-runs idempotent by
construction. Weeks with no entry in the index (e.g. week 0, linked from the
intro paragraph instead) are skipped. The hand-written bullets this replaced are
archived in 0-old-outline.md.

Anchors are derived from the source rather than read out of the built HTML,
because docs/slides/*.html is gitignored -- the CI drift check (repo-checks.yml)
runs with no decks built. So slugify() reimplements pandoc's auto_identifiers
algorithm, and every heading is walked (not just section headers) because
pandoc's duplicate suffixes count all of them: week 10's `# Hierarchical
Clustering {.section-header}` takes `hierarchical-clustering` and the plain
`# Hierarchical Clustering` four slides later becomes `hierarchical-clustering-1`.

The link form is `weekN.html#/slug`. reveal.js writes that shape into the URL
bar itself (Location.getHash prepends "/"), and reads it back with a regex that
makes the slash optional, so this matches what a user sees after navigating.

A section header can opt out of the index with `{.section-header .no-index}` --
useful for dividers that are structural rather than topical, like week 6's
Appendix. Decks with no indexable section headers keep a placeholder bullet.

Note the .qmd download resolves only because the Pages workflow copies slide
sources into _site after Jekyll runs -- docs/_config.yml deliberately excludes
slides/*.qmd so Jekyll cannot render one over the real deck.

Usage:
  python3 sync_slide_index.py [slides-dir]
"""
import os
import re
import sys

MARKER = '<!-- generated by sync_slide_index.py -->'
PLACEHOLDER = 'Topic details in-progress'
REPO_BLOB = 'https://github.com/jackbandy/data-science-fun/blob/main/docs/slides'

HEADING_RE = re.compile(r'^(#{1,6})\s+(.*?)\s*$')
# A trailing pandoc attribute block: {#explicit-id .class key="value"}
ATTR_RE = re.compile(r'\{([^{}]*)\}\s*$')
FENCE_RE = re.compile(r'^\s*(```+|~~~+)')


# --------------------------------------------------------------------------
# Reading a deck source
# --------------------------------------------------------------------------

def deck_source(slides_dir, week):
    """(path, text) for a week's deck, or None. Decks are .qmd or plain .md."""
    for ext in ('qmd', 'md'):
        path = os.path.join(slides_dir, f'week{week}.{ext}')
        if os.path.exists(path):
            return path, open(path, encoding='utf-8').read()
    return None


def headings(source_text):
    """Every ATX heading in order, as (raw_text, attrs), skipping non-prose.

    Front matter and code chunks are full of `#` comment lines that would
    otherwise read as headings -- see the YAML comments atop week1.qmd and the
    R setup chunk in week5.qmd.
    """
    found = []
    lines = source_text.split('\n')
    i = 0
    # Strip YAML front matter, which must open on the very first line.
    if lines and lines[0].strip() == '---':
        for i in range(1, len(lines)):
            if lines[i].strip() in ('---', '...'):
                i += 1
                break
        else:
            i = len(lines)
    fence = None
    while i < len(lines):
        line = lines[i]
        i += 1
        opener = FENCE_RE.match(line)
        if fence is not None:
            # Only a fence of the same kind and at least the same length closes.
            if opener and opener.group(1)[0] == fence[0] and len(opener.group(1)) >= len(fence):
                fence = None
            continue
        if opener:
            fence = opener.group(1)
            continue
        m = HEADING_RE.match(line)
        if m:
            text = m.group(2)
            attrs = ''
            attr = ATTR_RE.search(text)
            if attr:
                attrs = attr.group(1)
                text = text[:attr.start()].strip()
            found.append((text, attrs))
    return found


def strip_markup(text):
    """Heading text as pandoc sees it: inline formatting removed, not escaped."""
    text = re.sub(r'!?\[([^\]]*)\]\([^)]*\)', r'\1', text)   # links / images
    text = re.sub(r'<[^>]+>', '', text)                       # raw HTML
    text = re.sub(r'`([^`]*)`', r'\1', text)                  # code
    text = re.sub(r'(\*\*|__|\*|_)', '', text)                # emphasis
    return text.strip()


def slugify(text):
    """pandoc's auto_identifiers: what becomes the <section> id."""
    text = strip_markup(text)
    # Drop punctuation except underscores, hyphens and periods; spaces to dashes.
    text = ''.join(c for c in text if c.isalnum() or c in ' \t_-.')
    text = re.sub(r'[ \t]+', '-', text).lower()
    # Identifiers must start with a letter.
    text = re.sub(r'^[^a-z]+', '', text)
    return text or 'section'


def has_class(attrs, name):
    return re.search(r'(?:^|\s)\.' + re.escape(name) + r'(?:\s|$)', attrs) is not None


# --------------------------------------------------------------------------
# Turning a deck into bullets
# --------------------------------------------------------------------------

def topics(source_text):
    """[(text, anchor)] for the deck's indexable section headers."""
    found, seen = [], {}
    for raw, attrs in headings(source_text):
        explicit = re.search(r'#([^\s}]+)', attrs)
        slug = explicit.group(1) if explicit else slugify(raw)
        # Pandoc disambiguates repeats with -1, -2, ... in document order.
        n = seen.get(slug, 0)
        seen[slug] = n + 1
        anchor = slug if n == 0 else f'{slug}-{n}'
        if has_class(attrs, 'section-header') and not has_class(attrs, 'no-index'):
            found.append((strip_markup(raw), anchor))
    return found


def languages(source_text):
    """Human-readable list of the languages this deck executes, R first."""
    langs = [
        name for tag, name in (('r', 'R'), ('python', 'Python'))
        if re.search(r'^```\{' + tag + r'[ ,}]', source_text, re.MULTILINE)
    ]
    return ' + '.join(langs)


def artifact(slides_dir, week, source_path, source_text):
    """(target, kind, languages) for a deck, or None when it runs no code."""
    langs = languages(source_text)
    if not langs:
        return None
    # A notebook exists only for the jupyter engine; knitr decks fall back to
    # the source, which is the artifact that actually reproduces the deck.
    if os.path.exists(os.path.join(slides_dir, f'week{week}.ipynb')):
        return f'week{week}.ipynb', 'notebook', langs
    return os.path.basename(source_path), 'source', langs


def escape(text):
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def bullets(slides_dir, week, indent):
    """Every <li> for one deck: topics first, then the code link."""
    found = deck_source(slides_dir, week)
    if not found:
        return [f'{indent}<li>{MARKER}{PLACEHOLDER}</li>'], 0, None
    source_path, source_text = found

    deck_topics = topics(source_text)
    lines = [
        f'{indent}<li>{MARKER}'
        f'<a href="week{week}.html#/{anchor}">{escape(text)}</a></li>'
        for text, anchor in deck_topics
    ] or [f'{indent}<li>{MARKER}{PLACEHOLDER}</li>']

    code = artifact(slides_dir, week, source_path, source_text)
    if code:
        target, kind, langs = code
        lines.append(
            f'{indent}<li>{MARKER}Supporting {langs} code: '
            f'<a href="{target}">download {kind}</a> | '
            f'<a href="{REPO_BLOB}/{target}">view on GitHub</a></li>'
        )
    return lines, len(deck_topics), (code[1] if code else None)


# --------------------------------------------------------------------------
# Rewriting the index
# --------------------------------------------------------------------------

def replace_block(text, week, build):
    """Swap the body of week N's nested <ul> for freshly generated bullets."""
    head = re.search(rf'^([ \t]*)Week {week} Slide Deck:', text, re.MULTILINE)
    if not head:
        return text, False
    # The deck's detail bullets are the first nested list after the heading line.
    open_ul = text.find('<ul>', head.end())
    close_ul = text.find('</ul>', open_ul)
    if open_ul == -1 or close_ul == -1:
        return text, False
    ul_indent = re.search(r'([ \t]*)<ul>', text[max(0, open_ul - 40):open_ul + 4])
    indent = (ul_indent.group(1) + '  ') if ul_indent else '      '
    body_start = text.find('\n', open_ul) + 1
    body_end = text.rfind('\n', 0, close_ul) + 1
    return text[:body_start] + '\n'.join(build(indent)) + '\n' + text[body_end:], True


def main(slides_dir):
    index = os.path.join(slides_dir, 'index.html')
    original = open(index, encoding='utf-8').read()

    weeks = sorted(
        int(m.group(1))
        for f in os.listdir(slides_dir)
        for m in [re.fullmatch(r'week(\d+)\.(?:qmd|md)', f)]
        if m
    )

    text = original
    written, skipped = [], []
    for week in weeks:
        # Indent is only known once the week's <ul> is located, so pass a builder.
        stats = {}

        def build(indent, w=week, stats=stats):
            lines, n_topics, kind = bullets(slides_dir, w, indent)
            stats['topics'], stats['kind'] = n_topics, kind
            return lines

        text, placed = replace_block(text, week, build)
        if placed:
            n_topics, kind = stats['topics'], stats['kind']
            written.append(f'{week}:{n_topics}t' + (f'+{kind}' if kind else ''))
        else:
            skipped.append(str(week))

    if text != original:
        open(index, 'w', encoding='utf-8').write(text)
    note = f'; no index entry for week {", ".join(skipped)}' if skipped else ''
    print(f'[sync-index] wrote {len(written)}: {" ".join(written)}{note}', file=sys.stderr)


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__)))
