#!/usr/bin/env python3
# NOTICE: Modified by an LLM coding agent.
"""Generate the per-deck title line and detail bullets in the slides index.

The "Week N Slide Deck" title line and everything nested under it in index.html
are written by this script, from the deck sources sitting next to it.

The title line is the deck link followed by the week's schedule topics in
parentheses -- the same wording the summary table's Topics column uses, read
from ../_data/schedule.csv. The parenthetical sits outside the <a> so only the
title itself is clickable, and a week the schedule says nothing about gets no
parenthetical at all.

Under the title line, two kinds of bullet:

  * Topics -- one per `{.section-header}` heading, linked to that slide. Those
    headings are already the deck's table of contents, so the deck source stays
    the single place the wording is edited.
  * A "More:" bullet holding the week's other downloads, so the title line is
    free to be nothing but a link to the slides. Always the PDF; then, for
    decks that run code, that code both on GitHub and as a raw download.
    Jupyter decks (`jupyter: python3`) keep their executed notebook as
    weekN.ipynb (see keep-ipynb in _quarto.yml). knitr decks (`engine: knitr`,
    e.g. an R deck driving Python through reticulate) cannot produce a notebook
    at all, so they offer the source instead. That source *is* the full code,
    hidden setup chunks included, and it can never drift from the deck it built.

Because the script owns the whole nested <ul>, it rewrites that block outright
instead of tracking individual lines, which makes re-runs idempotent by
construction. Weeks with no entry in the index (e.g. week 0, linked from the
intro paragraph instead) are skipped. The hand-written bullets this replaced are
archived in 0-old-outline.md.

Anchors are derived from the source rather than read out of the built HTML,
because docs/slides/*.html is gitignored -- the CI drift check (repo-checks.yml)
runs with no decks built. So slugify() reimplements pandoc's auto_identifiers
algorithm, and every heading is walked (not just section headers) because
pandoc's duplicate suffixes count all of them: week 10's `# Hierarchical
Clustering {.section-header}` takes `hierarchical-clustering` and the plain
`# Hierarchical Clustering` four slides later becomes `hierarchical-clustering-1`.

The link form is `weekN.html#/slug`. reveal.js writes that shape into the URL
bar itself (Location.getHash prepends "/"), and reads it back with a regex that
makes the slash optional, so this matches what a user sees after navigating.

A section header can opt out of the index with `{.section-header .no-index}` --
useful for dividers that are structural rather than topical, like week 6's
Appendix. Decks with no indexable section headers keep a placeholder bullet.

The script also owns the slide-count table at the bottom of the page, between
the SUMMARY_BEGIN/SUMMARY_END markers. That one covers every weekN deck source
found, week 0 included, so it is a wider list than the deck bullets above it. Its
Topics column comes from ../_data/schedule.csv, so week 0 -- which is not on the
schedule -- leaves that cell empty.

Note the .qmd download resolves only because the Pages workflow copies slide
sources into _site after Jekyll runs -- docs/_config.yml deliberately excludes
slides/*.qmd so Jekyll cannot render one over the real deck.

Usage:
  python3 sync_slide_index.py [slides-dir]
"""
import csv
import os
import re
import sys

MARKER = '<!-- generated by sync_slide_index.py -->'
SUMMARY_BEGIN = '<!-- begin slide-count table generated by sync_slide_index.py -->'
SUMMARY_END = '<!-- end slide-count table generated by sync_slide_index.py -->'
PLACEHOLDER = 'Topic details in-progress'
REPO_BLOB = 'https://github.com/jackbandy/data-science-fun/blob/main/docs/slides'
# _quarto.yml sets slide-level for every deck that does not override it.
DEFAULT_SLIDE_LEVEL = 1

# The course schedule, one row per class day, two rows per week.
SCHEDULE_CSV = os.path.join('..', '_data', 'schedule.csv')

HEADING_RE = re.compile(r'^(#{1,6})\s+(.*?)\s*$')
# A trailing pandoc attribute block: {#explicit-id .class key="value"}
ATTR_RE = re.compile(r'\{([^{}]*)\}\s*$')
FENCE_RE = re.compile(r'^\s*(```+|~~~+)')


# --------------------------------------------------------------------------
# Reading a deck source
# --------------------------------------------------------------------------

def deck_source(slides_dir, week):
    """(path, text) for a week's deck, or None. Decks are .qmd or plain .md."""
    for ext in ('qmd', 'md'):
        path = os.path.join(slides_dir, f'week{week}.{ext}')
        if os.path.exists(path):
            return path, open(path, encoding='utf-8').read()
    return None


def headings(source_text):
    """Every ATX heading in order, as (level, raw_text, attrs), skipping non-prose.

    Front matter and code chunks are full of `#` comment lines that would
    otherwise read as headings -- see the YAML comments atop week1.qmd and the
    R setup chunk in week5.qmd.
    """
    found = []
    lines = source_text.split('\n')
    i = 0
    # Strip YAML front matter, which must open on the very first line.
    if lines and lines[0].strip() == '---':
        for i in range(1, len(lines)):
            if lines[i].strip() in ('---', '...'):
                i += 1
                break
        else:
            i = len(lines)
    fence = None
    while i < len(lines):
        line = lines[i]
        i += 1
        opener = FENCE_RE.match(line)
        if fence is not None:
            # Only a fence of the same kind and at least the same length closes.
            if opener and opener.group(1)[0] == fence[0] and len(opener.group(1)) >= len(fence):
                fence = None
            continue
        if opener:
            fence = opener.group(1)
            continue
        m = HEADING_RE.match(line)
        if m:
            text = m.group(2)
            attrs = ''
            attr = ATTR_RE.search(text)
            if attr:
                attrs = attr.group(1)
                text = text[:attr.start()].strip()
            found.append((len(m.group(1)), text, attrs))
    return found


def strip_markup(text):
    """Heading text as pandoc sees it: inline formatting removed, not escaped."""
    text = re.sub(r'!?\[([^\]]*)\]\([^)]*\)', r'\1', text)   # links / images
    text = re.sub(r'<[^>]+>', '', text)                       # raw HTML
    text = re.sub(r'`([^`]*)`', r'\1', text)                  # code
    text = re.sub(r'(\*\*|__|\*|_)', '', text)                # emphasis
    return text.strip()


def slugify(text):
    """pandoc's auto_identifiers: what becomes the <section> id."""
    text = strip_markup(text)
    # Drop punctuation except underscores, hyphens and periods; spaces to dashes.
    text = ''.join(c for c in text if c.isalnum() or c in ' \t_-.')
    text = re.sub(r'[ \t]+', '-', text).lower()
    # Identifiers must start with a letter.
    text = re.sub(r'^[^a-z]+', '', text)
    return text or 'section'


def has_class(attrs, name):
    return re.search(r'(?:^|\s)\.' + re.escape(name) + r'(?:\s|$)', attrs) is not None


# --------------------------------------------------------------------------
# Turning a deck into bullets
# --------------------------------------------------------------------------

def topics(source_text):
    """[(text, anchor)] for the deck's indexable section headers."""
    found, seen = [], {}
    for _level, raw, attrs in headings(source_text):
        explicit = re.search(r'#([^\s}]+)', attrs)
        slug = explicit.group(1) if explicit else slugify(raw)
        # Pandoc disambiguates repeats with -1, -2, ... in document order.
        n = seen.get(slug, 0)
        seen[slug] = n + 1
        anchor = slug if n == 0 else f'{slug}-{n}'
        if has_class(attrs, 'section-header') and not has_class(attrs, 'no-index'):
            found.append((strip_markup(raw), anchor))
    return found


def slide_level(source_text):
    """The deck's slide-level: its own front matter, else _quarto.yml's default."""
    front = source_text.split('\n---', 1)[0] if source_text.startswith('---') else ''
    m = re.search(r'^slide-level:\s*(\d+)', front, re.MULTILINE)
    return int(m.group(1)) if m else DEFAULT_SLIDE_LEVEL


def slide_count(source_text):
    """How many slides the deck renders to.

    Quarto opens every deck with a title slide, then starts a new one at each
    heading of the deck's slide level or above -- shallower headings are section
    dividers, which reveal.js renders as their own slides too (navigation is
    linear here, so nothing is nested into a vertical stack). Counting the
    source this way matches `<section>` count of the built deck exactly.
    """
    level = slide_level(source_text)
    return 1 + sum(1 for lvl, _text, _attrs in headings(source_text) if lvl <= level)


def languages(source_text):
    """Human-readable list of the languages this deck executes, R first."""
    langs = [
        name for tag, name in (('r', 'R'), ('python', 'Python'))
        if re.search(r'^```\{' + tag + r'[ ,}]', source_text, re.MULTILINE)
    ]
    return ' + '.join(langs)


def artifact(slides_dir, week, source_path, source_text):
    """(target, kind) for a deck's code download, or None when it runs no code."""
    if not languages(source_text):
        return None
    # A notebook exists only for the jupyter engine; knitr decks fall back to
    # the source, which is the artifact that actually reproduces the deck.
    if os.path.exists(os.path.join(slides_dir, f'week{week}.ipynb')):
        return f'week{week}.ipynb', 'notebook'
    return os.path.basename(source_path), 'source'


def escape(text):
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def more_bullet(week, code, indent):
    """The "More:" bullet and its nested list of downloads.

    The deck title links the HTML slides, so everything else a week ships --
    the PDF, and the code for decks that run any -- hangs off here rather than
    crowding the title line.
    """
    inner = indent + '    '
    links = [f'{inner}<li><a href="week{week}.pdf">PDF version of slides</a></li>']
    if code:
        target, kind = code
        links.append(
            f'{inner}<li><a href="{REPO_BLOB}/{target}">'
            f'supporting code via GitHub</a></li>'
        )
        links.append(
            f'{inner}<li><a href="{target}">supporting code via raw {kind}</a></li>'
        )
    return [
        f'{indent}<li>{MARKER}More:',
        f'{indent}  <ul>',
        *links,
        f'{indent}  </ul>',
        f'{indent}</li>',
    ]


def bullets(slides_dir, week, indent):
    """Every <li> for one deck: topics first, then the "More:" downloads."""
    found = deck_source(slides_dir, week)
    if not found:
        return [f'{indent}<li>{MARKER}{PLACEHOLDER}</li>'], 0, None
    source_path, source_text = found

    deck_topics = topics(source_text)
    lines = [
        f'{indent}<li>{MARKER}'
        f'<a href="week{week}.html#/{anchor}">{escape(text)}</a></li>'
        for text, anchor in deck_topics
    ] or [f'{indent}<li>{MARKER}{PLACEHOLDER}</li>']

    code = artifact(slides_dir, week, source_path, source_text)
    lines.extend(more_bullet(week, code, indent))
    return lines, len(deck_topics), (code[1] if code else None)


# --------------------------------------------------------------------------
# Rewriting the index
# --------------------------------------------------------------------------

def close_of(text, open_ul):
    """Index of the </ul> matching the <ul> at open_ul, or -1.

    The generated bullets nest a list of their own under "More:", so the first
    </ul> after the opener is not necessarily the one that closes it.
    """
    depth = 0
    for m in re.finditer(r'<ul\b[^>]*>|</ul>', text[open_ul:]):
        depth += 1 if m.group(0) != '</ul>' else -1
        if depth == 0:
            return open_ul + m.start()
    return -1


def replace_block(text, week, build):
    """Swap the body of week N's nested <ul> for freshly generated bullets."""
    # The title line links the deck, so allow the anchor tag ahead of the text.
    # Anchoring to the start of the line keeps this off the summary table's rows.
    head = re.search(
        rf'^([ \t]*)(?:<a [^>]*>)?Week {week} Slide Deck\b', text, re.MULTILINE)
    if not head:
        return text, False
    # The deck's detail bullets are the first nested list after the heading line.
    open_ul = text.find('<ul>', head.end())
    close_ul = close_of(text, open_ul) if open_ul != -1 else -1
    if open_ul == -1 or close_ul == -1:
        return text, False
    ul_indent = re.search(r'([ \t]*)<ul>', text[max(0, open_ul - 40):open_ul + 4])
    indent = (ul_indent.group(1) + '  ') if ul_indent else '      '
    body_start = text.find('\n', open_ul) + 1
    body_end = text.rfind('\n', 0, close_ul) + 1
    return text[:body_start] + '\n'.join(build(indent)) + '\n' + text[body_end:], True


def replace_title(text, week, topic):
    """Rewrite the tail of week N's title line as the schedule topics.

    The line is left as `<a ...>Week N Slide Deck</a> (topics)`: the anchor is
    untouched, so only the title links the deck, and the parenthetical is plain
    text after it. Any existing tail is replaced rather than appended to, which
    keeps re-runs idempotent and lets a schedule edit propagate here.
    """
    line = re.compile(
        rf'^([ \t]*(?:<a [^>]*>)?Week {week} Slide Deck(?:</a>)?)[^\n]*$',
        re.MULTILINE)
    tail = f' ({escape(topic)})' if topic else ''
    new_text, n = line.subn(lambda m: m.group(1) + tail, text, count=1)
    return new_text, bool(n)


def schedule_topics(slides_dir):
    """{week: "topic; topic"} from the course schedule, blanks and repeats dropped.

    The schedule is the syllabus's own wording for what a week covers, so it is
    what the table reports -- deliberately a coarser view than the per-deck
    section headers listed above it. Both class days of a week collapse into one
    cell, keeping their order; days with no topic (holidays) contribute nothing.
    """
    path = os.path.normpath(os.path.join(slides_dir, SCHEDULE_CSV))
    if not os.path.exists(path):
        return {}
    by_week = {}
    with open(path, encoding='utf-8', newline='') as fh:
        for row in csv.DictReader(fh):
            week, topic = (row.get('Week') or '').strip(), (row.get('Topic') or '').strip()
            if not week.isdigit() or not topic:
                continue
            seen = by_week.setdefault(int(week), [])
            if topic not in seen:
                seen.append(topic)
    return {week: '; '.join(topics) for week, topics in by_week.items()}


def summary_table(slides_dir, weeks):
    """The whole slide-count table, one row per deck."""
    topics_by_week = schedule_topics(slides_dir)
    rows = []
    for week in weeks:
        found = deck_source(slides_dir, week)
        if not found:
            continue
        rows.append(
            f'      <tr><td><a href="week{week}.html">Week {week} Slide Deck</a></td>'
            f'<td>{slide_count(found[1])}</td>'
            f'<td>{escape(topics_by_week.get(week, ""))}</td></tr>'
        )
    return [
        SUMMARY_BEGIN,
        '<div class="schedule-table-wrap">',
        '  <table class="schedule-table">',
        '    <thead>',
        '      <tr><th>Slide Deck</th><th>Slides</th><th>Topics</th></tr>',
        '    </thead>',
        '    <tbody>',
        *rows,
        '    </tbody>',
        '  </table>',
        '</div>',
        SUMMARY_END,
    ]


def replace_summary(text, slides_dir, weeks):
    """Swap everything between the summary markers for a freshly counted table."""
    start = text.find(SUMMARY_BEGIN)
    end = text.find(SUMMARY_END)
    if start == -1 or end == -1:
        return text, False
    table = '\n'.join(summary_table(slides_dir, weeks))
    return text[:start] + table + text[end + len(SUMMARY_END):], True


def main(slides_dir):
    index = os.path.join(slides_dir, 'index.html')
    original = open(index, encoding='utf-8').read()

    weeks = sorted(
        int(m.group(1))
        for f in os.listdir(slides_dir)
        for m in [re.fullmatch(r'week(\d+)\.(?:qmd|md)', f)]
        if m
    )

    text = original
    topics_by_week = schedule_topics(slides_dir)
    written, skipped = [], []
    for week in weeks:
        text, _titled = replace_title(text, week, topics_by_week.get(week, ''))

        # Indent is only known once the week's <ul> is located, so pass a builder.
        stats = {}

        def build(indent, w=week, stats=stats):
            lines, n_topics, kind = bullets(slides_dir, w, indent)
            stats['topics'], stats['kind'] = n_topics, kind
            return lines

        text, placed = replace_block(text, week, build)
        if placed:
            n_topics, kind = stats['topics'], stats['kind']
            written.append(f'{week}:{n_topics}t' + (f'+{kind}' if kind else ''))
        else:
            skipped.append(str(week))

    text, summarized = replace_summary(text, slides_dir, weeks)

    if text != original:
        open(index, 'w', encoding='utf-8').write(text)
    note = f'; no index entry for week {", ".join(skipped)}' if skipped else ''
    if not summarized:
        note += '; slide-count table markers missing'
    print(f'[sync-index] wrote {len(written)}: {" ".join(written)}{note}', file=sys.stderr)


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__)))
