#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM (Claude) and has not been hand-verified.

Redraw Bertin's original visual variables as a golden-ratio landscape SVG.

Same conventions as ../pasteurs-quadrant and ../lifecycle-steps: a 1000 x 618
canvas, fonts self-hosted from ../fonts and embedded as base64 woff2 so the SVG
stands alone.

Differences from the reference raster (bertin-visual-variables.png, see
SOURCES.md): the demonstration panels sit on a light gray rather than a
saturated blue, so the panel background stops competing with the marks it is
supposed to be showing off -- value and colour in particular are unreadable
against a mid-value blue. The table splits at the golden section too: labels get
the minor part, demonstrations the major part.

Source of the original figure: Jacques Bertin, *Semiologie Graphique* (1967);
this layout follows the summary table in
https://datavizblog.com/2017/06/13/revisiting-tableau-desktop-fundamentals/
"""

from __future__ import annotations

import base64
import colorsys
from pathlib import Path
from xml.sax.saxutils import escape


PHI = (1 + 5**0.5) / 2
WIDTH = 1000
HEIGHT = round(WIDTH / PHI)  # 618

OUT_DIR = Path(__file__).resolve().parent
OUT_FILE = OUT_DIR / "bertins-visual-variables.svg"

PAGE = "#FFFFFF"
PANEL = "#EEEEEE"  # STYLE.md neutral fill; replaces the original's blue
INK = "#111111"
MUTED = "#555555"
QUIET = "#777777"  # credit line only
RULE = "#C4C4C4"
BORDER = "#111111"

TITLE_FONT = "Big Shoulders"
BODY_FONT = "Libre Franklin"
FONTS = [
    (TITLE_FONT, "BigShoulders.woff2", "../fonts/big-shoulders"),
    (BODY_FONT, "LibreFranklin.woff2", "../fonts/libre-franklin"),
]

TITLE = "Bertin's Original Visual Variables"
CREDIT = "Based on Michael Sandberg's summary of visual variables proposed by Jacques Bertin, Sémiologie Graphique (1967)"

# Table geometry.
MARGIN = 16
TABLE_X = MARGIN
TABLE_W = WIDTH - 2 * MARGIN  # 968
TABLE_TOP = 72
TABLE_BOTTOM = 578  # leaves the bottom margin for the credit line
FOOTER_Y = 604
TABLE_H = TABLE_BOTTOM - TABLE_TOP  # 506

# The label / demonstration split is itself the golden section, with the
# demonstrations taking the major part.
LABEL_W = round(TABLE_W * (1 - 1 / PHI))  # 370
PANEL_X = TABLE_X + LABEL_W
PANEL_W = TABLE_W - LABEL_W

ROWS = [
    ("Position", "changes in the x, y location"),
    ("Size", "change in length, area or repetition"),
    ("Shape", "infinite number of shapes"),
    ("Value", "changes from light to dark"),
    ("Colour", "changes in hue at a given value"),
    ("Orientation", "changes in alignment"),
    ("Texture", "variation in 'grain'"),
]
ROW_H = TABLE_H / len(ROWS)

LABEL_PAD = 14
PANEL_PAD_X = 14
PANEL_PAD_Y = 6


# --------------------------------------------------------------------------
# small drawing helpers
# --------------------------------------------------------------------------


def rect(x, y, w, h, fill=INK, stroke=None, stroke_width=1.0, rx=0) -> str:
    parts = [
        f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}"',
        f'rx="{rx}"' if rx else "",
        f'fill="{fill}"',
        f'stroke="{stroke}" stroke-width="{stroke_width}"' if stroke else "",
    ]
    return "  " + " ".join(part for part in parts if part) + "/>"


def polygon(points, fill=INK) -> str:
    coords = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    return f'  <polygon points="{coords}" fill="{fill}"/>'


def spread(x, width, count, item_width):
    """Left coordinates for `count` items spaced evenly across `width`."""
    if count == 1:
        return [x + (width - item_width) / 2]
    gap = (width - count * item_width) / (count - 1)
    return [x + index * (item_width + gap) for index in range(count)]


def lay_out(x, width, widths):
    """Left coordinates for items of differing widths, equal gaps between them."""
    if len(widths) == 1:
        return [x + (width - widths[0]) / 2]
    gap = (width - sum(widths)) / (len(widths) - 1)
    lefts = []
    cursor = x
    for item_width in widths:
        lefts.append(cursor)
        cursor += item_width + gap
    return lefts


# --------------------------------------------------------------------------
# one function per visual variable
# --------------------------------------------------------------------------


def draw_position(x, y, w, h) -> list[str]:
    """The same mark, moved: only x and y differ."""
    size = 30
    # Fractions of the *free* space, so every mark lands wholly inside the panel
    # however the row geometry changes.
    spots = [(0.05, 0.62), (0.38, 0.98), (0.52, 0.02), (0.84, 0.55)]
    marks = []
    for fx, fy in spots:
        left = x + fx * (w - size)
        top = y + fy * (h - size)
        marks.append(polygon([(left, top), (left, top + size), (left + size, top + size)]))
    return marks


def draw_size(x, y, w, h) -> list[str]:
    """Three demonstrations -- length, area, repetition -- in three sub-panels."""
    gap = 14
    sub_w = (w - 2 * gap) / 3
    baseline = y + h - 10
    out = []

    # Length: bars of one width, four heights.
    bx = x
    bar_w = 11
    heights = [h - 18, h * 0.62, h * 0.40, h * 0.18]
    for left, bar_h in zip(spread(bx + 12, sub_w - 24, 4, bar_w), heights):
        out.append(rect(left, baseline - bar_h, bar_w, bar_h))

    # Area: squares of three sides, sharing a baseline.
    ax = x + sub_w + gap
    sides = [14, 26, 40]
    for left, side in zip(lay_out(ax + 14, sub_w - 28, sides), sides):
        out.append(rect(left, baseline - side, side, side))

    # Repetition: one mark, then nine, then twenty-five -- the mark never changes
    # size, only how many of it there are.
    rx = x + 2 * (sub_w + gap)
    dot, dot_gap = 6, 3
    counts = (1, 3, 5)
    fields = [n * dot + (n - 1) * dot_gap for n in counts]
    for left, n, field in zip(lay_out(rx + 12, sub_w - 24, fields), counts, fields):
        top = y + (h - field) / 2
        for row in range(n):
            for col in range(n):
                out.append(
                    rect(left + col * (dot + dot_gap), top + row * (dot + dot_gap), dot, dot)
                )
    return out


def draw_shape(x, y, w, h) -> list[str]:
    """Eight silhouettes at a constant area, so only outline varies."""
    size = 34
    cy = y + h / 2
    out = []
    for index, left in enumerate(spread(x, w, 8, size)):
        cx = left + size / 2
        r = size / 2
        if index == 0:  # cross
            arm = r * 0.42
            out.append(
                polygon(
                    [
                        (cx - arm, cy - r), (cx + arm, cy - r), (cx + arm, cy - arm),
                        (cx + r, cy - arm), (cx + r, cy + arm), (cx + arm, cy + arm),
                        (cx + arm, cy + r), (cx - arm, cy + r), (cx - arm, cy + arm),
                        (cx - r, cy + arm), (cx - r, cy - arm), (cx - arm, cy - arm),
                    ]
                )
            )
        elif index == 1:  # octagon
            out.append(polygon(_regular(cx, cy, r, 8, 22.5)))
        elif index == 2:  # triangle
            out.append(polygon([(cx, cy - r), (cx + r, cy + r * 0.8), (cx - r, cy + r * 0.8)]))
        elif index == 3:  # parallelogram
            out.append(
                polygon(
                    [
                        (cx - r * 0.4, cy - r * 0.7), (cx + r, cy - r * 0.7),
                        (cx + r * 0.4, cy + r * 0.7), (cx - r, cy + r * 0.7),
                    ]
                )
            )
        elif index == 4:  # ellipse
            out.append(
                f'  <ellipse cx="{cx:.1f}" cy="{cy:.1f}" rx="{r * 0.78:.1f}" '
                f'ry="{r:.1f}" fill="{INK}"/>'
            )
        elif index == 5:  # hexagon
            out.append(polygon(_regular(cx, cy, r, 6, 0)))
        elif index == 6:  # pentagon
            out.append(polygon(_regular(cx, cy, r, 5, 0)))
        else:  # trapezoid
            out.append(
                polygon(
                    [
                        (cx - r, cy - r * 0.75), (cx + r, cy - r * 0.75),
                        (cx + r * 0.45, cy + r * 0.75), (cx - r * 0.45, cy + r * 0.75),
                    ]
                )
            )
    return out


def _regular(cx, cy, r, sides, rotation_degrees) -> list[tuple[float, float]]:
    from math import cos, radians, sin

    return [
        (
            cx + r * sin(radians(rotation_degrees) + 2 * 3.141592653589793 * i / sides),
            cy - r * cos(radians(rotation_degrees) + 2 * 3.141592653589793 * i / sides),
        )
        for i in range(sides)
    ]


def draw_value(x, y, w, h) -> list[str]:
    """A ten-step ramp, white to black, at one hue (none) and one size."""
    side = min(h - 8, (w - 9 * 8) / 10)
    top = y + (h - side) / 2
    out = []
    for index, left in enumerate(spread(x, w, 10, side)):
        level = round(255 * (1 - index / 9))
        fill = f"#{level:02X}{level:02X}{level:02X}"
        out.append(rect(left, top, side, side, fill=fill, stroke=INK, stroke_width=1))
    return out


def draw_colour(x, y, w, h) -> list[str]:
    """Ten hues held at one lightness and saturation -- hue alone varies."""
    side = min(h - 8, (w - 9 * 8) / 10)
    top = y + (h - side) / 2
    out = []
    for index, left in enumerate(spread(x, w, 10, side)):
        red, green, blue = colorsys.hls_to_rgb(index / 10, 0.72, 0.62)
        fill = "#%02X%02X%02X" % (round(red * 255), round(green * 255), round(blue * 255))
        out.append(rect(left, top, side, side, fill=fill, stroke=INK, stroke_width=1))
    return out


ORIENTATIONS = (0, 45, 90, 135)
GRAINS = ((5, 1.6), (8, 2.4), (12, 3.4), (18, 4.6))


def draw_orientation(x, y, w, h) -> list[str]:
    """One stripe pattern at four alignments."""
    side = h - 8
    top = y + (h - side) / 2
    out = []
    for index, left in enumerate(spread(x + w * 0.08, w * 0.84, len(ORIENTATIONS), side)):
        out.append(
            rect(left, top, side, side, fill=f"url(#stripes{index})", stroke=INK, stroke_width=1)
        )
    return out


def draw_texture(x, y, w, h) -> list[str]:
    """One pattern at four grains: same mark, coarser and coarser."""
    side = h - 8
    top = y + (h - side) / 2
    out = []
    lefts = spread(x + w * 0.04, w * 0.92, 2 * len(GRAINS), side)
    for index in range(len(GRAINS)):
        out.append(
            rect(lefts[index], top, side, side, fill=f"url(#grid{index})", stroke=INK, stroke_width=1)
        )
    for index in range(len(GRAINS)):
        out.append(
            rect(
                lefts[len(GRAINS) + index], top, side, side,
                fill=f"url(#dots{index})", stroke=INK, stroke_width=1,
            )
        )
    return out


DRAWERS = [
    draw_position,
    draw_size,
    draw_shape,
    draw_value,
    draw_colour,
    draw_orientation,
    draw_texture,
]


# --------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------


def defs() -> str:
    out = []
    for index, angle in enumerate(ORIENTATIONS):
        out.append(
            f'    <pattern id="stripes{index}" width="10" height="10" '
            f'patternUnits="userSpaceOnUse" patternTransform="rotate({angle})">\n'
            f'      <rect width="10" height="10" fill="{PAGE}"/>\n'
            f'      <rect width="10" height="5" fill="{INK}"/>\n'
            f"    </pattern>"
        )
    for index, (step, weight) in enumerate(GRAINS):
        out.append(
            f'    <pattern id="grid{index}" width="{step}" height="{step}" '
            f'patternUnits="userSpaceOnUse">\n'
            f'      <rect width="{step}" height="{step}" fill="{PAGE}"/>\n'
            f'      <path d="M0 0 H{step} M0 0 V{step}" stroke="{INK}" '
            f'stroke-width="{weight}"/>\n'
            f"    </pattern>"
        )
    for index, (step, weight) in enumerate(GRAINS):
        out.append(
            f'    <pattern id="dots{index}" width="{step}" height="{step}" '
            f'patternUnits="userSpaceOnUse">\n'
            f'      <rect width="{step}" height="{step}" fill="{PAGE}"/>\n'
            f'      <circle cx="{step / 2}" cy="{step / 2}" r="{weight * 0.62:.2f}" '
            f'fill="{INK}"/>\n'
            f"    </pattern>"
        )
    return "\n".join(out)


DESCRIPTION_SIZE = 15
# Rough average advance per character for Libre Franklin at lowercase-mixed
# text, in ems. Only used to shrink a gloss that would otherwise run past the
# label column -- the glosses all fit at full size today.
AVERAGE_ADVANCE = 0.52


def draw_label(name: str, description: str, top: float) -> str:
    """Name and gloss, left aligned, vertically centred in the row.

    The gloss always sets on one line: these are captions, and a caption that
    wraps reads as a second, subordinate thought that isn't there.
    """
    x = TABLE_X + LABEL_PAD
    available = LABEL_W - 2 * LABEL_PAD
    estimated = len(description) * AVERAGE_ADVANCE * DESCRIPTION_SIZE
    size = DESCRIPTION_SIZE if estimated <= available else available / (len(description) * AVERAGE_ADVANCE)

    block_height = 24 + 19
    name_y = top + (ROW_H - block_height) / 2 + 21

    return (
        f'  <text x="{x}" y="{name_y:.1f}" font-family="{BODY_FONT}" font-size="23" '
        f'font-weight="700" fill="{INK}">{escape(name)}</text>\n'
        f'  <text x="{x}" y="{name_y + 24:.1f}" font-family="{BODY_FONT}" '
        f'font-size="{size:.1f}" font-weight="400" fill="{MUTED}">{escape(description)}</text>'
    )


def draw_rows() -> str:
    out = []
    for index, ((name, description), drawer) in enumerate(zip(ROWS, DRAWERS)):
        top = TABLE_TOP + index * ROW_H
        out.append(draw_label(name, description, top))

        panel_x = PANEL_X + 8
        panel_y = top + PANEL_PAD_Y
        panel_w = PANEL_W - 16
        panel_h = ROW_H - 2 * PANEL_PAD_Y

        if name == "Size":
            # Three sub-panels: length, area, repetition are three separate claims.
            gap = 14
            sub_w = (panel_w - 2 * gap) / 3
            for sub in range(3):
                out.append(
                    rect(panel_x + sub * (sub_w + gap), panel_y, sub_w, panel_h, fill=PANEL, rx=3)
                )
        else:
            out.append(rect(panel_x, panel_y, panel_w, panel_h, fill=PANEL, rx=3))

        out.extend(
            drawer(
                panel_x + PANEL_PAD_X,
                panel_y + 4,
                panel_w - 2 * PANEL_PAD_X,
                panel_h - 8,
            )
        )
    return "\n".join(out)


def draw_frame() -> str:
    out = [
        f'  <rect x="{TABLE_X}" y="{TABLE_TOP}" width="{TABLE_W}" height="{TABLE_H}" '
        f'fill="none" stroke="{BORDER}" stroke-width="1.5"/>',
        f'  <line x1="{PANEL_X}" y1="{TABLE_TOP}" x2="{PANEL_X}" y2="{TABLE_BOTTOM}" '
        f'stroke="{RULE}" stroke-width="1"/>',
    ]
    for index in range(1, len(ROWS)):
        y = TABLE_TOP + index * ROW_H
        out.append(
            f'  <line x1="{TABLE_X}" y1="{y:.1f}" x2="{TABLE_X + TABLE_W}" y2="{y:.1f}" '
            f'stroke="{RULE}" stroke-width="1"/>'
        )
    return "\n".join(out)


def draw_footer() -> str:
    return (
        f'  <text x="{TABLE_X + TABLE_W}" y="{FOOTER_Y}" text-anchor="end" '
        f'font-family="{BODY_FONT}" font-size="10.5" font-weight="400" '
        f'fill="{QUIET}">{escape(CREDIT)}</text>'
    )


def font_faces() -> str:
    faces = []
    for family, filename, upstream in FONTS:
        encoded = base64.b64encode((OUT_DIR / upstream / filename).read_bytes()).decode("ascii")
        faces.append(
            f"    @font-face {{\n"
            f"      font-family: '{family}';\n"
            f"      src: url('data:font/woff2;base64,{encoded}') format('woff2');\n"
            f"      font-weight: 100 900;\n"
            f"      font-style: normal;\n"
            f"    }}"
        )
    return "\n".join(faces)


def make_svg() -> str:
    return f"""<svg width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="{WIDTH}" height="{HEIGHT}" fill="{PAGE}"/>
  <style>
{font_faces()}
  </style>
  <defs>
{defs()}
  </defs>
  <text x="{WIDTH / 2}" y="52" text-anchor="middle" font-family="{TITLE_FONT}"
        font-size="46" font-weight="700" fill="{INK}">{escape(TITLE)}</text>
{draw_rows()}
{draw_frame()}
{draw_footer()}
</svg>
"""


def main() -> None:
    OUT_FILE.write_text(make_svg(), encoding="utf-8")
    print(f"wrote {OUT_FILE.relative_to(OUT_DIR.parent)}")


if __name__ == "__main__":
    main()
