#!/usr/bin/env python3
# NOTICE: Generated by an LLM coding agent. Review/edit/test before relying on it.
"""Post-process a Quarto reveal.js slide deck.

For .ipynb notebooks:
  1. Replace the YAML frontmatter cell with a plain title heading.
  2. Split markdown cells so one notebook cell holds one slide.
  3. Insert a compilation timestamp into the Sources slide.
  4. Strip the Quarto-only markup students have no use for: fenced divs,
     heading/span attributes, <style> and <script> blocks, #| cell options.
  5. Add a <!-- slide N --> comment before each slide heading.
  6. Clear code-cell outputs, so the committed notebooks stay small.

For .qmd / .md files:
  3. Insert a compilation timestamp into the Sources slide.
     (Replaces stamp_source_note.py for standalone use.)

Usage:
  python3 postprocess_slides.py deck.ipynb
  python3 postprocess_slides.py deck.qmd
"""
import json
import os
import re
import sys
from datetime import datetime
from zoneinfo import ZoneInfo

NOTE_PREFIX = "Last modified and compiled "
# The closing --- can be the very end of the cell, with no trailing newline —
# which is what Quarto emits when the frontmatter is the whole first cell.
FRONTMATTER_RE = re.compile(r'\A---\n.*?\n---[ \t]*(?:\n|\Z)', re.DOTALL)
SLIDE_SEP_RE = re.compile(r'(?m)^---[ \t]*$')
HEADING_RE = re.compile(r'(?m)^# .+')
# The decks set slide-level: 2, so a slide starts at a level-1 heading (a
# section divider) or a level-2 heading.
SLIDE_HEADING_RE = re.compile(r'^#{1,2} +\S')
# A ``` or ~~~ fence inside a markdown cell holds a code sample: the # lines in
# it are Python comments, not headings, and must not be read as slide starts.
CODE_FENCE_RE = re.compile(r'^ {0,3}(```+|~~~+)')
# Pandoc fenced div: ::: {.columns}, :::: {.r-stack}, or a bare :::
DIV_FENCE_RE = re.compile(r'^:{3,}[ \t]*(?:\{[^{}]*\}|[A-Za-z][\w-]*)?[ \t]*$')
# Trailing attributes on a heading: ## Rectangular Data {.smaller}
HEADING_ATTR_RE = re.compile(r'[ \t]*\{[^{}]*\}[ \t]*$')
# Bracketed span: [WORKED THROUGH]{.eyebrow} -> WORKED THROUGH
SPAN_ATTR_RE = re.compile(r'\[([^\[\]]*)\]\{[^{}]*\}')
# Attributes hung off a link or image: ![](fig.svg){.figure alt="..."}
LINK_ATTR_RE = re.compile(r'(!?\[[^\[\]]*\]\([^()]*\))\{[^{}]*\}')
# Quarto cell options: #| echo: false
CELL_OPTION_RE = re.compile(r'(?m)^#\|[^\n]*\n?')
# Slide widgets (the roll-call draw, mostly): a page's worth of CSS and JS that
# does nothing in a notebook.
RAW_BLOCK_RE = re.compile(r'(?is)<(style|script)\b[^>]*>.*?</\1>[ \t]*\n?')


# ── shared helpers ───────────────────────────────────────────────────────────

def _now_stamp():
    dt = datetime.now(ZoneInfo("America/Chicago"))
    return f"{NOTE_PREFIX}{dt:%B} {dt.day}, {dt:%H:%M}h Central (Chicago) time."


def _list_marker(line):
    """Return (indent, marker, spacing) for a markdown list item, or None."""
    m = re.match(r'^(\s*)([0-9]+[.)]|[-*+])(\s+)', line)
    if not m:
        return None
    indent, mk, sp = m.group(1), m.group(2), m.group(3)
    if mk[-1] in '.)':
        mk = '1' + mk[-1]
    return indent, mk, sp


def _stamp_lines(lines, note):
    """Insert timestamp after the GitHub source line (or best fallback).

    Operates on a list of strings (lines without trailing newline for the last,
    with \\n for the rest — or just plain lines). Mutates in place.
    """
    start = next(
        (i for i, l in enumerate(lines)
         if l.lstrip().startswith('#') and '.sources' in l),
        None,
    )
    if start is None:
        return

    end = next(
        (i for i in range(start + 1, len(lines)) if lines[i].strip() == '---'),
        len(lines),
    )
    block = range(start + 1, end)

    def insert_after(idx, mk):
        indent, marker, sp = mk
        lines.insert(idx + 1, f'{indent}{marker}{sp}{note}')

    # 1) After the GitHub source bullet
    for i in block:
        mk = _list_marker(lines[i])
        if 'GitHub source:' in lines[i] and mk:
            insert_after(i, mk)
            return

    # 2) After the "built with Quarto" line
    for i in block:
        if 'Quarto' in lines[i] and 'built' in lines[i].lower():
            mk = _list_marker(lines[i]) or ('', '1.', ' ')
            insert_after(i, mk)
            return

    # 3) After the last list item in the slide
    last = max((i for i in block if _list_marker(lines[i])), default=None)
    if last is not None:
        insert_after(last, _list_marker(lines[last]))
        return

    # 4) Fallback: before slide end
    lines.insert(end, note)


# ── .qmd / .md ───────────────────────────────────────────────────────────────

def process_qmd(path):
    text = open(path, encoding='utf-8').read()
    if NOTE_PREFIX in text:
        return
    note = _now_stamp()
    lines = text.split('\n')
    _stamp_lines(lines, note)
    open(path, 'w', encoding='utf-8').write('\n'.join(lines))


# ── .ipynb ────────────────────────────────────────────────────────────────────

def _src(cell):
    return ''.join(cell.get('source', []))


def _set_src(cell, text):
    """Write source back as a list of lines (preserving notebook conventions)."""
    if not text:
        cell['source'] = []
        return
    lines = text.split('\n')
    # Each line except the last gets a trailing \n, matching nbformat conventions.
    result = [line + '\n' for line in lines[:-1]]
    if lines[-1]:
        result.append(lines[-1])
    cell['source'] = result


def _code_fence_mask(lines):
    """True for every line inside (or delimiting) a ``` / ~~~ code fence."""
    mask = [False] * len(lines)
    fence = None
    for i, line in enumerate(lines):
        m = CODE_FENCE_RE.match(line)
        if fence is None:
            if m:
                fence = m.group(1)[0] * 3
                mask[i] = True
            continue
        mask[i] = True
        if m and line.strip().startswith(fence):
            fence = None
    return mask


def _split_slides(src):
    """Split one markdown cell into one chunk per slide.

    Slides break at a standalone --- (dropped: the cell boundary replaces it)
    and at every level-1/level-2 heading. A leading chunk with no heading is
    the tail of the slide that the previous cell started.
    """
    lines = src.split('\n')
    mask = _code_fence_mask(lines)
    chunks, current = [], []

    for i, line in enumerate(lines):
        if not mask[i]:
            if SLIDE_SEP_RE.match(line):
                chunks.append(current)
                current = []
                continue
            if SLIDE_HEADING_RE.match(line) and any(l.strip() for l in current):
                chunks.append(current)
                current = []
        current.append(line)

    chunks.append(current)
    return ['\n'.join(c).strip('\n') for c in chunks]


def _clean_markdown(src):
    """Drop the Quarto/reveal.js markup that means nothing in a notebook."""
    src = RAW_BLOCK_RE.sub('', src)
    lines = src.split('\n')
    mask = _code_fence_mask(lines)
    out = []

    for i, line in enumerate(lines):
        if mask[i]:
            out.append(line)
            continue
        if DIV_FENCE_RE.match(line):
            continue
        if line.startswith('#'):
            line = HEADING_ATTR_RE.sub('', line)
        line = LINK_ATTR_RE.sub(r'\1', line)
        line = SPAN_ATTR_RE.sub(r'\1', line)
        out.append(line)

    return re.sub(r'\n{3,}', '\n\n', '\n'.join(out)).strip('\n')


def process_ipynb(path):
    nb = json.loads(open(path, encoding='utf-8').read())
    cells = nb['cells']

    # Running twice would split the split cells again and number them a second
    # time; the build always starts from a fresh .quarto_ipynb, so bail out.
    if any('<!-- slide ' in _src(c) for c in cells):
        print(f'[postprocess] {path}: already processed, skipping', file=sys.stderr)
        return

    # 1. Drop the YAML frontmatter cell, keeping the title for a heading cell
    #    added at the end (added last so it does not shift the slide numbers).
    title = None
    for cell in cells:
        if cell['cell_type'] == 'markdown':
            src = _src(cell)
            m = FRONTMATTER_RE.match(src)
            if m:
                for ln in m.group(0).splitlines():
                    if ln.startswith('title:'):
                        title = ln.split(':', 1)[1].strip().strip('"\'')
                after_fm = src[m.end():]
                h1 = HEADING_RE.search(after_fm)
                _set_src(cell, after_fm[h1.start():] if h1 else after_fm.lstrip('\n'))
            break

    # 2. Stamp the Sources slide before cleaning, while the {.sources} class
    #    that identifies it is still on the heading. Idempotent.
    note = _now_stamp()
    for cell in cells:
        if cell['cell_type'] != 'markdown':
            continue
        src = _src(cell)
        if NOTE_PREFIX in src:
            break
        if '.sources' in src:
            lines = src.split('\n')
            _stamp_lines(lines, note)
            _set_src(cell, '\n'.join(lines))
            break

    # 3. One cell per slide, cleaned; chunks left empty by the cleaning (a
    #    stray ::: closing a div that opened on the previous slide) are dropped.
    split_cells = []
    for cell in cells:
        if cell['cell_type'] != 'markdown':
            split_cells.append(cell)
            continue
        for n, piece in enumerate(_split_slides(_src(cell))):
            piece = _clean_markdown(piece)
            # Nothing left but whitespace, or a heading whose text was entirely
            # attributes (## {.photo-only ...}, a full-bleed photo slide).
            if not piece.strip() or re.fullmatch(r'#{1,6}[ \t]*', piece.strip()):
                continue
            part = dict(cell)
            if 'id' in part and n:
                part['id'] = f'{part["id"]}-{n}'[:64]
            _set_src(part, piece)
            split_cells.append(part)
    cells = nb['cells'] = split_cells

    # 4. Number the slides.
    slide_num = 0
    for cell in cells:
        if cell['cell_type'] != 'markdown':
            continue
        lines = _src(cell).split('\n')
        mask = _code_fence_mask(lines)
        out = []
        for i, line in enumerate(lines):
            if not mask[i] and SLIDE_HEADING_RE.match(line):
                slide_num += 1
                out.append(f'<!-- slide {slide_num} -->')
            out.append(line)
        _set_src(cell, '\n'.join(out))

    # 5. Drop Quarto cell options (#| echo: false and friends) from code cells.
    for cell in cells:
        if cell['cell_type'] == 'code':
            _set_src(cell, CELL_OPTION_RE.sub('', _src(cell)).strip('\n'))

    if title:
        cells.insert(0, {
            'cell_type': 'markdown',
            'id': 'deck-title',
            'metadata': {},
            'source': [f'# {title}'],
        })

    # The kernel Quarto records points at this machine's .venv; students get a
    # notebook that runs against whatever kernel they open it with.
    nb.get('metadata', {}).get('kernelspec', {}).pop('path', None)

    # 6. Strip execution outputs. These notebooks are committed (see the
    #    !docs/slides/*.ipynb negation in .gitignore) so students can download
    #    them, and the decks render figures as SVG -- which Jupyter embeds as
    #    inline markup, pushing a single notebook past 20 MB and writing a fresh
    #    multi-megabyte blob into git on every rebuild. Shipping code-only
    #    notebooks keeps them small and makes their diffs readable; students run
    #    the cells to produce the output.
    stripped = 0
    for cell in cells:
        if cell['cell_type'] != 'code':
            continue
        if cell.get('outputs'):
            stripped += 1
        cell['outputs'] = []
        cell['execution_count'] = None

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)

    size_kb = os.path.getsize(path) / 1024
    print(
        f'[postprocess] {path}: {slide_num} slides, '
        f'cleared outputs from {stripped} cells, {size_kb:.0f} KB',
        file=sys.stderr,
    )


# ── entry point ───────────────────────────────────────────────────────────────

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(f'Usage: {sys.argv[0]} <deck.ipynb|deck.qmd|deck.md>')
    path = sys.argv[1]
    if path.endswith('.ipynb'):
        process_ipynb(path)
    else:
        process_qmd(path)
