#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM (Claude) and has not been hand-verified.

Draw "hours of video in one terabyte" as a golden-ratio landscape SVG: an interval
per resolution, because there is no single right answer. Resolution does not
determine file size -- bitrate does -- so every row is a range, not a number.

Writes TWO files, same data and same layout, differing only in x scale:

    terabyte-video-hours-log.svg      log axis, the one on the slide
    terabyte-video-hours-linear.svg   linear axis

The linear one is worth keeping precisely because it fails: 8K and 4K collapse
into slivers against 480p's 889 hours, which is the argument for the log axis
rather than a decoration on it.

Same conventions as ../iliinsky-visual-properties and ../pasteurs-quadrant: a
1000 x 618 canvas, fonts self-hosted from ../fonts and embedded as base64 woff2 so
the SVG stands alone (see ../STYLE.md). Deliberately all-neutral -- no orange --
because no single row is the focal one; the spread is the point.

Pills run left to right, so further right means "a terabyte lasts longer". Each
interval spans YouTube's own recommended upload bitrates for that resolution, from
the cheapest encode it lists (SDR at standard frame rate) to the most expensive
(HDR at high frame rate). One published table, one consistent meaning for every
pill. Hours follow by exact arithmetic, no estimation:

    1 TB = 8e12 bits, so hours = 8e12 / (Mbps * 1e6 * 3600) = 2222.2 / Mbps

Real streaming services run below even the low-bitrate end of these bands -- see
SOURCES.md for the Netflix comparison and why that does not contradict the
"~30 hours of 4K" figure on the slide next door.

Source: YouTube Help, "Recommended upload encoding settings",
https://support.google.com/youtube/answer/1722171
"""

from __future__ import annotations

import base64
from math import log10
from pathlib import Path
from xml.sax.saxutils import escape


PHI = (1 + 5**0.5) / 2
WIDTH = 1000
HEIGHT = round(WIDTH / PHI)  # 618

OUT_DIR = Path(__file__).resolve().parent

PAGE = "#FFFFFF"
INK = "#111111"
TEXT = "#333333"
MUTED = "#777777"
GRID = "#E8E8E8"
RULE = "#DDDDDD"
BAR_FILL = "#EEEEEE"

TITLE_FONT = "Big Shoulders"
BODY_FONT = "Libre Franklin"
FONTS = [
    (TITLE_FONT, "BigShoulders.woff2", "../fonts/big-shoulders"),
    (BODY_FONT, "LibreFranklin.woff2", "../fonts/libre-franklin"),
]

TITLE = "Hours of Video in One Terabyte"
SUBTITLE = "Each pill spans YouTube's recommended bitrates: SDR/standard frame rate to HDR/high frame rate. 480p ≈ DVD."
CREDIT = (
    "Bitrates: YouTube Help, “Recommended upload encoding settings.” "
    "1 TB = 1,000,000,000,000 bytes."
)

# 1 TB = 8e12 bits; one hour at B Mbps is B * 3.6e9 bits.
BITS_PER_TB = 8e12
BITS_PER_MBPS_HOUR = 1e6 * 3600

# (row label, cheapest encode Mbps, most expensive encode Mbps) -- straight from
# YouTube's table. 480p lists no HDR, so its high end is SDR at high frame rate.
# Heaviest format first, so the pills step down the page from left to right.
ROWS = [
    ("8K", 80, 300),
    ("4K UHD", 35, 85),
    ("1440p", 16, 30),
    ("1080p", 8, 15),
    ("720p", 5, 9.5),
    ("480p", 2.5, 4),
]

# Width budget for each row label, in px per px of font-size, at weight 700.
#
# Measured, not derived, and deliberately on the generous side. fontTools reports
# the *default* instance of this variable font (wght=100); instantiating at
# wght=700 still lands up to 42% under what a browser lays out, so it cannot be
# trusted here. These numbers come from canvas measureText() in headless Chrome
# with the real embedded woff2, divided by font size (width is linear in size;
# checked at 22/24/26/28).
#
# Canvas in turn runs wider than SVG text actually renders -- "4K UHD" budgets 82px
# at size 22 but paints 58px -- so this table over-reserves by roughly a third.
# That is the safe direction: the cost is occasionally banishing a label to the
# outside of a pill it would have squeaked into, versus a label spilling over the
# edge of a pill on a projector.
#
# Add a row above and you must add its label here too -- label_width() raises
# rather than guess, because guessing is what breaks the layout silently.
LABEL_WIDTH_PER_PX = {
    "8K": 30.7 / 24,
    "4K UHD": 90.0 / 24,
    "1440p": 61.3 / 24,
    "1080p": 61.3 / 24,
    "720p": 49.3 / 24,
    "480p": 49.3 / 24,
}

MARGIN = 48
# No left gutter for row labels any more -- they ride inside their pills -- so the
# plot takes nearly the full canvas.
PLOT_LEFT = 100
PLOT_RIGHT = 900
PLOT_TOP = 112
ROW_PITCH = 62
AXIS_Y = 496
TICK_LABEL_Y = 518
AXIS_TITLE_Y = 542
CREDIT_Y = 596

BAR_H = 34            # tall enough to seat the row label inside
PILL_DROP = 22        # pill centre, measured from the top of its row
LABEL_DROP = 31       # hours-label baseline, measured from the pill centre
ROW_LABEL_SIZE = 22
HOURS_LABEL_SIZE = 13
LABEL_PAD = 10        # clear space each side of a label sitting inside a pill

SCALES = [
    ("log", [10, 30, 100, 300, 1000], 6.0, 1000.0, "Hours of video per terabyte (log scale)"),
    ("linear", [0, 200, 400, 600, 800], 0.0, 900.0, "Hours of video per terabyte (linear scale)"),
]


def hours_at(mbps: float) -> float:
    return BITS_PER_TB / (mbps * BITS_PER_MBPS_HOUR)


def label_width(label: str, size: float) -> float:
    if label not in LABEL_WIDTH_PER_PX:
        raise KeyError(f"no measured width for {label!r} -- see LABEL_WIDTH_PER_PX")
    return LABEL_WIDTH_PER_PX[label] * size


def x_at(hours: float, kind: str, lo: float, hi: float) -> float:
    span = PLOT_RIGHT - PLOT_LEFT
    if kind == "log":
        fraction = (log10(hours) - log10(lo)) / (log10(hi) - log10(lo))
    else:
        fraction = (hours - lo) / (hi - lo)
    return PLOT_LEFT + fraction * span


def pill_center(index: int) -> float:
    return PLOT_TOP + index * ROW_PITCH + PILL_DROP


# --------------------------------------------------------------------------
# small drawing helpers -- same signatures as the other generators in this repo
# --------------------------------------------------------------------------


def rect(x, y, w, h, fill=BAR_FILL, stroke=None, stroke_width=1.0, rx=0) -> str:
    parts = [
        f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}"',
        f'rx="{rx}"' if rx else "",
        f'fill="{fill}"',
        f'stroke="{stroke}" stroke-width="{stroke_width}"' if stroke else "",
    ]
    return "  " + " ".join(part for part in parts if part) + "/>"


def line(x1, y1, x2, y2, width=1.0, stroke=RULE, cap="butt") -> str:
    return (
        f'  <line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
        f'stroke="{stroke}" stroke-width="{width}" stroke-linecap="{cap}"/>'
    )


def text(x, y, content, size=12, weight=400, fill=TEXT, anchor="start", family=BODY_FONT) -> str:
    return (
        f'  <text x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}" font-family="{family}" '
        f'font-size="{size}" font-weight="{weight}" fill="{fill}">{escape(content)}</text>'
    )


# --------------------------------------------------------------------------
# axis and intervals
# --------------------------------------------------------------------------


def draw_axis(kind, ticks, lo, hi, axis_title) -> str:
    out = []
    bottom = PLOT_TOP + len(ROWS) * ROW_PITCH
    for tick in ticks:
        x = x_at(tick, kind, lo, hi)
        out.append(line(x, PLOT_TOP, x, bottom, width=1.0, stroke=GRID))
        out.append(text(x, TICK_LABEL_Y, f"{tick:,}", size=13, fill=MUTED, anchor="middle"))
    out.append(line(PLOT_LEFT, AXIS_Y, PLOT_RIGHT, AXIS_Y, width=1.0, stroke=RULE))
    out.append(
        text(
            (PLOT_LEFT + PLOT_RIGHT) / 2,
            AXIS_TITLE_Y,
            axis_title,
            size=13,
            fill=MUTED,
            anchor="middle",
        )
    )
    return "\n".join(out)


def draw_rows(kind, lo, hi) -> str:
    out = []
    for index, (label, cheap_mbps, dear_mbps) in enumerate(ROWS):
        middle = pill_center(index)
        # The expensive encode buys the fewest hours, so it is the left end.
        most_hours = hours_at(cheap_mbps)
        fewest_hours = hours_at(dear_mbps)
        left = x_at(fewest_hours, kind, lo, hi)
        right = x_at(most_hours, kind, lo, hi)

        out.append(
            rect(left, middle - BAR_H / 2, right - left, BAR_H, stroke=INK, stroke_width=1.5, rx=BAR_H / 2)
        )

        # Inside the pill when there is room for it, immediately right of the pill
        # when there is not. On the linear scale the top three pills are far too
        # short to seat a label, which is exactly the point that chart makes.
        needed = label_width(label, ROW_LABEL_SIZE) + 2 * LABEL_PAD
        if right - left >= needed:
            out.append(
                text(
                    (left + right) / 2,
                    middle + ROW_LABEL_SIZE * 0.35,
                    label,
                    size=ROW_LABEL_SIZE,
                    weight=700,
                    fill=INK,
                    anchor="middle",
                    family=TITLE_FONT,
                )
            )
        else:
            out.append(
                text(
                    right + LABEL_PAD,
                    middle + ROW_LABEL_SIZE * 0.35,
                    label,
                    size=ROW_LABEL_SIZE,
                    weight=700,
                    fill=INK,
                    anchor="start",
                    family=TITLE_FONT,
                )
            )

        # Hours sit under their own pill, centred on it, quiet enough that the
        # pills stay the first thing read.
        out.append(
            text(
                (left + right) / 2,
                middle + LABEL_DROP,
                f"{fewest_hours:,.0f}–{most_hours:,.0f} hours",
                size=HOURS_LABEL_SIZE,
                weight=400,
                fill=TEXT,
                anchor="middle",
            )
        )
    return "\n".join(out)


def font_faces() -> str:
    faces = []
    for family, filename, upstream in FONTS:
        encoded = base64.b64encode((OUT_DIR / upstream / filename).read_bytes()).decode("ascii")
        faces.append(
            f"    @font-face {{\n"
            f"      font-family: '{family}';\n"
            f"      src: url('data:font/woff2;base64,{encoded}') format('woff2');\n"
            f"      font-weight: 100 900;\n"
            f"      font-style: normal;\n"
            f"    }}"
        )
    return "\n".join(faces)


def make_svg(kind, ticks, lo, hi, axis_title) -> str:
    return f"""<svg width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="{WIDTH}" height="{HEIGHT}" fill="{PAGE}"/>
  <style>
{font_faces()}
  </style>
  <text x="{MARGIN}" y="58" font-family="{TITLE_FONT}"
        font-size="44" font-weight="700" fill="{INK}">{escape(TITLE)}</text>
  <text x="{MARGIN}" y="86" font-family="{BODY_FONT}"
        font-size="14" font-weight="400" fill="{MUTED}">{escape(SUBTITLE)}</text>
{draw_axis(kind, ticks, lo, hi, axis_title)}
{draw_rows(kind, lo, hi)}
  <text x="{MARGIN}" y="{CREDIT_Y}" font-family="{BODY_FONT}"
        font-size="12" font-weight="400" fill="{MUTED}">{escape(CREDIT)}</text>
</svg>
"""


def main() -> None:
    for kind, ticks, lo, hi, axis_title in SCALES:
        out_file = OUT_DIR / f"terabyte-video-hours-{kind}.svg"
        out_file.write_text(make_svg(kind, ticks, lo, hi, axis_title), encoding="utf-8")
        print(f"wrote {out_file.relative_to(OUT_DIR.parent)}")


if __name__ == "__main__":
    main()
