#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM (Claude) and has not been hand-verified.

Redraw Noah Iliinsky's "Properties and Best Uses of Visual Encodings" table as a
golden-ratio landscape SVG.

Same conventions as ../bertins-visual-variables and ../pasteurs-quadrant: a
1000 x 618 canvas, fonts self-hosted from ../fonts and embedded as base64 woff2
so the SVG stands alone.

The source table is CC BY-SA, so this redraw is a derivative and carries the
attribution in the figure itself -- see SOURCES.md before reusing it.

Departures from the reference raster (visualpropertiestable2.gif):
  - the four data-type columns use a filled dot instead of sixty repetitions of
    the word "Good"; a dot matrix is scannable down a column, the word is not
  - example marks are drawn in the repo accent orange rather than the source's
    blue, and everything else stays neutral, per ../STYLE.md
  - the "weight, boldness" example uses actual type weights, which is what the
    row is about, rather than reusing the line-weight example
  - the "shape, icon" example uses the star, square and teardrop from
    ../abstraction/0-shapes.svg, so the shape row and the abstraction figures
    speak the same vocabulary

Source: Noah Iliinsky, complexdiagrams.com/properties (2012-06), reproduced in
https://datavizblog.com/2017/06/13/revisiting-tableau-desktop-fundamentals/
"""

from __future__ import annotations

import base64
import colorsys
from math import cos, pi, radians, sin
from pathlib import Path
from xml.sax.saxutils import escape


PHI = (1 + 5**0.5) / 2
WIDTH = 1000
HEIGHT = round(WIDTH / PHI)  # 618

OUT_DIR = Path(__file__).resolve().parent
OUT_FILE = OUT_DIR / "iliinsky-visual-properties.svg"

PAGE = "#FFFFFF"
INK = "#111111"
TEXT = "#333333"
MUTED = "#777777"
RULE = "#DDDDDD"
BORDER = "#111111"
HEADER_FILL = "#EEEEEE"
MATRIX_FILL = "#F7F7F7"  # groups the four data-type columns as one matrix
ACCENT = "#F9461C"  # $orange -- carries every example mark

TITLE_FONT = "Big Shoulders"
BODY_FONT = "Libre Franklin"
FONTS = [
    (TITLE_FONT, "BigShoulders.woff2", "../fonts/big-shoulders"),
    (BODY_FONT, "LibreFranklin.woff2", "../fonts/libre-franklin"),
]

TITLE = "Properties and Best Uses of Visual Encodings"
CREDIT = (
    "Based on Noah Iliinsky's table, complexdiagrams.com/properties (2012), CC BY-SA"
)
LEGEND = "● = “Good” in the original"

MARGIN = 16
TABLE_X = MARGIN
TABLE_W = WIDTH - 2 * MARGIN  # 968
TABLE_TOP = 52
FOOTER_Y = 604
TABLE_BOTTOM = 578
HEADER_H = 26
BODY_TOP = TABLE_TOP + HEADER_H

# Example | Encoding | Ordered | Useful values | Quantitative Ordinal Categorical Relational
COLUMNS = [
    ("Example", 132),
    ("Encoding", 186),
    ("Ordered", 132),
    ("Useful values", 122),
    ("Quantitative", 99),
    ("Ordinal", 99),
    ("Categorical", 99),
    ("Relational", 99),
]
MATRIX_START = 4  # first data-type column

# (example key, encoding, ordered, ordered note, useful values, values emphasised,
#  data types that fit)
ROWS = [
    ("position", "position, placement", "yes", "", "infinite", True, "QOCR"),
    ("labels", "text labels", "optional", "(alphabetical or numbered)", "infinite", True, "QOCR"),
    ("length", "length", "yes", "", "many", True, "QO"),
    ("area", "size, area", "yes", "", "many", True, "QO"),
    ("angle", "angle", "yes", "", "medium/few", False, "QO"),
    ("density", "pattern density", "yes", "", "few", False, "QO"),
    ("boldness", "weight, boldness", "yes", "", "few", False, "O"),
    ("saturation", "saturation, brightness", "yes", "", "few", False, "O"),
    ("colour", "color", "no", "", "few (< 20)", False, "C"),
    ("shape", "shape, icon", "no", "", "medium", False, "C"),
    ("texture", "pattern texture", "no", "", "medium", False, "C"),
    ("enclosure", "enclosure, connection", "no", "", "infinite", True, "CR"),
    ("linepattern", "line pattern", "no", "", "few", False, "R"),
    ("lineendings", "line endings", "no", "", "few", False, "R"),
    ("lineweight", "line weight", "yes", "", "few", False, "O"),
]
ROW_H = (TABLE_BOTTOM - BODY_TOP) / len(ROWS)

DATA_TYPE_KEYS = "QOCR"


def column_x(index: int) -> float:
    return TABLE_X + sum(width for _, width in COLUMNS[:index])


# --------------------------------------------------------------------------
# small drawing helpers
# --------------------------------------------------------------------------


def rect(x, y, w, h, fill=ACCENT, stroke=None, stroke_width=1.0, rx=0) -> str:
    parts = [
        f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}"',
        f'rx="{rx}"' if rx else "",
        f'fill="{fill}"',
        f'stroke="{stroke}" stroke-width="{stroke_width}"' if stroke else "",
    ]
    return "  " + " ".join(part for part in parts if part) + "/>"


def circle(cx, cy, r, fill=ACCENT) -> str:
    return f'  <circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="{fill}"/>'


def line(x1, y1, x2, y2, width=2.0, dash="", cap="butt", stroke=ACCENT) -> str:
    dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'  <line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
        f'stroke="{stroke}" stroke-width="{width}" stroke-linecap="{cap}"{dash_attr}/>'
    )


def text(x, y, content, size=12, weight=400, fill=TEXT, anchor="start", family=BODY_FONT) -> str:
    return (
        f'  <text x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}" font-family="{family}" '
        f'font-size="{size}" font-weight="{weight}" fill="{fill}">{escape(content)}</text>'
    )


def thirds(x, width, item_width):
    """Left coordinates for three examples spread across the example cell."""
    gap = (width - 3 * item_width) / 2
    return [x + index * (item_width + gap) for index in range(3)]


# --------------------------------------------------------------------------
# example marks -- one per row, each varying only the property it names
# --------------------------------------------------------------------------


def example_position(x, y, w, h) -> list[str]:
    return [
        circle(x + 0.14 * w, y + 0.72 * h, 5),
        circle(x + 0.50 * w, y + 0.28 * h, 5),
        circle(x + 0.80 * w, y + 0.62 * h, 5),
    ]


def example_labels(x, y, w, h) -> list[str]:
    return [text(x + w / 2, y + h / 2 + 4, "1, 2, 3 · A, B, C", size=12, fill=ACCENT, anchor="middle")]


def example_length(x, y, w, h) -> list[str]:
    bar_h = 5
    lengths = [w * 0.30, w * 0.62, w * 0.95]
    tops = [y + h / 2 - 1.6 * bar_h - 4, y + h / 2 - bar_h / 2, y + h / 2 + 0.6 * bar_h + 4]
    return [rect(x, top, length, bar_h) for length, top in zip(lengths, tops)]


def example_area(x, y, w, h) -> list[str]:
    radii = [3, 6, 9.5]
    cy = y + h / 2
    return [
        circle(left + 9.5, cy, r)
        for left, r in zip(thirds(x, w, 19), radii)
    ]


def example_angle(x, y, w, h) -> list[str]:
    cy = y + h / 2
    length = 20
    return [
        line(
            left + 11 - length / 2 * cos(radians(angle)),
            cy + length / 2 * sin(radians(angle)),
            left + 11 + length / 2 * cos(radians(angle)),
            cy - length / 2 * sin(radians(angle)),
            width=2.4,
        )
        for left, angle in zip(thirds(x, w, 22), (0, 35, 70))
    ]


def example_density(x, y, w, h) -> list[str]:
    side = min(h - 2, 20)
    top = y + (h - side) / 2
    return [
        rect(left, top, side, side, fill=f"url(#density{index})")
        for index, left in enumerate(thirds(x, w, side))
    ]


def example_boldness(x, y, w, h) -> list[str]:
    """Type weight, which is what "weight, boldness" means -- not line weight."""
    cy = y + h / 2 + 6
    return [
        text(left + 9, cy, "Aa", size=16, weight=weight, fill=ACCENT, anchor="middle")
        for left, weight in zip(thirds(x, w, 18), (300, 500, 800))
    ]


def example_saturation(x, y, w, h) -> list[str]:
    """One hue -- the accent -- at three saturations."""
    side = min(h - 2, 20)
    top = y + (h - side) / 2
    out = []
    for left, saturation in zip(thirds(x, w, side), (0.28, 0.62, 1.0)):
        red, green, blue = colorsys.hls_to_rgb(0.0333, 0.55, saturation)
        fill = "#%02X%02X%02X" % (round(red * 255), round(green * 255), round(blue * 255))
        out.append(rect(left, top, side, side, fill=fill))
    return out


def example_colour(x, y, w, h) -> list[str]:
    side = min(h - 2, 20)
    top = y + (h - side) / 2
    fills = (ACCENT, "#00A1DE", "#009B3A")  # CTA route colors, per STYLE.md
    return [
        rect(left, top, side, side, fill=fill)
        for left, fill in zip(thirds(x, w, side), fills)
    ]


def example_shape(x, y, w, h) -> list[str]:
    """Star, square, teardrop -- the first three shapes from ../abstraction's
    0-shapes.svg, drawn as flat silhouettes so only the outline varies."""
    r = 9.5
    cy = y + h / 2
    lefts = thirds(x, w, 2 * r)

    star = []
    for index in range(16):
        radius = r if index % 2 == 0 else r * 0.29
        angle = -pi / 2 + index * pi / 8
        star.append((lefts[0] + r + radius * cos(angle), cy + radius * sin(angle)))
    star_points = " ".join(f"{px:.1f},{py:.1f}" for px, py in star)

    side = r * 1.6
    cx = lefts[2] + r
    drop_r = r * 0.755
    base = cy + r
    top = base - drop_r * 1.65  # centre of the teardrop's round top

    return [
        f'  <polygon points="{star_points}" fill="{ACCENT}"/>',
        rect(lefts[1] + r - side / 2, cy - side / 2, side, side, rx=2),
        f'  <path d="M {cx:.1f},{base:.1f} '
        f'C {cx - drop_r * 0.72:.1f},{top + drop_r * 0.85:.1f} '
        f'{cx - drop_r:.1f},{top + drop_r * 0.45:.1f} {cx - drop_r:.1f},{top:.1f} '
        f'A {drop_r:.1f},{drop_r:.1f} 0 1 1 {cx + drop_r:.1f},{top:.1f} '
        f'C {cx + drop_r:.1f},{top + drop_r * 0.45:.1f} '
        f'{cx + drop_r * 0.72:.1f},{top + drop_r * 0.85:.1f} {cx:.1f},{base:.1f} Z" '
        f'fill="{ACCENT}"/>',
    ]


def example_texture(x, y, w, h) -> list[str]:
    side = min(h - 2, 20)
    top = y + (h - side) / 2
    return [
        rect(left, top, side, side, fill=f"url(#texture{index})")
        for index, left in enumerate(thirds(x, w, side))
    ]


def example_enclosure(x, y, w, h) -> list[str]:
    cy = y + h / 2
    return [
        rect(x, cy - 11, w * 0.56, 22, fill="none", stroke=ACCENT, stroke_width=1.6, rx=11),
        circle(x + w * 0.16, cy, 4.5),
        circle(x + w * 0.40, cy, 4.5),
        circle(x + w * 0.90, cy, 4.5),
        line(x + w * 0.56, cy, x + w * 0.90 - 4.5, cy, width=1.6),
    ]


def example_linepattern(x, y, w, h) -> list[str]:
    cy = y + h / 2
    return [
        line(x, cy - 8, x + w, cy - 8, width=2),
        line(x, cy, x + w, cy, width=2, dash="8 5"),
        line(x, cy + 8, x + w, cy + 8, width=2, dash="1.5 4", cap="round"),
    ]


def example_lineendings(x, y, w, h) -> list[str]:
    cy = y + h / 2
    tip = x + w
    out = [
        line(x, cy - 9, tip - 7, cy - 9, width=1.8),
        line(x, cy, tip - 2, cy, width=1.8),
        line(x, cy + 9, tip - 7, cy + 9, width=1.8),
    ]
    out.append(
        f'  <polygon points="{tip:.1f},{cy - 9:.1f} {tip - 7:.1f},{cy - 12.5:.1f} '
        f'{tip - 7:.1f},{cy - 5.5:.1f}" fill="{ACCENT}"/>'
    )
    out.append(line(tip - 2, cy - 4.5, tip - 2, cy + 4.5, width=2.2))
    out.append(circle(tip - 3.5, cy + 9, 3.5))
    return out


def example_lineweight(x, y, w, h) -> list[str]:
    cy = y + h / 2
    return [
        line(x, cy - 8.5, x + w, cy - 8.5, width=1),
        line(x, cy, x + w, cy, width=2.6),
        line(x, cy + 8, x + w, cy + 8, width=4.5),
    ]


EXAMPLES = {
    "position": example_position,
    "labels": example_labels,
    "length": example_length,
    "area": example_area,
    "angle": example_angle,
    "density": example_density,
    "boldness": example_boldness,
    "saturation": example_saturation,
    "colour": example_colour,
    "shape": example_shape,
    "texture": example_texture,
    "enclosure": example_enclosure,
    "linepattern": example_linepattern,
    "lineendings": example_lineendings,
    "lineweight": example_lineweight,
}

DENSITIES = ((7, 1.2), (4.5, 1.6), (2.6, 1.6))


# --------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------


def defs() -> str:
    out = []
    for index, (step, weight) in enumerate(DENSITIES):
        out.append(
            f'    <pattern id="density{index}" width="{step}" height="{step}" '
            f'patternUnits="userSpaceOnUse">\n'
            f'      <rect width="{step}" height="{step}" fill="{PAGE}"/>\n'
            f'      <rect width="{weight}" height="{step}" fill="{ACCENT}"/>\n'
            f"    </pattern>"
        )
    # Three different grains of the same idea: stripes, checker, dots.
    out.append(
        f'    <pattern id="texture0" width="6" height="6" patternUnits="userSpaceOnUse" '
        f'patternTransform="rotate(45)">\n'
        f'      <rect width="6" height="6" fill="{PAGE}"/>\n'
        f'      <rect width="6" height="3" fill="{ACCENT}"/>\n'
        f"    </pattern>"
    )
    out.append(
        f'    <pattern id="texture1" width="8" height="8" patternUnits="userSpaceOnUse">\n'
        f'      <rect width="8" height="8" fill="{PAGE}"/>\n'
        f'      <rect width="4" height="4" fill="{ACCENT}"/>\n'
        f'      <rect x="4" y="4" width="4" height="4" fill="{ACCENT}"/>\n'
        f"    </pattern>"
    )
    out.append(
        f'    <pattern id="texture2" width="5" height="5" patternUnits="userSpaceOnUse">\n'
        f'      <rect width="5" height="5" fill="{PAGE}"/>\n'
        f'      <circle cx="2.5" cy="2.5" r="1.4" fill="{ACCENT}"/>\n'
        f"    </pattern>"
    )
    return "\n".join(out)


def draw_header() -> str:
    out = [rect(TABLE_X, TABLE_TOP, TABLE_W, HEADER_H, fill=HEADER_FILL)]
    baseline = TABLE_TOP + HEADER_H - 9
    for index, (label, width) in enumerate(COLUMNS):
        x = column_x(index)
        if index >= MATRIX_START:
            out.append(text(x + width / 2, baseline, label, size=12, weight=700, fill=INK, anchor="middle"))
        else:
            out.append(text(x + 10, baseline, label, size=12, weight=700, fill=INK))
    return "\n".join(out)


def draw_rows() -> str:
    out = []
    matrix_x = column_x(MATRIX_START)
    matrix_w = TABLE_W - (matrix_x - TABLE_X)
    out.append(rect(matrix_x, BODY_TOP, matrix_w, TABLE_BOTTOM - BODY_TOP, fill=MATRIX_FILL))

    for index, (key, encoding, ordered, note, values, emphasised, fits) in enumerate(ROWS):
        top = BODY_TOP + index * ROW_H
        middle = top + ROW_H / 2
        baseline = middle + 4

        # Example cell.
        cell_x = column_x(0) + 12
        cell_w = COLUMNS[0][1] - 24
        out.extend(EXAMPLES[key](cell_x, top + 3, cell_w, ROW_H - 6))

        out.append(text(column_x(1) + 10, baseline, encoding, size=12.5, fill=INK))

        if note:
            out.append(text(column_x(2) + 10, middle - 1, ordered, size=12.5, weight=700, fill=INK))
            out.append(text(column_x(2) + 10, middle + 11, note, size=9.5, fill=MUTED))
        else:
            weight = 700 if ordered == "yes" else 400
            fill = INK if ordered == "yes" else MUTED
            out.append(text(column_x(2) + 10, baseline, ordered, size=12.5, weight=weight, fill=fill))

        out.append(
            text(
                column_x(3) + 10, baseline, values, size=12.5,
                weight=700 if emphasised else 400,
                fill=INK if emphasised else TEXT,
            )
        )

        for offset, key_letter in enumerate(DATA_TYPE_KEYS):
            if key_letter in fits:
                column = MATRIX_START + offset
                out.append(circle(column_x(column) + COLUMNS[column][1] / 2, middle, 4.5))
    return "\n".join(out)


def draw_frame() -> str:
    out = [
        f'  <rect x="{TABLE_X}" y="{TABLE_TOP}" width="{TABLE_W}" '
        f'height="{TABLE_BOTTOM - TABLE_TOP}" fill="none" stroke="{BORDER}" stroke-width="1.5"/>',
        f'  <line x1="{TABLE_X}" y1="{BODY_TOP}" x2="{TABLE_X + TABLE_W}" y2="{BODY_TOP}" '
        f'stroke="{BORDER}" stroke-width="1.5"/>',
    ]
    for index in range(1, len(ROWS)):
        y = BODY_TOP + index * ROW_H
        out.append(
            f'  <line x1="{TABLE_X}" y1="{y:.1f}" x2="{TABLE_X + TABLE_W}" y2="{y:.1f}" '
            f'stroke="{RULE}" stroke-width="1"/>'
        )
    for index in range(1, len(COLUMNS)):
        x = column_x(index)
        # The matrix boundary is the one structural division; the rest are hairlines.
        stroke, width = (BORDER, 1.2) if index == MATRIX_START else (RULE, 1)
        out.append(
            f'  <line x1="{x:.1f}" y1="{TABLE_TOP}" x2="{x:.1f}" y2="{TABLE_BOTTOM}" '
            f'stroke="{stroke}" stroke-width="{width}"/>'
        )
    return "\n".join(out)


def draw_footer() -> str:
    return "\n".join(
        [
            text(TABLE_X, FOOTER_Y, LEGEND, size=10.5, fill=MUTED),
            text(TABLE_X + TABLE_W, FOOTER_Y, CREDIT, size=10.5, fill=MUTED, anchor="end"),
        ]
    )


def font_faces() -> str:
    faces = []
    for family, filename, upstream in FONTS:
        encoded = base64.b64encode((OUT_DIR / upstream / filename).read_bytes()).decode("ascii")
        faces.append(
            f"    @font-face {{\n"
            f"      font-family: '{family}';\n"
            f"      src: url('data:font/woff2;base64,{encoded}') format('woff2');\n"
            f"      font-weight: 100 900;\n"
            f"      font-style: normal;\n"
            f"    }}"
        )
    return "\n".join(faces)


def make_svg() -> str:
    return f"""<svg width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="{WIDTH}" height="{HEIGHT}" fill="{PAGE}"/>
  <style>
{font_faces()}
  </style>
  <defs>
{defs()}
  </defs>
  <text x="{WIDTH / 2}" y="38" text-anchor="middle" font-family="{TITLE_FONT}"
        font-size="38" font-weight="700" fill="{INK}">{escape(TITLE)}</text>
{draw_header()}
{draw_rows()}
{draw_frame()}
{draw_footer()}
</svg>
"""


def main() -> None:
    OUT_FILE.write_text(make_svg(), encoding="utf-8")
    print(f"wrote {OUT_FILE.relative_to(OUT_DIR.parent)}")


if __name__ == "__main__":
    main()
