#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM (Claude) and has not been hand-verified.

Generate the "labels appear as you go" variant of the data science lifecycle.

Same geometry as ../lifecycle/make_lifecycle_figures.py (imported, not copied),
but the labels are withheld until a node is highlighted:

  step0 — every box blank, no highlight (the empty scaffold)
  step1 — box 1 highlighted, its label appears
  step2 — box 2 highlighted; box 1 keeps its label, now un-highlighted
  ...    labels accumulate left to right, so nothing already said disappears
"""

from __future__ import annotations

import sys
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent
BASE_DIR = OUT_DIR.parent / "lifecycle"
sys.path.insert(0, str(BASE_DIR))

import make_lifecycle_figures as base  # noqa: E402


_DRAW_NODE = base.draw_node
_revealed: set[str] = set()


def draw_node_progressive(node_id: str, label: str, highlighted: bool) -> str:
    """Blank out the label unless this node has been reached yet."""
    return _DRAW_NODE(node_id, label if node_id in _revealed else "", highlighted)


def main() -> None:
    base.draw_node = draw_node_progressive
    try:
        for step in range(len(base.NODES) + 1):
            highlight_index = None if step == 0 else step - 1
            _revealed.clear()
            _revealed.update(node_id for node_id, _ in base.NODES[:step])
            path = OUT_DIR / f"ds-lifecycle-step{step}.svg"
            path.write_text(base.make_svg(highlight_index), encoding="utf-8")
            print(path.name)
    finally:
        base.draw_node = _DRAW_NODE


if __name__ == "__main__":
    main()
