#!/usr/bin/env bash
# NOTICE: This file was generated by an LLM coding system.
#
# Build the Python Yard (JupyterLite) from docs/yard/ sources.
#
#   bash docs/yard/build.sh              # build into docs/yard/_output (gitignored)
#   bash docs/yard/build.sh _site/yard   # build into another folder (CI)
#   SERVE=1 bash docs/yard/build.sh      # build, then serve at http://localhost:8000/
#
# No datasets are bundled: notebooks read them from the repo's datasets/ folder
# on GitHub by raw URL.
set -euo pipefail

YARD="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$YARD/../.." && pwd)"
OUT="${1:-$YARD/_output}"
mkdir -p "$OUT" && OUT="$(cd "$OUT" && pwd)"  # absolute: the build runs from a temp dir

# Local runs use a venv here; CI installs requirements.txt itself and sets SKIP_VENV.
if [[ -z "${SKIP_VENV:-}" ]]; then
  if [[ ! -x "$YARD/.venv/bin/jupyter" ]]; then
    uv venv -q "$YARD/.venv" --python 3.12
    uv pip install -q --python "$YARD/.venv/bin/python" -r "$YARD/requirements.txt"
  fi
  export PATH="$YARD/.venv/bin:$PATH"
fi

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
cp -R "$YARD/content/." "$STAGE/"
# The executed lecture notebooks, so File → Open… lists them next to welcome.ipynb.
cp "$REPO"/docs/slides/week*.ipynb "$STAGE/"

# --lite-dir picks up jupyter-lite.json; build from inside the stage so the
# .jupyterlite.doit.db cache lands in the temp dir, not the repo.
(cd "$STAGE" && jupyter lite build --lite-dir "$YARD" --contents "$STAGE" --output-dir "$OUT")

if [[ -n "${SERVE:-}" ]]; then
  echo "Starter notebook: http://localhost:8000/notebooks/index.html?path=welcome.ipynb"
  python3 -m http.server 8000 --directory "$OUT"
fi
