#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM (Claude) and has not been hand-verified.

Generate Pasteur's quadrant as a build-up sequence of golden-ratio SVGs.

Same conventions as ../lifecycle-steps: one element appears per step, nothing
already shown disappears, and the newest element is the highlighted one.

  step0 — empty 2x2 grid, no labels (the scaffold)
  step1 — x axis: "Considerations of use?"  (No | Yes)
  step2 — y axis: "Quest for fundamental understanding?"  (Yes | No)
  step3 — Bohr    (pure basic research)
  step4 — Edison  (pure applied research)
  step5 — Pasteur (use-inspired basic research)

Source for the framing: Stokes, *Pasteur's Quadrant: Basic Science and
Technological Innovation* (Brookings, 1997); see
https://en.wikipedia.org/wiki/Pasteur%27s_quadrant
"""

from __future__ import annotations

import base64
import shutil
from pathlib import Path
from xml.sax.saxutils import escape


PHI = (1 + 5**0.5) / 2
WIDTH = 1000
HEIGHT = round(WIDTH / PHI)  # 618

OUT_DIR = Path(__file__).resolve().parent

NEUTRAL = "#EEEEEE"
HIGHLIGHT = "#222222"
STROKE = "#111111"
TEXT = "#111111"
TEXT_ON_DARK = "#FFFFFF"
MUTED = "#777777"
STROKE_WIDTH = 3

FONT_FAMILY = "Libre Franklin"
FONT_FILE = "LibreFranklin.woff2"
FONT_SOURCE = OUT_DIR / "../fonts/libre-franklin" / FONT_FILE
if not FONT_SOURCE.exists():
    FONT_SOURCE = OUT_DIR / FONT_FILE

# Grid geometry: the 2x2 block is itself a golden-ratio rectangle.
GRID_WIDTH = 660
GRID_HEIGHT = round(GRID_WIDTH / PHI)  # 408
GRID_X = 300
GRID_Y = 60
CELL_WIDTH = GRID_WIDTH / 2
CELL_HEIGHT = GRID_HEIGHT / 2

# Both axis titles are set horizontally: x below the grid, y in the left margin.
X_AXIS_TITLE = "Considerations of use?"
X_AXIS_TICKS = ("No", "Yes")  # left column, right column
Y_AXIS_TITLE = "Quest for\nfundamental\nunderstanding?"
Y_AXIS_TICKS = ("Yes", "No")  # top row, bottom row

# (id, column, row, name, subtitle)
QUADRANTS = [
    ("bohr", 0, 0, "Bohr", "Pure basic\nresearch"),
    ("edison", 1, 1, "Edison", "Pure applied\nresearch"),
    ("pasteur", 1, 0, "Pasteur", "Use-inspired\nbasic research"),
]

# Order in which elements are revealed, one per step.
STEPS = ["x_axis", "y_axis", "bohr", "edison", "pasteur"]


def cell_center(column: int, row: int) -> tuple[float, float]:
    return (
        GRID_X + (column + 0.5) * CELL_WIDTH,
        GRID_Y + (row + 0.5) * CELL_HEIGHT,
    )


def draw_grid() -> str:
    mid_x = GRID_X + CELL_WIDTH
    mid_y = GRID_Y + CELL_HEIGHT
    return f"""  <rect x="{GRID_X}" y="{GRID_Y}" width="{GRID_WIDTH}" height="{GRID_HEIGHT}"
        rx="6" fill="none" stroke="{STROKE}" stroke-width="{STROKE_WIDTH}"/>
  <line x1="{mid_x}" y1="{GRID_Y}" x2="{mid_x}" y2="{GRID_Y + GRID_HEIGHT}"
        stroke="{STROKE}" stroke-width="{STROKE_WIDTH}"/>
  <line x1="{GRID_X}" y1="{mid_y}" x2="{GRID_X + GRID_WIDTH}" y2="{mid_y}"
        stroke="{STROKE}" stroke-width="{STROKE_WIDTH}"/>"""


def draw_cell(quadrant_id: str, column: int, row: int, name: str, subtitle: str, highlighted: bool) -> str:
    """A filled quadrant cell, inset so the grid rules stay visible."""
    x = GRID_X + column * CELL_WIDTH + STROKE_WIDTH / 2
    y = GRID_Y + row * CELL_HEIGHT + STROKE_WIDTH / 2
    width = CELL_WIDTH - STROKE_WIDTH
    height = CELL_HEIGHT - STROKE_WIDTH
    fill = HIGHLIGHT if highlighted else NEUTRAL
    name_color = TEXT_ON_DARK if highlighted else TEXT
    sub_color = TEXT_ON_DARK if highlighted else MUTED

    cx, cy = cell_center(column, row)
    sub_lines = subtitle.split("\n")
    line_height = 24
    block_height = 34 + len(sub_lines) * line_height
    name_y = cy - block_height / 2 + 26
    sub_tspans = "\n    ".join(
        f'<tspan x="{cx:.1f}" y="{name_y + 34 + index * line_height:.1f}">{escape(line)}</tspan>'
        for index, line in enumerate(sub_lines)
    )

    return f"""  <rect x="{x:.1f}" y="{y:.1f}" width="{width:.1f}" height="{height:.1f}"
        rx="4" fill="{fill}"/>
  <text x="{cx:.1f}" y="{name_y:.1f}" text-anchor="middle" font-family="{FONT_FAMILY}"
        font-size="34" font-weight="700" fill="{name_color}">{escape(name)}</text>
  <text text-anchor="middle" font-family="{FONT_FAMILY}" font-size="20"
        font-weight="400" fill="{sub_color}">
    {sub_tspans}
  </text>"""


def draw_x_axis() -> str:
    """Title and column headers, both horizontal, below the grid."""
    tick_y = GRID_Y + GRID_HEIGHT + 40
    title_y = GRID_Y + GRID_HEIGHT + 86
    ticks = "\n".join(
        f'  <text x="{cell_center(column, 0)[0]:.1f}" y="{tick_y}" text-anchor="middle" '
        f'font-family="{FONT_FAMILY}" font-size="24" font-weight="400" '
        f'fill="{TEXT}">{escape(label)}</text>'
        for column, label in enumerate(X_AXIS_TICKS)
    )
    title = (
        f'  <text x="{GRID_X + GRID_WIDTH / 2:.1f}" y="{title_y}" text-anchor="middle" '
        f'font-family="{FONT_FAMILY}" font-size="24" font-weight="700" '
        f'fill="{TEXT}">{escape(X_AXIS_TITLE)}</text>'
    )
    return f"{ticks}\n{title}"


def draw_y_axis() -> str:
    """Title and row headers, both horizontal, in the left margin."""
    tick_x = GRID_X - 20
    title_x = 30
    line_height = 28
    title_lines = Y_AXIS_TITLE.split("\n")
    first_y = GRID_Y + GRID_HEIGHT / 2 - ((len(title_lines) - 1) * line_height) / 2 + 8
    ticks = "\n".join(
        f'  <text x="{tick_x}" y="{cell_center(0, row)[1] + 8:.1f}" text-anchor="end" '
        f'font-family="{FONT_FAMILY}" font-size="24" font-weight="400" '
        f'fill="{TEXT}">{escape(label)}</text>'
        for row, label in enumerate(Y_AXIS_TICKS)
    )
    title_tspans = "\n    ".join(
        f'<tspan x="{title_x}" y="{first_y + index * line_height:.1f}">{escape(line)}</tspan>'
        for index, line in enumerate(title_lines)
    )
    title = (
        f'  <text text-anchor="start" font-family="{FONT_FAMILY}" font-size="24" '
        f'font-weight="700" fill="{TEXT}">\n    {title_tspans}\n  </text>'
    )
    return f"{ticks}\n{title}"


def font_data_url() -> str:
    encoded = base64.b64encode(FONT_SOURCE.read_bytes()).decode("ascii")
    return f"data:font/woff2;base64,{encoded}"


def make_svg(step: int, highlight: bool = True) -> str:
    revealed = set(STEPS[:step])
    newest = STEPS[step - 1] if (step > 0 and highlight) else None

    parts = []
    if "x_axis" in revealed:
        parts.append(draw_x_axis())
    if "y_axis" in revealed:
        parts.append(draw_y_axis())
    # Cells go under the grid rules so the rules read as one continuous cross.
    cells = [
        draw_cell(quadrant_id, column, row, name, subtitle, newest == quadrant_id)
        for quadrant_id, column, row, name, subtitle in QUADRANTS
        if quadrant_id in revealed
    ]

    body = "\n".join(cells + [draw_grid()] + parts)

    return f"""<svg width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="{WIDTH}" height="{HEIGHT}" fill="white"/>
  <style>
    @font-face {{
      font-family: '{FONT_FAMILY}';
      src: url('{font_data_url()}') format('woff2');
      font-weight: 100 900;
      font-style: normal;
    }}
  </style>
{body}
</svg>
"""


def main() -> None:
    font_destination = OUT_DIR / FONT_FILE
    if FONT_SOURCE.resolve() != font_destination.resolve():
        shutil.copy2(FONT_SOURCE, font_destination)
    for step in range(len(STEPS) + 1):
        path = OUT_DIR / f"pasteurs-quadrant-step{step}.svg"
        path.write_text(make_svg(step), encoding="utf-8")
        print(path.name)

    # The finished quadrant with nothing singled out, for slides that talk
    # about one cell without the figure doing the pointing.
    complete = OUT_DIR / "pasteurs-quadrant-complete.svg"
    complete.write_text(make_svg(len(STEPS), highlight=False), encoding="utf-8")
    print(complete.name)


if __name__ == "__main__":
    main()
