#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM coding agent (Claude). Review before promoting out of sandbox/.

Build a seamlessly looping GIF from orange-line-trace-with-stops.svg in which the white
chevrons crawl along the Orange Line, sliding behind the station dots as they go.

The route
---------
Chevrons run the inbound trip, downtown to Midway. They are born under the Harold
Washington Library marker at (537,492) -- the first stop of the run -- head clockwise
around the Loop, come off it at the top right, and then run the whole stem down to
Midway, where they fade out.

That direction is not a guess: the two chevrons already in the source SVG point left
along the Loop's lower leg and right along its top, which is exactly this traversal.

The loop
--------
N chevrons sit at equal arc-length spacing L/N and every one advances by exactly L/N
over the animation, so chevron 1 lands where chevron 2 began, chevron 2 where 3 began,
and the position set in the last frame is the set in the first. The one chevron that
runs off the Midway end wraps back to the library in the same step.

Opacity is a pure function of arc length -- zero at both ends of the route, ramping up
over --fade units -- so the wrap happens where nothing is drawn and the loop is exact.
Equal spacing and constant speed are both load-bearing: either alone is not enough.

Chevrons are drawn in their own group between the line and the Stops group, so the
station dots and transfer markers occlude them as they pass.

Usage
-----
    python make_chevron_gif_og.py
    python make_chevron_gif_og.py --chevrons 6 --duration 3 --out chevrons.gif
"""

import argparse
import math
import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
DEFAULT_SVG = HERE.parent / "orange-line-trace-with-stops.svg"

# The chevron the source SVG uses, as an outline pointing along +x with its apex at the
# origin, so it can be dropped onto a path point and rotated to the local tangent.
CHEVRON = [(-20.0, -22.0), (0.0, 0.0), (-20.0, 22.0)]
CHEVRON_STROKE = 9.0

# Harold Washington Library, in map units: the first stop of the inbound run and so the
# point every chevron is born at. It is also where path1's opening curve lands, which is
# why the chevrons can start there without cutting the Loop short.
LIBRARY = (537.0, 492.0)


# ---------------------------------------------------------------- path geometry

def parse_path(d):
    """Flatten an absolute M/L/C path string into a list of points."""
    tokens = re.findall(r"[MLCmlc]|-?\d*\.?\d+(?:e-?\d+)?", d)
    if any(t in "mlc" for t in tokens):
        raise ValueError("relative path commands are not supported")
    pts = []
    i = 0
    cmd = None
    while i < len(tokens):
        if tokens[i] in "MLC":
            cmd = tokens[i]
            i += 1
            continue
        nums = []
        need = 6 if cmd == "C" else 2
        for _ in range(need):
            nums.append(float(tokens[i]))
            i += 1
        if cmd == "C":
            p0 = pts[-1]
            c1, c2, p1 = (nums[0], nums[1]), (nums[2], nums[3]), (nums[4], nums[5])
            for k in range(1, 33):
                t = k / 32
                u = 1 - t
                pts.append((
                    u**3 * p0[0] + 3 * u * u * t * c1[0] + 3 * u * t * t * c2[0] + t**3 * p1[0],
                    u**3 * p0[1] + 3 * u * u * t * c1[1] + 3 * u * t * t * c2[1] + t**3 * p1[1],
                ))
        else:
            pts.append((nums[0], nums[1]))
    return pts


class Polyline:
    """A flattened path with arc-length lookup."""

    def __init__(self, pts):
        self.pts = pts
        self.cum = [0.0]
        for a, b in zip(pts, pts[1:]):
            self.cum.append(self.cum[-1] + math.hypot(b[0] - a[0], b[1] - a[1]))
        self.length = self.cum[-1]

    def at(self, s):
        """(x, y, heading in degrees) at arc length s."""
        s = min(max(s, 0.0), self.length)
        lo, hi = 0, len(self.cum) - 1
        while lo < hi - 1:
            mid = (lo + hi) // 2
            if self.cum[mid] <= s:
                lo = mid
            else:
                hi = mid
        a, b = self.pts[lo], self.pts[lo + 1]
        seg = self.cum[lo + 1] - self.cum[lo]
        t = 0.0 if seg == 0 else (s - self.cum[lo]) / seg
        return (a[0] + t * (b[0] - a[0]),
                a[1] + t * (b[1] - a[1]),
                math.degrees(math.atan2(b[1] - a[1], b[0] - a[0])))

    def nearest(self, x, y):
        """Arc length of the point on the path closest to (x, y)."""
        best = (float("inf"), 0.0)
        for i, (a, b) in enumerate(zip(self.pts, self.pts[1:])):
            dx, dy = b[0] - a[0], b[1] - a[1]
            seg = dx * dx + dy * dy
            t = 0.0 if seg == 0 else max(0.0, min(1.0, ((x - a[0]) * dx + (y - a[1]) * dy) / seg))
            px, py = a[0] + t * dx, a[1] + t * dy
            best = min(best, ((px - x) ** 2 + (py - y) ** 2,
                              self.cum[i] + t * math.sqrt(seg)))
        return best[1]


def build_route(stem_pts, loop_pts):
    """The library, clockwise around the Loop, then down the whole stem to Midway.

    The stem is drawn outbound (Midway first), so it is reversed to run inbound. The short
    stub between the wye and the library is the only piece of line left without chevrons;
    that stub carries the other direction of travel.
    """
    loop = Polyline(loop_pts)
    start = loop.nearest(*LIBRARY)
    onward = [loop.at(start)[:2]] + [p for p, c in zip(loop.pts, loop.cum) if c > start]
    return Polyline(onward + stem_pts[::-1])


# ---------------------------------------------------------------- frame assembly

def read_svg(path):
    """Return (body, width, height) for the source SVG."""
    text = path.read_text()
    m = re.search(r"<svg\b([^>]*)>(.*)</svg>", text, re.DOTALL)
    if not m:
        raise ValueError(f"could not parse {path}")
    attrs, body = m.group(1), m.group(2)
    vb = re.search(r'viewBox\s*=\s*"([^"]+)"', attrs)
    _, _, w, h = (float(v) for v in vb.group(1).replace(",", " ").split())
    return body, w, h


def strip_static_chevrons(body):
    """Drop the two hand-placed chevrons; the animation supplies its own."""
    return re.sub(r'\s*<path id="path[23]"[^>]*/>', "", body)


def read_route(body):
    d = dict(re.findall(r'<path id="([^"]+)"[^>]*\sd="([^"]+)"', body))
    return build_route(parse_path(d["Path"]), parse_path(d["path1"]))


def source_apexes(body):
    """Apex (the middle vertex) of each chevron drawn in the source SVG."""
    return [parse_path(d)[1] for _, d in
            re.findall(r'<path id="(path[23])"[^>]*\sd="([^"]+)"', body)]


def phase_for(route, n, apexes):
    """Offset of the evenly spaced chevron grid that best keeps the hand-placed ones put.

    Spacing is fixed at L/n by the loop, so the only freedom left is where the grid sits.
    The apexes are positions modulo the spacing, i.e. angles on a circle, so the average
    that minimizes the shift is the circular mean rather than the arithmetic one.
    """
    if not apexes:
        return 0.0
    gap = route.length / n
    angles = [2 * math.pi * (route.nearest(*p) % gap) / gap for p in apexes]
    mean = math.atan2(sum(math.sin(a) for a in angles) / len(angles),
                      sum(math.cos(a) for a in angles) / len(angles))
    return (mean / (2 * math.pi)) % 1.0 * gap


def smoothstep(x):
    x = min(max(x, 0.0), 1.0)
    return x * x * (3 - 2 * x)


def chevrons_svg(route, n, phase, t, fade):
    """The chevron group at normalized time t in [0, 1)."""
    L = route.length
    d = "M {:.0f} {:.0f} L {:.0f} {:.0f} L {:.0f} {:.0f}".format(*[v for p in CHEVRON for v in p])
    out = []
    for k in range(n):
        s = ((k + t) * L / n + phase) % L
        x, y, heading = route.at(s)
        opacity = smoothstep(s / fade) * smoothstep((L - s) / fade)
        if opacity <= 0.001:
            continue
        out.append(
            f'<path d="{d}" transform="translate({x:.3f},{y:.3f}) rotate({heading:.3f})"'
            f' opacity="{opacity:.3f}"/>'
        )
    return (f'<g id="Chevrons" fill="none" stroke="#ffffff" stroke-width="{CHEVRON_STROKE:g}">'
            + "".join(out) + "</g>")


def frame_svg(body, route, cfg, t):
    """A full frame, with the chevron group slipped in behind the Stops group."""
    layers = body.replace('<g id="Stops">',
                          chevrons_svg(route, cfg["chevrons"], cfg["phase"], t, cfg["fade"]) + '<g id="Stops">')
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{cfg["W"]}" height="{cfg["H"]}" '
            f'viewBox="0 0 {cfg["vw"]:g} {cfg["vh"]:g}">'
            f'<rect x="0" y="0" width="{cfg["vw"]:g}" height="{cfg["vh"]:g}" fill="{cfg["bg"]}"/>'
            f"{layers}</svg>")


def render(svg_markup, W, H, ss, tmpdir):
    """Rasterize with rsvg-convert, supersampled and boxed back down."""
    src = Path(tmpdir) / "frame.svg"
    dst = Path(tmpdir) / "frame.png"
    src.write_text(svg_markup)
    subprocess.run(["rsvg-convert", "-w", str(W * ss), "-h", str(H * ss),
                    "-b", "white", str(src), "-o", str(dst)], check=True)
    img = Image.open(dst).convert("RGB")
    return img.resize((W, H), Image.LANCZOS) if ss != 1 else img


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--svg", type=Path, default=DEFAULT_SVG)
    ap.add_argument("--out", type=Path, default=HERE / "orange-line-chevrons-og.gif")
    ap.add_argument("--chevrons", type=int, default=4,
                    help="how many ride the route at once; they are always evenly spaced, "
                         "so this also sets how far each one travels per loop")
    ap.add_argument("--width", type=int, default=500)
    ap.add_argument("--height", type=int, default=800)
    ap.add_argument("--duration", type=float, default=4.0, help="seconds for one full loop")
    ap.add_argument("--fps", type=float, default=20.0)
    ap.add_argument("--fade", type=float, default=70.0,
                    help="map units over which a chevron fades in at the library and out at "
                         "Midway; the ramp is what hides the wrap")
    ap.add_argument("--supersample", type=int, default=2)
    ap.add_argument("--bg", default="#ffffff")
    ap.add_argument("--poster", action="store_true", help="also write a PNG of frame 0")
    args = ap.parse_args()

    body, vw, vh = read_svg(args.svg)
    route = read_route(body)
    phase = phase_for(route, args.chevrons, source_apexes(body))
    body = strip_static_chevrons(body)

    cfg = {"W": args.width, "H": args.height, "vw": vw, "vh": vh, "bg": args.bg,
           "chevrons": args.chevrons, "phase": phase, "fade": args.fade}

    n_frames = max(2, round(args.duration * args.fps))
    print(f"route {route.length:.1f} map units, {args.chevrons} chevrons "
          f"{route.length / args.chevrons:.1f} apart, phase {phase:.1f}")
    print(f"{n_frames} frames at {args.width}x{args.height}")

    frames = []
    with tempfile.TemporaryDirectory() as tmp:
        for i in range(n_frames):
            frames.append(render(frame_svg(body, route, cfg, i / n_frames),
                                 args.width, args.height, args.supersample, tmp))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    # One shared palette, so no frame drifts to a different quantization of the same orange.
    palette = frames[0].quantize(colors=64, method=Image.MEDIANCUT)
    quantized = [f.quantize(palette=palette, dither=Image.NONE) for f in frames]
    quantized[0].save(args.out, save_all=True, append_images=quantized[1:],
                      duration=round(1000 / args.fps), loop=0, optimize=True, disposal=2)
    print(f"wrote {args.out} ({args.out.stat().st_size / 1e6:.2f} MB)")

    if args.poster:
        poster = args.out.with_suffix(".png")
        frames[0].save(poster)
        print(f"wrote {poster}")


if __name__ == "__main__":
    main()
