#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM coding agent (Claude). Review before promoting out of sandbox/.

Build an infinite-zoom ("Droste") GIF from orange-line-trace-with-stops.svg for use as
an og:image / social preview, in the spirit of https://pudding.cool/2017/03/punk/

The illusion: one of the Loop stops on the map contains, inside its dot, a complete copy
of the Orange Line map. Zooming into that stop lands you back exactly where you started,
so the GIF loops seamlessly.

How it works
------------
Every frame is composed as vector SVG (so it stays sharp at any zoom) and rasterized with
cairosvg. The nesting transform T maps the whole canvas into the target stop's dot:

    T(p) = C + s * (p - canvas_center)

T is a pure scale-and-translate, so it has a fixed point P = (C - s*center)/(1 - s).
Both the nesting and the camera zoom are therefore scalings about the same point P,
which is what makes the loop exact: after zooming by 1/s over the full duration, the
frame is pixel-identical to frame 0, one level deeper into the fractal.

Two window shapes, set by --window:

  rect   (default) the nested copy is the whole frame, shrunk until it is inscribed in
         the dot: s = 2R/diag. Its own background matches the dot, so it reads as a map
         floating inside the stop, and at the wrap it expands to exactly fill the frame
         -- the loop is pixel-exact.
  circle the nested copy is clipped to the dot itself (s = 2R/H), which shows more map
         per level, but a circle cannot fill a rectangular frame, so the wrap point
         mismatches in the corners. Fine for stills, visibly jumpy as a loop.

Three variants come out of one pass (--variants to pick a subset):

  -zoom-in    falling into the stop
  -zoom-out   the same frames reversed, climbing back out
  -bounce     one eased round trip, in and back out, forever

Usage
-----
    python make_fractal_og.py                 # writes all three
    python make_fractal_og.py --variants bounce --stop 607,414 --duration 12
"""

import argparse
import io
import math
import re
from pathlib import Path

import cairosvg
from PIL import Image

HERE = Path(__file__).resolve().parent
DEFAULT_SVG = HERE.parents[1] / "orange-line-map-stops" / "stop01-harold-washington-library.svg"

# Stops on the Loop, by center in map units (the big "transfer" markers, outer ring r=22).
# harold-washington-library is the one stop01-*.svg already rings in red and points a
# "you are here" arrow at, so it is the natural mouth of the fractal. Note these are the
# centers of the marker circles: stop01's red pulse rings sit at x=538, one unit off, and
# nesting into that instead visibly shoves the nested map off-center at high zoom.
LOOP_STOPS = {
    "harold-washington-library": (537, 492),
    "adams-wabash": (401, 183),
    "state-lake": (538, 183),
    "clark-lake": (345, 286),
    "washington-wells": (607, 414),
}


def strip_pointers(body: str) -> str:
    """Drop the source card's "you are here" pointers, keeping only the pulse rings.

    The arrow and the solid red center both point at a stop the viewer is standing at;
    here the stop is a doorway, not a destination, and the nested map inside it does the
    pointing. Emptying the center back to white also hides the seam of the nested frame,
    since it lands on white-on-white.
    """
    body = re.sub(r"\s*<polygon\b[^>]*id=\"you-are-here-arrow\"[^>]*/>", "", body)
    return body.replace('fill="#c60c30"', 'fill="#ffffff"')


def read_svg_body(path: Path):
    """Return (inner_markup, min_x, min_y, width, height) for the source SVG."""
    text = path.read_text()
    m = re.search(r"<svg\b([^>]*)>(.*)</svg>", text, re.DOTALL)
    if not m:
        raise ValueError(f"could not parse {path}")
    attrs, body = m.group(1), m.group(2)
    vb = re.search(r'viewBox\s*=\s*"([^"]+)"', attrs)
    if vb:
        x0, y0, w, h = (float(v) for v in vb.group(1).replace(",", " ").split())
    else:
        x0 = y0 = 0.0
        w = float(re.search(r'width\s*=\s*"([\d.]+)', attrs).group(1))
        h = float(re.search(r'height\s*=\s*"([\d.]+)', attrs).group(1))
    return body, x0, y0, w, h


def scale_about(a, px, py):
    """SVG transform for scaling by `a` about the point (px, py)."""
    return f"translate({px:.4f},{py:.4f}) scale({a:.8f}) translate({-px:.4f},{-py:.4f})"


def build_frame_svg(t, cfg):
    """SVG markup for the frame at normalized time t in [0, 1)."""
    s, P, C, R = cfg["s"], cfg["P"], cfg["C"], cfg["R"]
    W, H = cfg["W"], cfg["H"]
    m = s ** (-t)  # camera magnification: 1 at t=0, 1/s at t=1

    # Draw levels outward-in until a nested copy is smaller than a pixel.
    levels = []
    n = 0
    while True:
        a = m * s**n
        levels.append(a)
        if a * H < 1.5 or n > 12:
            break
        n += 1

    # Innermost first, then wrap each level in the window cut into its parent.
    inner = ""
    for n in range(len(levels) - 1, -1, -1):
        a = levels[n]
        content = f'<g transform="{scale_about(a, *P)}"><use href="#canvas"/></g>'
        if n == 0:
            inner = content + inner
        else:
            if cfg["window"] == "circle":  # the parent's dot itself
                ap = levels[n - 1]
                shape = (
                    f'<circle cx="{P[0] + ap * (C[0] - P[0]):.4f}" '
                    f'cy="{P[1] + ap * (C[1] - P[1]):.4f}" r="{ap * R:.4f}"/>'
                )
            else:  # this level's own frame, inscribed in the parent's dot
                shape = (
                    f'<rect x="{P[0] * (1 - a):.4f}" y="{P[1] * (1 - a):.4f}" '
                    f'width="{a * W:.4f}" height="{a * H:.4f}"/>'
                )
            cid = f"clip{n}"
            inner = (
                f'<clipPath id="{cid}" clipPathUnits="userSpaceOnUse">{shape}</clipPath>'
                f'<g clip-path="url(#{cid})">{content}{inner}</g>'
            )

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'width="{W}" height="{H}" viewBox="0 0 {W} {H}">'
        f"<defs><g id=\"canvas\">"
        f'<rect x="0" y="0" width="{W}" height="{H}" fill="{cfg["bg"]}"/>'
        f'<g transform="translate({cfg["ox"]:.4f},{cfg["oy"]:.4f}) scale({cfg["k"]:.8f})">'
        f'{cfg["map_body"]}</g></g></defs>'
        f'<rect x="0" y="0" width="{W}" height="{H}" fill="{cfg["bg"]}"/>'
        f"{inner}</svg>"
    )


def render(svg_markup, W, H, ss):
    png = cairosvg.svg2png(
        bytestring=svg_markup.encode("utf-8"),
        output_width=W * ss,
        output_height=H * ss,
    )
    img = Image.open(io.BytesIO(png)).convert("RGB")
    if ss != 1:
        img = img.resize((W, H), Image.LANCZOS)
    return img


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--svg", type=Path, default=DEFAULT_SVG)
    ap.add_argument("--out-prefix", type=Path, default=HERE / "orange-line-fractal-og",
                    help="output stem; each variant appends its own suffix and .gif")
    ap.add_argument("--variants", nargs="+", default=["zoom-in", "zoom-out", "bounce", "poster"],
                    choices=("zoom-in", "zoom-out", "bounce", "poster"))
    ap.add_argument("--width", type=int, default=800)
    ap.add_argument("--height", type=int, default=420)
    ap.add_argument("--duration", type=float, default=10.0, help="seconds for one full loop")
    ap.add_argument("--fps", type=float, default=20.0)
    ap.add_argument("--stop", default="harold-washington-library",
                    help=f"named Loop stop {sorted(LOOP_STOPS)} or raw 'cx,cy' in SVG units")
    ap.add_argument("--stop-radius", type=float, default=11.0,
                    help="radius (map units) of the dot the nested map is dropped into; "
                         "11 = the filled center of a transfer marker (its black ring survives "
                         "as a porthole frame), 22 = the whole marker")
    ap.add_argument("--fit", type=float, default=0.88, help="fraction of frame height the map occupies")
    ap.add_argument("--inset", type=float, default=0.85,
                    help="how far inside the dot the nested frame sits, as a fraction of the "
                         "dot radius. 1.0 inscribes it exactly, so its corners graze the black "
                         "ring; below that it clears the ring with air to spare. Costs zoom "
                         "depth per loop, not seamlessness.")
    ap.add_argument("--keep-pointers", action="store_true",
                    help="keep the source card's you-are-here arrow and solid red stop center "
                         "(by default only the two red pulse rings are kept)")
    ap.add_argument("--window", choices=("rect", "circle"), default="rect",
                    help="shape of the nested copy: 'rect' inscribes the whole frame in the dot "
                         "and loops exactly; 'circle' clips to the dot, showing more map per "
                         "level but breaking the wrap in the frame corners")
    ap.add_argument("--bg", default="#ffffff")
    ap.add_argument("--supersample", type=int, default=2)
    ap.add_argument("--colors", type=int, default=64)
    args = ap.parse_args()

    map_body, mx0, my0, mw, mh = read_svg_body(args.svg)
    if not args.keep_pointers:
        map_body = strip_pointers(map_body)

    if args.stop in LOOP_STOPS:
        sx, sy = LOOP_STOPS[args.stop]
    else:
        sx, sy = (float(v) for v in args.stop.split(","))

    W, H = args.width, args.height
    k = args.fit * H / mh                  # map -> canvas scale
    ox = (W - k * mw) / 2.0 - k * mx0      # viewBox origin folded into the offset
    oy = (H - k * mh) / 2.0 - k * my0
    C = (ox + k * sx, oy + k * sy)         # stop center, canvas coords
    R = k * args.stop_radius
    span = math.hypot(W, H) if args.window == "rect" else H
    s = 2.0 * R * args.inset / span        # nested frame inscribed in / covering the dot
    center = (W / 2.0, H / 2.0)
    P = ((C[0] - s * center[0]) / (1 - s), (C[1] - s * center[1]) / (1 - s))

    cfg = dict(map_body=map_body, W=W, H=H, k=k, ox=ox, oy=oy, C=C, R=R, s=s, P=P,
               bg=args.bg, window=args.window)

    n_frames = max(2, int(round(args.duration * args.fps)))
    delay_ms = int(round(args.duration * 1000 / n_frames))
    print(f"zoom per loop: {1/s:.1f}x over {args.duration}s "
          f"({n_frames} frames @ {delay_ms}ms, {math.log(1/s)/args.duration:.2f} e-folds/s, "
          f"{(1/s)**(1/n_frames):.4f}x per frame)")

    def render_track(times, label):
        out = []
        for i, t in enumerate(times):
            out.append(render(build_frame_svg(t, cfg), W, H, args.supersample))
            print(f"\r{label}: frame {i+1}/{len(times)}", end="", flush=True)
        print()
        return out

    def save_gif(frames, suffix, delay):
        # Flat vector art: dithering only adds noise (and GIF bytes), so leave it off.
        frames = [f.quantize(colors=args.colors, method=Image.MEDIANCUT, dither=Image.NONE)
                  for f in frames]
        path = args.out_prefix.with_name(args.out_prefix.name + suffix + ".gif")
        path.parent.mkdir(parents=True, exist_ok=True)
        frames[0].save(path, save_all=True, append_images=frames[1:],
                       duration=delay, loop=0, optimize=True, disposal=2)
        print(f"wrote {path.name}: {len(frames)} frames, "
              f"{len(frames) * delay / 1000:.1f}s, {path.stat().st_size/1e6:.2f} MB")

    want = set(args.variants)
    if "poster" in want:
        # Static fallback for anything that will not take a multi-megabyte GIF. t=0 is the
        # whole map, and is also frame 0 of the zoom-out GIF, so the still and the animation
        # agree wherever a platform shows only the first frame.
        path = args.out_prefix.with_name(args.out_prefix.name + "-poster.png")
        path.parent.mkdir(parents=True, exist_ok=True)
        render(build_frame_svg(0.0, cfg), W, H, args.supersample).save(path, optimize=True)
        print(f"wrote {path.name}: {W}x{H}, {path.stat().st_size/1024:.0f} KB")

    forward = None
    if want & {"zoom-in", "zoom-out"}:
        forward = render_track([i / n_frames for i in range(n_frames)], "zoom-in")
    if "zoom-in" in want:
        save_gif(forward, "-zoom-in", delay_ms)
    if "zoom-out" in want:
        # The same climb played backwards: falling out of the stop instead of into it.
        save_gif(forward[::-1], "-zoom-out", delay_ms)
    if "bounce" in want:
        # One round trip, eased so the reversals are turns rather than jolts:
        # t = (1 - cos(2*pi*u))/2 runs 0 -> 1 -> 0 with zero velocity at both ends, and
        # its velocity is continuous across the wrap, so the ping-pong never snaps.
        n_b = 2 * n_frames
        times = [(1 - math.cos(2 * math.pi * i / n_b)) / 2 for i in range(n_b)]
        print(f"bounce: {n_b} frames, peak speed {math.pi/2:.2f}x the steady zoom rate")
        save_gif(render_track(times, "bounce"), "-bounce", delay_ms)


if __name__ == "__main__":
    main()
