#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM coding agent (Claude). Review before promoting out of sandbox/.

`make_datasaurus_gif_og.py` for a 404 page: the same Datasaurus loop, with the Orange Line
route swapped out for the digits 404.

The card cycles 404, dino, 404, star, 404, circle, 404, dots -- the digits are the refrain
the cloud keeps coming back to, so a visitor who lands on a missing page sees the number
first, watches it fall apart into a dinosaur, and gets it back a second later. Every shape
carries the Datasaurus Dozen's mean(x), mean(y), sd(x) and sd(y), the 404 included.

The digits
----------
Drawn as text, not traced: a bold TextPath for "404", flattened to polylines, then walked
at even arc length over every contour at once -- outer edges and the two counters inside
the zeros alike -- so the dots land evenly spaced over the whole glyph set and each digit
gets a share of them proportional to how much outline it has.

Two ways to sit in the frame
----------------------------
"404" is naturally wide and short; the dozen's spread is much taller than it is wide, so
no legible horizontal 404 can carry sd(x) = 16.8 and sd(y) = 26.9 at once. The script picks
which half of that to keep:

  --fit legible (default)  one scale on both axes, sized to fill the card and centred on
                           the dozen's mean(x) and mean(y). The digits keep their real
                           proportions and read as digits; sd(x) and sd(y) do not match.
  --fit stats              each axis z-scored on its own onto the dozen's moments. All four
                           statistics land exactly -- the same bargain `make_datasaurus_gif_og.py`
                           strikes with the Orange Line -- but the ~3x vertical stretch
                           squeezes the digits into a condensed cut that is hard to read at
                           card size. Kept because it is the honest Datasaurus move.

Usage
-----
    python make_datasaurus_404_gif.py
    python make_datasaurus_404_gif.py --width 1200 --poster
    python make_datasaurus_404_gif.py --fit stats --poster
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import polars as pl
from matplotlib.animation import PillowWriter
from matplotlib.font_manager import FontProperties
from matplotlib.textpath import TextPath

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[3]
DATA_PATH = REPO_ROOT / "datasets" / "datasaurus-dozen" / "datasaurus-dozen.csv"

ORANGE = "#F9461C"
PAPER = "#FFFFFF"

# Three shapes borrowed from the dozen, plus the Chicago star and the digits.
FROM_CSV = ("dino", "star", "circle", "dots")
BORROWED = ("dino", "star", "circle", "dots")
GLYPH = "404"

# The digits are the refrain: every borrowed shape passes back through 404 on its way to
# the next one. Starting on 404 also closes the loop, since the last shape morphs back into
# the first.
ORDER = tuple(x for name in BORROWED for x in (GLYPH, name))


def _angle_sorted(pts: np.ndarray) -> np.ndarray:
    """Rows ordered by angle around the centroid, in spread-normalized units.

    Every shape sorted the same way pairs point i in one with a point in roughly the same
    direction from the middle of the next, so the straight-line morph between them reads as
    the cloud rearranging rather than scrambling.
    """
    centered = pts - pts.mean(axis=0)
    angle = np.arctan2(
        centered[:, 1] / centered[:, 1].std(), centered[:, 0] / centered[:, 0].std()
    )
    return pts[np.argsort(angle)]


def _text_outline(text: str, weight: str, family: str) -> tuple[np.ndarray, np.ndarray]:
    """Every contour of `text` as one polyline soup: segment starts and segment vectors.

    Contours are kept separate (each is closed on itself) but returned concatenated, so a
    single cumulative-length walk over the result spaces points evenly across all of them
    at once -- which is also what shares the points out between the digits fairly.
    """
    path = TextPath((0, 0), text, size=1.0, prop=FontProperties(family=family, weight=weight))
    starts, vectors = [], []
    for poly in path.to_polygons():
        if len(poly) < 2:
            continue
        ring = poly if np.allclose(poly[0], poly[-1]) else np.vstack([poly, poly[:1]])
        starts.append(ring[:-1])
        vectors.append(np.diff(ring, axis=0))
    return np.vstack(starts), np.vstack(vectors)


def glyph_points(
    n: int,
    moments: tuple[float, float, float, float],
    text: str = GLYPH,
    weight: str = "bold",
    family: str = "DejaVu Sans",
    fit: str = "legible",
    width: float | None = None,
) -> np.ndarray:
    """`n` points walked at even arc length over the outlines of `text`.

    `fit="legible"` scales both axes by the same factor so the digits keep their shape,
    sizing them to `width` data units across, and centres them on the dozen's means.
    `fit="stats"` z-scores each axis on its own so all four moments match exactly, at the
    cost of a tall condensed 404. See the module docstring.
    """
    starts, vectors = _text_outline(text, weight, family)
    edge = np.linalg.norm(vectors, axis=1)
    walked = np.concatenate([[0.0], np.cumsum(edge)])
    # Open interval: half a step in from each end, so no two dots stack on a contour seam.
    s = (np.arange(n) + 0.5) * walked[-1] / n
    i = np.clip(np.searchsorted(walked, s, "right") - 1, 0, len(edge) - 1)
    t = ((s - walked[i]) / edge[i])[:, None]
    pts = starts[i] + t * vectors[i]

    mean_x, mean_y, sd_x, sd_y = moments
    if fit == "legible":
        pts = pts * ((width if width is not None else 4 * sd_x) / np.ptp(pts[:, 0]))
        return pts + np.array([mean_x - pts[:, 0].mean(), mean_y - pts[:, 1].mean()])

    out = np.empty_like(pts)
    for col, mean, sd in ((0, mean_x, sd_x), (1, mean_y, sd_y)):
        v = pts[:, col]
        out[:, col] = (v - v.mean()) / v.std(ddof=1) * sd + mean
    return out


def load_shapes(aspect: float, fill: float = 0.82, **glyph_kwargs) -> dict[str, np.ndarray]:
    """The four borrowed shapes plus the digits, all sorted the same way for morphing.

    `aspect` is the card's width/height. The borrowed shapes are as tall as the card and
    leave its flanks empty, so the digits are sized against the *frame* -- `fill` of its
    width -- rather than against the dino, which is what lets them read at card size.
    """
    df = pl.read_csv(DATA_PATH)
    shapes: dict[str, np.ndarray] = {}
    for name in FROM_CSV:
        sub = df.filter(pl.col("dataset") == name)
        shapes[name] = _angle_sorted(
            np.column_stack([sub["x"].to_numpy(), sub["y"].to_numpy()])
        )
    dino = shapes["dino"]
    moments = (
        dino[:, 0].mean(), dino[:, 1].mean(),
        dino[:, 0].std(ddof=1), dino[:, 1].std(ddof=1),
    )
    frame_width = np.ptp(np.vstack(list(shapes.values()))[:, 1]) * aspect
    shapes[GLYPH] = _angle_sorted(
        glyph_points(len(dino), moments, width=fill * frame_width, **glyph_kwargs)
    )
    return shapes


def smoothstep(t: float) -> float:
    return t * t * (3 - 2 * t)


def stats_line(pts: np.ndarray) -> str:
    x, y = pts[:, 0], pts[:, 1]
    return (
        f"mean(x) = {x.mean():.2f}  mean(y) = {y.mean():.2f}  "
        f"sd(x) = {x.std(ddof=1):.2f}  sd(y) = {y.std(ddof=1):.2f}  "
        f"r = {np.corrcoef(x, y)[0, 1]:.2f}"
    )


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", type=Path, default=HERE / "datasaurus-404.gif")
    ap.add_argument("--width", type=int, default=1000, help="canvas width; height follows the golden ratio")
    ap.add_argument("--dpi", type=int, default=100)
    ap.add_argument("--hold", type=float, default=0.65, help="seconds a shape sits still")
    ap.add_argument("--morph", type=float, default=0.5, help="seconds spent travelling to the next shape")
    ap.add_argument("--fps", type=float, default=25.0)
    ap.add_argument("--size", type=float, default=55.0, help="point area in pt^2")
    ap.add_argument(
        "--alpha",
        type=float,
        default=0.8,
        help="point opacity; below ~0.8 stacked points start to show as darker overlaps",
    )
    ap.add_argument("--text", default=GLYPH, help="the digits to draw (default: 404)")
    ap.add_argument("--font", default="DejaVu Sans", help="font family for the digits")
    ap.add_argument("--weight", default="bold", help="font weight for the digits")
    ap.add_argument(
        "--fit",
        choices=("legible", "stats"),
        default="legible",
        help="legible: real proportions, sized to the card; stats: exact match to all four moments",
    )
    ap.add_argument(
        "--fill",
        type=float,
        default=0.82,
        help="with --fit legible, how much of the card's width the digits span",
    )
    ap.add_argument("--poster", action="store_true", help="also write a PNG of the digits")
    args = ap.parse_args()

    width = args.width
    height = round(width / ((1 + 5 ** 0.5) / 2))
    shapes = load_shapes(
        width / height,
        fill=args.fill,
        text=args.text,
        weight=args.weight,
        family=args.font,
        fit=args.fit,
    )

    fig, ax = plt.subplots(figsize=(width / args.dpi, height / args.dpi), dpi=args.dpi)
    fig.patch.set_facecolor(PAPER)
    ax.set_facecolor(PAPER)
    ax.set_position((0, 0, 1, 1))  # the cloud is the whole card; nothing else on it
    ax.set_axis_off()

    every = np.vstack(list(shapes.values()))
    # One data unit is the same length on both axes -- the dino is never squashed -- so the
    # landscape frame is filled by widening the x window, not by stretching the shapes.
    pad = 0.03 * np.ptp(every[:, 1])
    ylim = (every[:, 1].min() - pad, every[:, 1].max() + pad)
    span_x = max(np.ptp(ylim) * width / height, np.ptp(every[:, 0]) + 2 * pad)
    mid_x = (every[:, 0].min() + every[:, 0].max()) / 2
    ax.set_xlim(mid_x - span_x / 2, mid_x + span_x / 2)
    ax.set_ylim(*ylim)

    # Slightly transparent, so where the outline crowds -- the corners of the 4, the tight
    # ends of the zeros -- the pile-up reads as a deeper orange instead of one flat blob.
    scatter = ax.scatter([], [], s=args.size, color=ORANGE, alpha=args.alpha, linewidths=0)

    hold_frames = max(1, round(args.hold * args.fps))
    morph_frames = max(1, round(args.morph * args.fps))
    frames: list[np.ndarray] = []
    for i, name in enumerate(ORDER):
        here, there = shapes[name], shapes[ORDER[(i + 1) % len(ORDER)]]
        frames.extend(here for _ in range(hold_frames))
        for step in range(1, morph_frames + 1):
            t = smoothstep(step / (morph_frames + 1))
            frames.append((1 - t) * here + t * there)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    writer = PillowWriter(fps=args.fps)
    with writer.saving(fig, str(args.out), dpi=args.dpi):
        for pts in frames:
            scatter.set_offsets(pts)
            writer.grab_frame(facecolor=PAPER)

    if args.poster:
        scatter.set_offsets(shapes[GLYPH])
        fig.savefig(args.out.with_suffix(".png"), facecolor=PAPER, dpi=args.dpi)
        print(f"wrote {args.out.with_suffix('.png')}")
    plt.close(fig)

    print(f"wrote {args.out} ({args.out.stat().st_size / 1e6:.2f} MB)")
    print(f"  {width}x{height}, {len(frames)} frames at {args.fps:g} fps")
    print("  " + " -> ".join(ORDER))
    for name in (GLYPH,) + BORROWED:
        print(f"  {name:>6}  {stats_line(shapes[name])}")


if __name__ == "__main__":
    main()
