#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM coding agent (Claude). Review before promoting out of sandbox/.

A stripped-down Datasaurus loop for the site's social card: orange points on white, no
axes, no labels, no statistics readout, in a landscape golden rectangle.

Five shapes instead of thirteen -- dino, star, circle, dots, and a new one, lasso -- so
that at card size each one is on screen long enough to register. The lasso is interleaved
between the other four rather than taking a turn of its own: lasso, dino, lasso, star, and
so on, so the route is the shape the card keeps coming back to.

The lasso
---------
The fifth shape is the Orange Line itself: points sampled at even arc length along the
route the chevron GIF animates (Harold Washington Library, clockwise around the Loop,
then the whole stem down to Midway), flipped out of SVG's y-down coordinates and then
z-scored back onto the Datasaurus Dozen's own mean(x), mean(y), sd(x), sd(y). Standardizing
each axis on its own is exactly what makes the numbers match, and it is also what stretches
the route: the dino's spread is much taller than it is wide, so the Loop comes out taller
than it is on a map. That is the joke -- one more dataset with the same summary statistics
and a shape nobody would guess -- so r is deliberately left alone.

Usage
-----
    python make_datasaurus_gif_og.py
    python make_datasaurus_gif_og.py --width 1200 --duration 1.1 --poster
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import polars as pl
from matplotlib.animation import PillowWriter

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[3]
DATA_PATH = REPO_ROOT / "datasets" / "datasaurus-dozen" / "datasaurus-dozen.csv"
ROUTE_SVG = HERE.parent / "orange-line-trace.svg"

# The chevron script already knows how to flatten these two paths into one inbound route.
sys.path.insert(0, str(HERE))
from make_chevron_gif_og import build_route, parse_path, read_svg  # noqa: E402

ORANGE = "#F9461C"
PAPER = "#FFFFFF"

# Four shapes borrowed from the dozen, plus the route.
BORROWED = ("dino", "star", "circle", "dots")
SHAPES = BORROWED + ("lasso",)

# The lasso is the refrain: every borrowed shape passes back through the Orange Line on its
# way to the next one, so the route is what the eye keeps returning to and the other four
# read as departures from it. Starting on the lasso also closes the loop, since the last
# shape morphs back into the first.
ORDER = tuple(x for name in BORROWED for x in ("lasso", name))


def _angle_sorted(pts: np.ndarray) -> np.ndarray:
    """Rows ordered by angle around the centroid, in spread-normalized units.

    Every shape sorted the same way pairs point i in one with a point in roughly the same
    direction from the middle of the next, so the straight-line morph between them reads
    as the cloud rearranging rather than scrambling.
    """
    centered = pts - pts.mean(axis=0)
    angle = np.arctan2(
        centered[:, 1] / centered[:, 1].std(), centered[:, 0] / centered[:, 0].std()
    )
    return pts[np.argsort(angle)]


def route_points(n: int, moments: tuple[float, float, float, float]) -> np.ndarray:
    """`n` points evenly spaced along the Orange Line, matched to the dozen's moments."""
    body, _, _ = read_svg(ROUTE_SVG)
    d = dict(
        (m.group(1), m.group(2))
        for m in __import__("re").finditer(r'<path id="([^"]+)"[^>]*\sd="([^"]+)"', body)
    )
    route = build_route(parse_path(d["Path"]), parse_path(d["path1"]))
    # Open interval: the endpoints of the route are a fade-out in the chevron animation and
    # would sit as two lonely outliers here.
    s = (np.arange(n) + 0.5) * route.length / n
    pts = np.array([route.at(v)[:2] for v in s])
    pts[:, 1] *= -1  # SVG y grows downward; data y grows up

    mean_x, mean_y, sd_x, sd_y = moments
    out = np.empty_like(pts)
    for col, mean, sd in ((0, mean_x, sd_x), (1, mean_y, sd_y)):
        v = pts[:, col]
        out[:, col] = (v - v.mean()) / v.std(ddof=1) * sd + mean
    return out


def load_shapes() -> dict[str, np.ndarray]:
    df = pl.read_csv(DATA_PATH)
    shapes: dict[str, np.ndarray] = {}
    for name in BORROWED:
        sub = df.filter(pl.col("dataset") == name)
        shapes[name] = _angle_sorted(
            np.column_stack([sub["x"].to_numpy(), sub["y"].to_numpy()])
        )
    dino = shapes["dino"]
    moments = (
        dino[:, 0].mean(), dino[:, 1].mean(),
        dino[:, 0].std(ddof=1), dino[:, 1].std(ddof=1),
    )
    shapes["lasso"] = _angle_sorted(route_points(len(dino), moments))
    return shapes


def smoothstep(t: float) -> float:
    return t * t * (3 - 2 * t)


def stats_line(pts: np.ndarray) -> str:
    x, y = pts[:, 0], pts[:, 1]
    return (
        f"mean(x) = {x.mean():.2f}  mean(y) = {y.mean():.2f}  "
        f"sd(x) = {x.std(ddof=1):.2f}  sd(y) = {y.std(ddof=1):.2f}  "
        f"r = {np.corrcoef(x, y)[0, 1]:.2f}"
    )


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", type=Path, default=HERE / "datasaurus-og.gif")
    ap.add_argument("--width", type=int, default=1000, help="canvas width; height follows the golden ratio")
    ap.add_argument("--dpi", type=int, default=100)
    ap.add_argument("--hold", type=float, default=0.65, help="seconds a shape sits still")
    ap.add_argument("--morph", type=float, default=0.5, help="seconds spent travelling to the next shape")
    ap.add_argument("--fps", type=float, default=25.0)
    ap.add_argument("--size", type=float, default=55.0, help="point area in pt^2")
    ap.add_argument("--poster", action="store_true", help="also write a PNG of frame 0")
    args = ap.parse_args()

    width = args.width
    height = round(width / ((1 + 5 ** 0.5) / 2))
    shapes = load_shapes()

    fig, ax = plt.subplots(figsize=(width / args.dpi, height / args.dpi), dpi=args.dpi)
    fig.patch.set_facecolor(PAPER)
    ax.set_facecolor(PAPER)
    ax.set_position((0, 0, 1, 1))  # the cloud is the whole card; nothing else on it
    ax.set_axis_off()

    every = np.vstack(list(shapes.values()))
    # One data unit is the same length on both axes -- the dino is never squashed -- so the
    # landscape frame is filled by widening the x window, not by stretching the shapes.
    pad = 0.03 * np.ptp(every[:, 1])
    ylim = (every[:, 1].min() - pad, every[:, 1].max() + pad)
    span_x = np.ptp(ylim) * width / height
    mid_x = (every[:, 0].min() + every[:, 0].max()) / 2
    ax.set_xlim(mid_x - span_x / 2, mid_x + span_x / 2)
    ax.set_ylim(*ylim)

    scatter = ax.scatter([], [], s=args.size, color=ORANGE, alpha=0.9, linewidths=0)

    hold_frames = max(1, round(args.hold * args.fps))
    morph_frames = max(1, round(args.morph * args.fps))
    frames: list[np.ndarray] = []
    for i, name in enumerate(ORDER):
        here, there = shapes[name], shapes[ORDER[(i + 1) % len(ORDER)]]
        frames.extend(here for _ in range(hold_frames))
        for step in range(1, morph_frames + 1):
            t = smoothstep(step / (morph_frames + 1))
            frames.append((1 - t) * here + t * there)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    writer = PillowWriter(fps=args.fps)
    with writer.saving(fig, str(args.out), dpi=args.dpi):
        for pts in frames:
            scatter.set_offsets(pts)
            writer.grab_frame(facecolor=PAPER)

    if args.poster:
        scatter.set_offsets(shapes["lasso"])
        fig.savefig(args.out.with_suffix(".png"), facecolor=PAPER, dpi=args.dpi)
        print(f"wrote {args.out.with_suffix('.png')}")
    plt.close(fig)

    print(f"wrote {args.out} ({args.out.stat().st_size / 1e6:.2f} MB)")
    print(f"  {width}x{height}, {len(frames)} frames at {args.fps:g} fps")
    print("  " + " -> ".join(ORDER))
    for name in SHAPES:
        print(f"  {name:>6}  {stats_line(shapes[name])}")


if __name__ == "__main__":
    main()
