#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM coding agent (Claude). Review before promoting out of sandbox/.

The chevron GIF's motion, applied to the Datasaurus version of the Orange Line.

`make_chevron_gif_og.py` crawls four white chevrons along the route on top of the map.
`make_datasaurus_gif_og.py` turns that same route into the `lasso` dataset -- points at
even arc length along the line, z-scored onto the Datasaurus Dozen's mean(x), mean(y),
sd(x) and sd(y). This script animates the second with the first's trick: the whole point
cloud crawls, dots slipping off the end at Midway as new ones are born back at Harold
Washington Library, and the summary statistics come back to the dozen's every time the
dots arrive at the next stop.

One track
---------
There is a single fixed track -- the route, flipped out of SVG's y-down coordinates and
put through the lasso's standardization ONCE -- and every dot simply slides along it at
constant arc-length speed. Nothing is recomputed per frame and no dot ever leaves the
line, so the cloud cannot breathe, drift, or cut a corner. Over one loop each dot advances
--advance station gaps, so dot k lands exactly where dot k+A started and the loop is exact.

Where the statistics land
-------------------------
The dots are the route sampled by an evenly spaced comb. Whenever the comb has slid by a
whole number of gaps -- t = 0, 1/A, 2/A, ... 1 -- the set of sampled positions is the lasso
again, dots relabelled, so mean(x), mean(y), sd(x) and sd(y) are exactly the dozen's. At
A = 2 and 20 fps that is every 20th frame.

In between, the comb sits at a fractional offset and the moments ride about 1% off; that is
the cost of putting the dots on a real track instead of correcting them into place, and it
is the reason an earlier version appeared to expand and contract. Frame count is rounded to
a multiple of A so the exact frames are always among the ones actually rendered.

The wrap
--------
Opacity is a pure function of arc length, so it slides along the track with the dot that
carries it. The ramp is pinned to zero over the first and last A dot-slots, which makes the
crossing from Midway back to the library invisible for its whole duration and needs no
special case: a wrapping dot is unlit before it leaves and still unlit when it arrives.

Usage
-----
    python make_datasaurus_crawl_gif_og.py
    python make_datasaurus_crawl_gif_og.py --advance 1 --duration 6 --poster
    python make_datasaurus_crawl_gif_og.py --stats   # burn the summary line into the card
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import polars as pl
from matplotlib.animation import PillowWriter
from matplotlib.colors import to_rgb

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[3]
DATA_PATH = REPO_ROOT / "datasets" / "datasaurus-dozen" / "datasaurus-dozen.csv"
ROUTE_SVG = HERE.parent / "orange-line-trace.svg"

# The chevron script already knows how to flatten the two route paths into one inbound
# run: library, clockwise around the Loop, then the whole stem down to Midway.
sys.path.insert(0, str(HERE))
from make_chevron_gif_og import build_route, parse_path, read_svg  # noqa: E402

ORANGE = "#F9461C"
PAPER = "#FFFFFF"


def load_route():
    body, _, _ = read_svg(ROUTE_SVG)
    d = dict(re.findall(r'<path id="([^"]+)"[^>]*\sd="([^"]+)"', body))
    return build_route(parse_path(d["Path"]), parse_path(d["path1"]))


def dozen_moments() -> tuple[float, float, float, float]:
    """mean(x), mean(y), sd(x), sd(y) of the dino -- the moments the whole dozen shares."""
    sub = pl.read_csv(DATA_PATH).filter(pl.col("dataset") == "dino")
    x, y = sub["x"].to_numpy(), sub["y"].to_numpy()
    return x.mean(), y.mean(), x.std(ddof=1), y.std(ddof=1)


def raw(route, s: np.ndarray) -> np.ndarray:
    """Route positions at the given arc lengths, in data orientation."""
    pts = np.array([route.at(v)[:2] for v in s])
    pts[:, 1] *= -1  # SVG y grows downward; data y grows up
    return pts


class Track:
    """The route as one fixed curve in the dozen's coordinates.

    The standardization is fitted once, on the lasso's own sample, and then frozen. Every
    dot at every time is that one map applied to a point of the route, which is what keeps
    the animation a slide along a track rather than a cloud being re-fitted each frame.
    """

    def __init__(self, route, n: int, moments):
        self.route = route
        self.gap = route.length / n
        # Open interval: the ends of the route are a fade-out and would sit in the dataset
        # as two lonely outliers.
        seed = raw(route, (np.arange(n) + 0.5) * self.gap)
        mean_x, mean_y, sd_x, sd_y = moments
        self.scale = np.array([sd_x / seed[:, 0].std(ddof=1), sd_y / seed[:, 1].std(ddof=1)])
        self.shift = np.array([mean_x, mean_y]) - self.scale * seed.mean(axis=0)

    def at(self, s: np.ndarray) -> np.ndarray:
        return raw(self.route, s % self.route.length) * self.scale + self.shift


def smoothstep(x: np.ndarray) -> np.ndarray:
    x = np.clip(x, 0.0, 1.0)
    return x * x * (3 - 2 * x)


def opacity(s: np.ndarray, gap: float, length: float, fade: float,
            alpha: float, advance: int) -> np.ndarray:
    """Ink as a function of arc length: nothing at either end, full in the middle.

    The ramp is pinned to zero over the first and last `advance` dot-slots rather than at
    the very ends of the route. A dot that runs off the end at Midway is therefore already
    dark, and stays dark until it has climbed back out of the first slots at the library,
    so its crossing is never drawn.
    """
    lo, hi = (advance - 0.5) * gap, length - (advance - 0.5) * gap
    return alpha * smoothstep((s % length - lo) / fade) * smoothstep((hi - s % length) / fade)


def stats_line(pts: np.ndarray) -> str:
    x, y = pts[:, 0], pts[:, 1]
    return (
        f"mean(x) = {x.mean():.2f}  mean(y) = {y.mean():.2f}  "
        f"sd(x) = {x.std(ddof=1):.2f}  sd(y) = {y.std(ddof=1):.2f}  "
        f"r = {np.corrcoef(x, y)[0, 1]:.2f}"
    )


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", type=Path, default=HERE / "datasaurus-crawl-og.gif")
    ap.add_argument("--width", type=int, default=500)
    ap.add_argument("--height", type=int, default=800)
    ap.add_argument("--dpi", type=int, default=100)
    ap.add_argument("--points", type=int, default=142, help="dots on the route; the dozen uses 142")
    ap.add_argument("--advance", type=int, default=2,
                    help="station gaps each dot covers per loop, and so how fast the cloud "
                         "crawls; the moments come back to the dozen's once per gap")
    ap.add_argument("--duration", type=float, default=4.0, help="seconds for one full loop")
    ap.add_argument("--fps", type=float, default=20.0)
    ap.add_argument("--size", type=float, default=55.0, help="point area in pt^2")
    ap.add_argument("--alpha", type=float, default=0.8, help="opacity of a dot at full ink")
    ap.add_argument(
        "--fade",
        type=float,
        default=70.0,
        help="map units over which a dot fades in at the library and out at Midway; the "
             "ramp is what hides the wrap",
    )
    ap.add_argument("--stats", action="store_true", help="print the summary line on the card")
    ap.add_argument("--poster", action="store_true", help="also write a PNG of frame 0")
    args = ap.parse_args()

    route = load_route()
    track = Track(route, args.points, dozen_moments())
    n, A, L = args.points, args.advance, route.length

    # A multiple of A, so the frames where the comb sits on whole gaps -- the frames whose
    # moments are exactly the dozen's -- are frames that actually get rendered.
    n_frames = max(A, round(args.duration * args.fps / A) * A)
    offsets = (np.arange(n) + 0.5) * track.gap
    steps = []
    for i in range(n_frames):
        s = offsets + (i / n_frames) * A * track.gap
        steps.append((track.at(s),
                      opacity(s, track.gap, L, args.fade, args.alpha, A)))

    fig, ax = plt.subplots(
        figsize=(args.width / args.dpi, args.height / args.dpi), dpi=args.dpi
    )
    fig.patch.set_facecolor(PAPER)
    ax.set_facecolor(PAPER)
    ax.set_position((0, 0, 1, 1))  # the cloud is the whole card
    ax.set_axis_off()

    # The window frames the track itself, not any one frame's sample, so it cannot shift as
    # the dots slide. One data unit is the same length on both axes: the route is never
    # squashed further than the standardization already has.
    whole = track.at(np.linspace(0, L, 4000))
    mid = (whole.min(axis=0) + whole.max(axis=0)) / 2
    need = np.ptp(whole, axis=0) * 1.06  # a little air around the cloud
    span_y = max(need[1], need[0] * args.height / args.width)
    span_x = span_y * args.width / args.height
    ax.set_xlim(mid[0] - span_x / 2, mid[0] + span_x / 2)
    ax.set_ylim(mid[1] - span_y / 2, mid[1] + span_y / 2)

    rgb = to_rgb(ORANGE)
    scatter = ax.scatter([], [], s=args.size, linewidths=0)
    caption = None
    if args.stats:
        caption = ax.text(
            0.5, 0.015, "", transform=ax.transAxes, ha="center", va="bottom",
            fontsize=7, color="#444444", family="monospace",
        )

    def draw(pts: np.ndarray, a: np.ndarray) -> None:
        scatter.set_offsets(pts)
        scatter.set_facecolors(np.column_stack([np.tile(rgb, (len(pts), 1)), a]))
        if caption is not None:
            caption.set_text(stats_line(pts))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    writer = PillowWriter(fps=args.fps)
    with writer.saving(fig, str(args.out), dpi=args.dpi):
        for pts, a in steps:
            draw(pts, a)
            writer.grab_frame(facecolor=PAPER)

    if args.poster:
        draw(*steps[0])
        fig.savefig(args.out.with_suffix(".png"), facecolor=PAPER, dpi=args.dpi)
        print(f"wrote {args.out.with_suffix('.png')}")
    plt.close(fig)

    print(f"wrote {args.out} ({args.out.stat().st_size / 1e6:.2f} MB)")
    print(f"  {args.width}x{args.height}, {n_frames} frames at {args.fps:g} fps, "
          f"{n} dots {track.gap:.1f} map units apart, advancing {A}")
    for j in range(A + 1):
        i = j * n_frames // A
        pts = steps[i % n_frames][0]
        print(f"  frame {i:>3} (on a stop)  {stats_line(pts)}")


if __name__ == "__main__":
    main()
