#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM coding agent (Claude). Review before promoting out of sandbox/.

Cut the Loop out of orange-line-trace-with-stops.svg and build the site's icons from it.

The favicon is a crop, not a redrawing: the same artwork as the masthead and the og image,
zoomed to the one piece of it that is recognizably Chicago. The crop is tight enough that
the Loop fills the frame, and it keeps the stub where the Orange Line leaves the Loop
heading southwest, which is what makes it the *Orange* Line and not just a rectangle.
Station markers are dropped at every size -- the icon is the track path only.

Writes, relative to docs/:
    favicon.ico                        16/32/48/64/128 px, transparent
    assets/orange-line/loop-icon.svg   vector favicon for browsers that take one
    assets/orange-line/apple-touch-icon.png   180px, on white (iOS ignores alpha)
    assets/orange-line/icon-192.png, icon-512.png   Android/PWA, named in site.webmanifest
"""

import argparse
import io
import re
from pathlib import Path

import cairosvg
from PIL import Image

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "orange-line-trace-with-stops.svg"
DOCS = HERE.parents[2]

# The Loop, in map units. The track rectangle spans x 345..607, y 183..492; a 30-unit
# stroke and the r=22 transfer markers push the ink out to roughly 323..629 / 161..514.
LOOP_BOX = (323, 161, 306, 353)  # x, y, w, h
ICO_SIZES = (16, 32, 48, 64, 128)
PWA_SIZES = (192, 512)


def loop_svg(pad: float = 10.0) -> str:
    """The source map's track path alone, re-framed on the Loop and squared up.

    The Stops group goes: at icon sizes the station markers are grit, not dots, and even
    at 128px they clutter a shape whose whole job is to be recognized at a glance.
    """
    text = SRC.read_text()
    body = re.search(r"<svg\b[^>]*>(.*)</svg>", text, re.DOTALL).group(1)
    body = re.sub(r'<g id="Stops">.*?</g>\s*(?=<|$)', "", body, flags=re.DOTALL)
    x, y, w, h = LOOP_BOX
    side = max(w, h) + 2 * pad          # square viewBox so the icon never distorts
    x -= (side - w) / 2
    y -= (side - h) / 2
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{side:.0f}" height="{side:.0f}" '
        f'viewBox="{x:.2f} {y:.2f} {side:.2f} {side:.2f}">{body}</svg>'
    )


def render(markup: str, size: int, bg: str | None = None) -> Image.Image:
    png = cairosvg.svg2png(bytestring=markup.encode("utf-8"),
                           output_width=size, output_height=size,
                           background_color=bg)
    return Image.open(io.BytesIO(png)).convert("RGBA")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--docs", type=Path, default=DOCS, help="site root to write into")
    ap.add_argument("--pad", type=float, default=10.0, help="margin around the Loop, map units")
    args = ap.parse_args()

    markup = loop_svg(args.pad)
    assets = args.docs / "assets" / "orange-line"

    svg_path = assets / "loop-icon.svg"
    svg_path.write_text(markup + "\n")

    # Render every size from the vector rather than resampling one bitmap down.
    layers = [render(markup, s) for s in ICO_SIZES]
    ico_path = args.docs / "favicon.ico"
    layers[-1].save(ico_path, format="ICO", sizes=[(s, s) for s in ICO_SIZES],
                    append_images=layers)

    touch_path = assets / "apple-touch-icon.png"
    render(markup, 180, bg="#ffffff").convert("RGB").save(touch_path, optimize=True)

    # Android/PWA icons named in site.webmanifest. On white, since Android composites
    # home-screen icons on its own plate and a transparent one can vanish on a dark wall.
    pwa_paths = []
    for size in PWA_SIZES:
        p = assets / f"icon-{size}.png"
        render(markup, size, bg="#ffffff").convert("RGB").save(p, optimize=True)
        pwa_paths.append(p)

    for p in (svg_path, ico_path, touch_path, *pwa_paths):
        print(f"wrote {p.relative_to(args.docs)} ({p.stat().st_size/1024:.1f} KB)")


if __name__ == "__main__":
    main()
