#!/usr/bin/env python3
# NOTICE: This file was generated by an LLM coding system on 2026-08-15.
"""Build the JSON that docs/meta-analytics/ plots.

Two datasets, written to docs/meta-analytics/data/:

  links.json  every outbound http(s) link in the repo's source files, grouped
              by host. lychee does the extraction (`--dump`, which finds links
              without checking them), so the page counts exactly the links the
              weekly link-rot check watches.

  words.json  the word-frequency distribution of the repo's prose; the words
              used exactly once, twice, and three times; and the words this
              site over- and under-uses relative to general English.

Run from anywhere; paths are resolved against the repo root.

    python3 meta_analytics_source/build_data.py

Requires lychee on PATH for links.json. Without it the script still writes
words.json and leaves links.json alone, so a partial environment degrades to a
stale link section rather than a broken build.

The English baseline is downloaded on first run and cached; see
english_frequencies.md in this directory for its provenance and its caveats.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import urllib.request
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlsplit

REPO = Path(__file__).resolve().parent.parent
SOURCE_DIR = Path(__file__).resolve().parent
OUT_DIR = REPO / "docs" / "meta-analytics" / "data"
STOPWORDS_FILE = SOURCE_DIR / "stopwords.txt"

# ---------------------------------------------------------------------------
# Outbound links
# ---------------------------------------------------------------------------

# Same file globs and --exclude-path list as
# .github/workflows/link-check-external.yml, so the two agree on what "our
# links" means. docs/syllabus is excluded because it is generated from
# syllabus_source, which is already in the list; counting both double-counts
# every syllabus link.
#
# One deliberate difference: docs/meta-analytics is excluded here but not
# there. The page's own links are real published links and should still be
# checked for rot; they just must not appear in the counts the page reports
# about itself.
LYCHEE_INPUTS = [
    "README.md",
    "NOTES.md",
    "docs/**/*.md",
    "docs/**/*.qmd",
    "docs/**/*.html",
    "docs/_data/**/*.yml",
    "syllabus_source/**/*.md",
    "worksheets_source/**/*.md",
]

LYCHEE_EXCLUDE_PATHS = [
    "docs/ethics-in-data-science/book",
    "docs/ethics-in-data-science/assets/shared",
    "docs/slides/_libs",
    "docs/syllabus",
    "docs/_includes/masthead.html",
    "docs/assets/fonts",
    "docs/meta-analytics",
    # Local `jekyll serve` output. Git-ignored, so it never exists in CI, but
    # on a machine that has previewed the site it is a full second copy of
    # every page and silently doubles every count.
    "docs/_site",
    "docs/.jekyll-cache",
]

# Hosts that are this site itself, or the repo it lives in. They are not
# "outbound" in any interesting sense.
SELF_HOSTS = {
    "dodatascience.fun",
    "www.dodatascience.fun",
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
}


def build_links() -> dict | None:
    lychee = shutil.which("lychee")
    if lychee is None:
        print("lychee not found on PATH; skipping links.json", file=sys.stderr)
        return None

    args = [
        lychee,
        "--dump",
        "--no-progress",
        "--include-verbatim",
        "--scheme",
        "https",
        "--scheme",
        "http",
        "--root-dir",
        str(REPO / "docs"),
        "--exclude",
        "^/",
        # .lycheeignore lists hosts that block bots (LinkedIn, doi.org, …).
        # Those links are still links we published, so for counting purposes
        # the ignore file is deliberately overridden with an empty one.
        "--exclude-file",
        "/dev/null",
    ]
    for path in LYCHEE_EXCLUDE_PATHS:
        args += ["--exclude-path", path]
    args += LYCHEE_INPUTS

    proc = subprocess.run(args, cwd=REPO, capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stderr, file=sys.stderr)
        raise SystemExit(f"lychee --dump failed ({proc.returncode})")

    hosts: Counter[str] = Counter()
    urls: dict[str, set[str]] = {}
    total = 0
    for line in proc.stdout.splitlines():
        url = line.strip()
        if not url.startswith(("http://", "https://")):
            continue
        host = (urlsplit(url).hostname or "").lower()
        if not host or host in SELF_HOSTS:
            continue
        # A leading "www." is a subdomain nobody thinks of as part of the name.
        display = host[4:] if host.startswith("www.") else host
        hosts[display] += 1
        urls.setdefault(display, set()).add(url)
        total += 1

    domains = [
        {"domain": d, "count": c, "unique": len(urls[d])}
        for d, c in sorted(hosts.items(), key=lambda kv: (-kv[1], kv[0]))
    ]
    return {
        "generated": _now(),
        "total_links": total,
        "total_domains": len(domains),
        "total_unique_urls": sum(len(u) for u in urls.values()),
        "domains": domains,
    }


# ---------------------------------------------------------------------------
# Word frequencies
# ---------------------------------------------------------------------------

# Prose only. datasets/**/*.txt is raw data (the ICD-10-CM code tables alone
# are 21 MB of billing codes) and would drown the corpus, so only the dataset
# READMEs are read from there.
WORD_SUFFIXES = {".md", ".qmd", ".txt"}

WORD_EXCLUDE_PREFIXES = (
    "docs/meta-analytics/",  # this page, so it never counts itself
    # sandbox/ is the quarantine area for drafts, scraped material, and
    # generated reports that have not been reviewed. None of it is the site
    # speaking, so none of it is counted. (The link half of this script never
    # reads sandbox/ either -- it is not in LYCHEE_INPUTS above.)
    "sandbox/",
    # Image-attribution manifests: photographer names, license boilerplate, and
    # file names, not prose. _config.yml already excludes assets/**/*.md from
    # the Jekyll build, so the site itself does not treat these as content, and
    # neither should a count of what the site says. Leaving them in put
    # "helmick" -- a sculptor credited fourteen times in one SOURCES.md, almost
    # always inside a file name -- among the most over-used words on the site.
    "docs/assets/",
    "docs/ethics-in-data-science/assets/",
    "docs/.well-known/",  # security.txt, a machine-readable record
    "docs/ethics-in-data-science/book/",  # generated from the .md above it
    "docs/syllabus/",  # generated from syllabus_source
)

WORD_EXCLUDE_GLOBS = ("datasets/**/*.txt",)

FRONT_MATTER = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
FENCED_CODE = re.compile(r"^([ \t]*)(`{3,}|~{3,}).*?^\1\2.*$", re.DOTALL | re.MULTILINE)
INLINE_CODE = re.compile(r"`[^`\n]*`")
HTML_TAG = re.compile(r"<[^>]+>")
MATH = re.compile(r"\$\$.*?\$\$|\$[^$\n]*\$", re.DOTALL)
URL = re.compile(r"https?://\S+|www\.\S+")
LINK_TARGET = re.compile(r"\]\([^)]*\)")  # keep [link text], drop the target
IMAGE = re.compile(r"!\[[^\]]*\]")
ATTR_BRACES = re.compile(r"\{[^}\n]*\}")  # {.class #id}, Quarto/Jekyll/Liquid
DIV_FENCE = re.compile(r"^:::.*$", re.MULTILINE)  # Quarto ::: divs
CITATION = re.compile(r"@[A-Za-z][A-Za-z0-9_:.#$%&+?<>~/-]*")  # @pandoc-citekeys

# File names read as words once the punctuation is stripped: "orange-line-
# trace-og.png" would contribute orange, line, trace, og. Removed whole, before
# tokenizing, so a name only counts when someone actually wrote it in a
# sentence.
FILENAME = re.compile(
    r"[\w@./-]+\.(?:jpe?g|png|svg|gif|webp|pdf|csv|tsv|json|ya?ml|md|qmd|txt|html?"
    r"|css|js|py|r|ipynb|bib|zip|gz|woff2?|ttf|otf|ico|mp4|webm)\b",
    re.IGNORECASE,
)

# Letters and internal apostrophes. Numbers, code identifiers with digits or
# underscores, and bare punctuation are not words.
TOKEN = re.compile(r"[a-z]+(?:'[a-z]+)*")

# "a" and "i" are words; every other bare letter in this corpus is debris from
# an abbreviation ("e.g." -> e, g), a variable name, or a statistic (p, n).
REAL_ONE_LETTER_WORDS = {"a", "i"}


def tokenize(text: str):
    for token in TOKEN.findall(text):
        if len(token) == 1 and token not in REAL_ONE_LETTER_WORDS:
            continue
        yield token


def strip_markup(text: str) -> str:
    text = FRONT_MATTER.sub("", text)
    text = FENCED_CODE.sub(" ", text)
    text = MATH.sub(" ", text)
    text = INLINE_CODE.sub(" ", text)
    text = IMAGE.sub(" ", text)
    text = LINK_TARGET.sub(" ", text)
    text = URL.sub(" ", text)
    text = FILENAME.sub(" ", text)
    text = DIV_FENCE.sub(" ", text)
    text = ATTR_BRACES.sub(" ", text)
    text = HTML_TAG.sub(" ", text)
    text = CITATION.sub(" ", text)
    return text


def prose_files() -> list[Path]:
    listed = subprocess.run(
        ["git", "ls-files", "-z", "*.md", "*.qmd", "*.txt"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split("\0")

    files = []
    for rel in listed:
        if not rel:
            continue
        path = Path(rel)
        if path.suffix.lower() not in WORD_SUFFIXES:
            continue
        if rel.startswith(WORD_EXCLUDE_PREFIXES):
            continue
        if any(path.match(g) for g in WORD_EXCLUDE_GLOBS):
            continue
        files.append(path)
    return sorted(files)


def load_stopwords() -> set[str]:
    words = set()
    for line in STOPWORDS_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            words.add(line)
    return words


def build_words() -> dict:
    counts: Counter[str] = Counter()
    files = prose_files()
    for rel in files:
        text = (REPO / rel).read_text(encoding="utf-8", errors="replace").lower()
        counts.update(tokenize(strip_markup(text)))

    stopwords = load_stopwords()
    ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    total = sum(counts.values())

    # Words used exactly once, twice, and three times. "1" is the hapax
    # legomena; the site shows all three as separate drop-downs. The unfiltered
    # size of each tier is reported alongside, because dropping stop words from
    # the list changes the count the reader sees.
    rare: dict[str, list[str]] = {}
    rare_totals: dict[str, int] = {}
    for tier in (1, 2, 3):
        words_at_tier = [w for w, c in ranked if c == tier]
        rare_totals[str(tier)] = len(words_at_tier)
        rare[str(tier)] = sorted(w for w in words_at_tier if w not in stopwords)

    return {
        "generated": _now(),
        "total_words": total,
        "unique_words": len(counts),
        "file_count": len(files),
        # [word, count], already in descending-frequency order, so the page can
        # take rank straight from the array index.
        "words": [[w, c] for w, c in ranked],
        "rare": rare,
        "rare_totals": rare_totals,
        "unusual": build_unusual(counts, total),
    }


# ---------------------------------------------------------------------------
# Unusual words: this site's vocabulary against general English
# ---------------------------------------------------------------------------

# Peter Norvig's count_1w.txt -- the 1/3 million most frequent words, all
# lowercase, with counts, derived from the Google Web Trillion Word Corpus.
# See english_frequencies.md in this directory for full provenance.
#
# It is downloaded and cached rather than committed: the MIT license on
# Norvig's page covers his code, not the corpus data, which is Google's and is
# distributed by the Linguistic Data Consortium. That is the same reason
# datasets/musiclab-salganik-2006/ is git-ignored rather than redistributed.
ENGLISH_URL = "https://norvig.com/ngrams/count_1w.txt"
ENGLISH_CACHE = SOURCE_DIR / ".cache" / "count_1w.txt"

# A word must appear at least this many times here before it can be called
# over- or under-used. Below it the ratio is dominated by sampling noise: one
# stray occurrence of a rare word already looks like a thousandfold excess.
MIN_COUNT = 10

# How many words to show on each side.
UNUSUAL_N = 20


def load_english() -> tuple[dict[str, int], int]:
    if not ENGLISH_CACHE.exists():
        ENGLISH_CACHE.parent.mkdir(parents=True, exist_ok=True)
        print(f"downloading {ENGLISH_URL} ...", file=sys.stderr)
        with urllib.request.urlopen(ENGLISH_URL, timeout=60) as response:
            ENGLISH_CACHE.write_bytes(response.read())

    freqs: dict[str, int] = {}
    total = 0
    for line in ENGLISH_CACHE.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line:
            continue
        word, _, count = line.partition("\t")
        count = int(count)
        freqs[word] = count
        total += count
    return freqs, total


def build_unusual(counts: Counter[str], total: int) -> dict:
    """Rank words by how far their rate here departs from general English.

    The statistic is a plain rate ratio: this site's occurrences per million
    divided by English's. Above 1 the word is over-used, below 1 under-used,
    and the same number orders both lists, so the two halves of the section
    are the same measurement pointed in opposite directions.
    """
    english, english_total = load_english()

    rows = []
    for word, count in counts.items():
        if count < MIN_COUNT:
            continue
        # A word absent from the baseline has no expected rate to compare
        # against, so it cannot be ranked. This drops the vocabulary that
        # postdates the 2006 corpus -- github, llms, agentic -- which would
        # otherwise top the over-used list purely as an artifact of the
        # baseline's age.
        if word not in english:
            continue
        here = count / total * 1e6
        expected = english[word] / english_total * 1e6
        rows.append(
            {
                "word": word,
                "count": count,
                "actual": round(here, 2),
                "expected": round(expected, 3),
                "ratio": round(here / expected, 3),
            }
        )

    rows.sort(key=lambda r: r["ratio"])
    return {
        "min_count": MIN_COUNT,
        "compared": len(rows),
        "english_words": len(english),
        "english_total": english_total,
        "over": list(reversed(rows[-UNUSUAL_N:])),
        "under": rows[:UNUSUAL_N],
    }


# ---------------------------------------------------------------------------


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def write(name: str, payload: dict) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / name
    path.write_text(json.dumps(payload, separators=(",", ":")) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(REPO)} ({path.stat().st_size:,} bytes)")


def main() -> None:
    links = build_links()
    if links is not None:
        write("links.json", links)
        print(
            f"  {links['total_links']:,} links across "
            f"{links['total_domains']:,} domains"
        )

    words = build_words()
    write("words.json", words)
    print(
        f"  {words['total_words']:,} words, {words['unique_words']:,} unique, "
        f"from {words['file_count']} files"
    )
    tiers = ", ".join(f"{n}x{k}" for k, n in words["rare_totals"].items())
    print(f"  rare tiers (used once/twice/thrice): {tiers}")
    print(
        f"  unusual: {words['unusual']['compared']:,} words compared against "
        f"{words['unusual']['english_words']:,} English baseline words"
    )


if __name__ == "__main__":
    main()
