// NOTICE: This file was generated by an LLM coding system on 2026-09-15.
//
// Counts how often AI coding agents are opened inside a course assignment folder.
//
// The assignment folders ship hook configs (.claude/, .codex/, .cursor/, .github/hooks/)
// that POST one small JSON object here when an agent session starts. Nothing about the
// student is sent: no name, username, hostname, email, IP-derived field, file path, code,
// or prompt text. This Worker stores counters only — never a request body, never a log line.
//
//   POST /            {"assignment":"hw1","tool":"claude-code","event":"session-start","install":"<random id>"}
//   GET  /stats.json  {"generated":"…","total":N,"installs":N,"tools":{…},"assignments":{…},"days":{…}}
//
// meta_analytics_source/build_data.py reads /stats.json at site build time and writes
// docs/meta-analytics/data/ai-usage.json, which the Meta-Analytics page plots.

const FIELD = /^[a-z0-9][a-z0-9-]{0,31}$/; // keeps junk out of KV key names
const INSTALL = /^[A-Za-z0-9-]{4,40}$/;
const INSTALL_TTL = 60 * 60 * 24 * 365; // a distinct folder is counted once per year

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

async function bump(kv, key, by = 1) {
  // KV is eventually consistent, so two writes in the same instant can lose one.
  // At classroom volume that is a rounding error; exact counts would need a
  // Durable Object. See README.md.
  const current = parseInt((await kv.get(key)) || "0", 10) || 0;
  await kv.put(key, String(current + by));
}

async function record(request, env) {
  let body;
  try {
    body = await request.json();
  } catch {
    return new Response("bad json", { status: 400, headers: CORS });
  }

  const tool = String(body.tool || "");
  const assignment = String(body.assignment || "");
  const event = String(body.event || "");
  const install = String(body.install || "");

  if (!FIELD.test(tool) || !FIELD.test(assignment) || !FIELD.test(event)) {
    return new Response("bad fields", { status: 400, headers: CORS });
  }
  if (event !== "session-start") {
    return new Response(null, { status: 204, headers: CORS }); // only starts are counted
  }

  await bump(env.COUNTS, "total");
  await bump(env.COUNTS, `tool:${tool}`);
  await bump(env.COUNTS, `assignment:${assignment}`);
  await bump(env.COUNTS, `day:${new Date().toISOString().slice(0, 10)}`);

  // Distinct folders, so one student running twenty sessions counts once. The id is
  // random and generated in the student's folder; it identifies a copy of the
  // assignment, not a person, and nothing here can map it back to one.
  //
  // Two separate "seen" keys, because the two counters answer different questions.
  // The headline `installs` is folder-wide: how many copies of the assignment ran
  // any agent at all. `installs:tool:<tool>` is per tool: how many copies ran THIS
  // tool. Sharing one folder-wide key between them let whichever tool happened to
  // POST first claim the folder, and every other tool a student opened in the same
  // folder scored zero — so per-tool adoption read far lower than it was.
  if (INSTALL.test(install)) {
    const seenAny = `seen:${assignment}:${install}`;
    if ((await env.COUNTS.get(seenAny)) === null) {
      await env.COUNTS.put(seenAny, "1", { expirationTtl: INSTALL_TTL });
      await bump(env.COUNTS, "installs");
    }

    const seenTool = `seen:${assignment}:${tool}:${install}`;
    if ((await env.COUNTS.get(seenTool)) === null) {
      await env.COUNTS.put(seenTool, "1", { expirationTtl: INSTALL_TTL });
      await bump(env.COUNTS, `installs:tool:${tool}`);
    }
  }

  return new Response(null, { status: 204, headers: CORS });
}

async function stats(env) {
  const out = { generated: new Date().toISOString(), total: 0, installs: 0, tools: {}, assignments: {}, days: {} };
  let cursor;
  do {
    const page = await env.COUNTS.list({ cursor });
    for (const { name } of page.keys) {
      if (name.startsWith("seen:")) continue;
      const value = parseInt((await env.COUNTS.get(name)) || "0", 10) || 0;
      if (name === "total") out.total = value;
      else if (name === "installs") out.installs = value;
      else if (name.startsWith("installs:tool:")) {
        const tool = name.slice("installs:tool:".length);
        out.tools[tool] = Object.assign({ sessions: 0, installs: 0 }, out.tools[tool], { installs: value });
      } else if (name.startsWith("tool:")) {
        const tool = name.slice("tool:".length);
        out.tools[tool] = Object.assign({ sessions: 0, installs: 0 }, out.tools[tool], { sessions: value });
      } else if (name.startsWith("assignment:")) out.assignments[name.slice("assignment:".length)] = value;
      else if (name.startsWith("day:")) out.days[name.slice("day:".length)] = value;
    }
    cursor = page.list_complete ? null : page.cursor;
  } while (cursor);

  return new Response(JSON.stringify(out), {
    headers: { ...CORS, "Content-Type": "application/json", "Cache-Control": "public, max-age=300" },
  });
}

export default {
  async fetch(request, env) {
    const { pathname } = new URL(request.url);
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
    if (request.method === "POST" && pathname === "/") return record(request, env);
    if (request.method === "GET" && pathname === "/stats.json") return stats(env);
    return new Response("not found", { status: 404, headers: CORS });
  },
};
