#!/usr/bin/env python3
"""Generate the group-project checkpoint pages under docs/ from the .md files next to this file.

NOTICE: this file was largely written by an LLM (Claude Code).

Each checkpoint is one file here, named `NN-slug.md`, with frontmatter (see
README.md) and a markdown body whose first `# Heading` is the title.

    python3 project/build-project-data.py

Outputs (regenerated from scratch, never hand-edited):

  - docs/project/<slug>.md    one Jekyll page per checkpoint, at /project/<slug>/

Unlike exercises/build-exercises-data.py, this does not convert the markdown
itself: there is no starter code and no notebook to render here, so the body is
passed through to Jekyll and kramdown renders it. That keeps this script to the
one job the exercises build cannot avoid -- turning source frontmatter into page
frontmatter.

A checkpoint whose frontmatter says `draft: true` is skipped, so an unfinished
stub is not published while the rest of the list is.

docs/project/index.html is the hand-written index and is NOT generated.
"""
import re
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
DOCS_DIR = PROJECT_DIR.parent / "docs"
PAGES_DIR = DOCS_DIR / "project"

GENERATED_NOTE = "Generated by project/build-project-data.py -- do not edit by hand."

AI_POLICIES = {"double-red", "red-yellow", "double-yellow", "tk"}

FILE_RE = re.compile(r'^(\d+)-(.+)\.md$')
TITLE_RE = re.compile(r'^#\s+(.+?)\s*$', re.MULTILINE)


def parse_frontmatter(text):
    """Minimal `key: value` frontmatter. Values are single-line strings."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    meta = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if sep:
            meta[key.strip()] = value.strip()
    return meta, text[end + 4:].lstrip("\n")


def yaml_quote(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    sources = sorted(p for p in PROJECT_DIR.glob("*.md") if FILE_RE.match(p.name))
    if not sources:
        sys.exit(f"No NN-slug.md checkpoints found in {PROJECT_DIR}")

    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    for stale in PAGES_DIR.glob("*.md"):
        stale.unlink()

    built = 0
    for source in sources:
        number, slug = FILE_RE.match(source.name).groups()
        meta, body = parse_frontmatter(source.read_text())

        if meta.get("draft", "").lower() == "true":
            continue

        title_match = TITLE_RE.search(body)
        if not title_match:
            sys.exit(f"{source.name}: no `# Title` heading in the body")
        title = title_match.group(1)
        body = (body[:title_match.start()] + body[title_match.end():]).lstrip("\n")

        policy = meta.get("ai_policy", "tk")
        if policy not in AI_POLICIES:
            sys.exit(f"{source.name}: unknown ai_policy {policy!r} (expected one of {sorted(AI_POLICIES)})")

        front = [
            "---",
            f"# {GENERATED_NOTE}",
            f"# Source: project/{source.name}",
            "layout: project-checkpoint",
            # Same stylesheet as the coding exercises: the checkpoint layout
            # reuses their classes (.exercise-meta and friends), so without this
            # the header strip renders unstyled.
            "extra_css:",
            "  - /css/exercises.css",
            f"title: {yaml_quote(title)}",
            f"number: {int(number)}",
            f"slug: {slug}",
            f"summary: {yaml_quote(meta.get('summary', ''))}",
            f"topic: {yaml_quote(meta.get('topic', ''))}",
            f"due: {yaml_quote(meta.get('due', ''))}",
            f"ai_policy: {policy}",
            f"permalink: /project/{slug}/",
            "nav: project",
            "---",
            "",
        ]
        (PAGES_DIR / f"{slug}.md").write_text("\n".join(front) + body)
        built += 1

    print(f"Wrote {built} checkpoint page(s) to {PAGES_DIR} ({len(sources) - built} draft(s) skipped)")


if __name__ == "__main__":
    main()
