#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM (Claude) and has not been hand-verified.

Remix of Zone_of_proximal_development.svg (Dcoetzee, CC0 -- see SOURCES.md) in
this repo's house style, as a four-variant set for building the idea up on a
slide:

    v0  the three bands, unlabelled
    v1  + innermost  -- learner can do unaided (too easy)
    v2  + outermost  -- learner cannot do (too difficult)
    v3  + middle     -- the zone of proximal development
    v4  the middle band ringed, for "this is the point"

Labels accumulate, so v3 carries all three. The order brackets the two extremes
first and only then names the zone between them, which is the order the slide's
bullets go in. The bands themselves never change, which is what lets the labels
stay legible once they are all up; v4 adds emphasis rather than taking any away,
a white line inset in the zone like a track running the Loop.

Departures from the original, all deliberate:

  - the three nested circles become three nested rounded rectangles. The repo's
    running motif is the Orange Line, and the elevated Loop is the one piece of
    that map already shaped like a ring, so it is the natural stand-in for a
    ring diagram. Corner radius is the Loop's own -- 5.7% of the width, read off
    ../orange-line/loop-icon.svg -- and scales with each rectangle, so all three
    read as the same shape at three sizes.
  - the frame is a portrait golden rectangle and the outermost band fills it, so
    the band proportions are golden rather than the Loop's 262:309. The Loop
    signature is carried by the corners instead; a 0.848 shape cannot fill a
    0.618 frame, and the frame is the constraint that shows.
  - the blue-violet ramp becomes three steps of the brand orange, keeping the
    original's light-outside / dark-inside ordering so the figure still reads
    the same way. All three steps are dark enough to carry white type.
  - every label is white with a black drop shadow, so one type treatment works
    on all three bands and in the dimmed state.

Two outputs, because a slide and a standalone figure want different things:

  - `zpd-loop-v0.svg` … `v4.svg` stand alone, fonts embedded as base64 woff2.
  - `zpd-loop-stack.md` is a Quarto include holding the same five frames as
    *inline* SVG, for `../../slides/week1.qmd`. Reveal scales `.slides` with a
    CSS transform, and an <img> is rasterised at its layout size before that
    transform is applied, so an <img> figure goes soft while the slide's own
    headings stay sharp. Inline SVG renders through the same vector path as
    that heading. The inline copies carry no @font-face: they inherit the
    deck's self-hosted Libre Franklin, and their filter ids are suffixed so the
    five frames can share one document.

Labels are names only. The glosses moved to the slide's bullets -- at the size
this figure is shown, a parenthetical set small enough to fit was unreadable
whether or not it was crisp.
"""

from __future__ import annotations

import base64
from pathlib import Path
from xml.sax.saxutils import escape


PHI = (1 + 5**0.5) / 2
WIDTH = 618
HEIGHT = 1000

OUT_DIR = Path(__file__).resolve().parent

PAGE = "#FFFFFF"
LABEL = "#FFFFFF"

# Three steps down the brand orange. $orange on the largest field, $orange-dark
# in the middle, one further step for the core.
BAND_FILLS = ["#F9461C", "#C83214", "#8E2410"]

BODY_FONT = "Libre Franklin"
FONTS = [(BODY_FONT, "LibreFranklin.woff2", "../fonts/libre-franklin")]

# --- layout ---------------------------------------------------------------
MARGIN = 26
OUTER_W = WIDTH - 2 * MARGIN  # 566
OUTER_H = OUTER_W * PHI  # the outermost band is itself a golden portrait rect
CENTER_X = WIDTH / 2
CENTER_Y = HEIGHT / 2

LOOP_CORNER = 15 / 262  # corner radius as a fraction of width, from the Loop

# The original's three radii -- 337.9, 230.7, 131.4 -- as fractions of the
# outermost, so the band widths carry over from the figure being remixed.
SCALES = [1.000, 0.683, 0.389]

# The .figure-aside layout caps a figure at 430px tall, so this 618-wide canvas
# is shown about 266px wide. A name set at 36 lands at roughly 15 CSS px there,
# which is readable from the back of a room; the old 22 landed at 9.
NAME_SIZE = 36
LINE_STEP = 44

# (band index, lines) -- ordered v1, v2, v3: core, then outermost, then the zone
# between them. Names wrap to fit their own box, which is why the narrow core
# takes three lines and the full-width outer band takes one.
VARIANTS = [
    (2, ["Learner", "can do", "unaided"]),
    (0, ["Learner cannot do"]),
    (1, ["Zone of Proximal", "Development"]),
]

# $figure-height-aside in ../../slides/shared/theme/uic-orange-reveal.scss. The
# theme's cap is an `img.figure` rule, which an inline <svg> does not match, so
# the height is set here instead -- keep the two in step.
ASIDE_HEIGHT = 430

ZONE = 1  # the band v4 rings
RING_INSET = 11
RING_WIDTH = 4


def band_box(index: int) -> tuple[float, float, float, float, float]:
    """(x, y, w, h, rx) for one nested rounded rectangle."""
    w = OUTER_W * SCALES[index]
    h = OUTER_H * SCALES[index]
    return CENTER_X - w / 2, CENTER_Y - h / 2, w, h, w * LOOP_CORNER


def label_center(index: int) -> float:
    """Where a band's label sits: the strip above the next band in, or, for the
    core, the middle of the core itself."""
    top = band_box(index)[1]
    if index == len(SCALES) - 1:
        return CENTER_Y
    return (top + band_box(index + 1)[1]) / 2


def draw_bands() -> str:
    out = []
    for index, fill in enumerate(BAND_FILLS):
        x, y, w, h, rx = band_box(index)
        out.append(
            f'  <rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
            f'rx="{rx:.1f}" fill="{fill}"/>'
        )
    return "\n".join(out)


def draw_label(index: int, lines: list[str], filter_id: str) -> str:
    """One type treatment for every band: white, bold, over a black shadow."""
    block = LINE_STEP * (len(lines) - 1)
    first = label_center(index) - block / 2 + NAME_SIZE * 0.35

    out = [f'  <g filter="url(#{filter_id})">']
    for offset, line in enumerate(lines):
        out.append(
            f'    <text x="{CENTER_X:.1f}" y="{first + offset * LINE_STEP:.1f}" '
            f'text-anchor="middle" font-family="{BODY_FONT}" font-size="{NAME_SIZE}" '
            f'font-weight="700" fill="{LABEL}">{escape(line)}</text>'
        )
    out.append("  </g>")
    return "\n".join(out)


def font_faces() -> str:
    faces = []
    for family, filename, upstream in FONTS:
        encoded = base64.b64encode((OUT_DIR / upstream / filename).read_bytes()).decode("ascii")
        faces.append(
            f"    @font-face {{\n"
            f"      font-family: '{family}';\n"
            f"      src: url('data:font/woff2;base64,{encoded}') format('woff2');\n"
            f"      font-weight: 100 900;\n"
            f"      font-style: normal;\n"
            f"    }}"
        )
    return "\n".join(faces)


def draw_ring() -> str:
    """A white line inset in the zone -- a track running the Loop, and the one
    mark v4 adds."""
    x, y, w, h, rx = band_box(ZONE)
    return (
        f'  <rect x="{x + RING_INSET:.1f}" y="{y + RING_INSET:.1f}" '
        f'width="{w - 2 * RING_INSET:.1f}" height="{h - 2 * RING_INSET:.1f}" '
        f'rx="{rx - RING_INSET:.1f}" fill="none" stroke="{LABEL}" '
        f'stroke-width="{RING_WIDTH}"/>\n'
    )


def draw_defs(filter_id: str) -> str:
    return (
        f'  <defs>\n'
        f'    <filter id="{filter_id}" x="-25%" y="-40%" width="150%" height="180%">\n'
        f'      <feDropShadow dx="0" dy="2" stdDeviation="3" flood-color="#000000" '
        f'flood-opacity="0.9"/>\n'
        f"    </filter>\n"
        f"  </defs>"
    )


def draw_body(number: int, filter_id: str) -> str:
    """Everything inside the <svg>, shared by both outputs."""
    shown = min(number, len(VARIANTS))
    labels = (draw_ring() if number > len(VARIANTS) else "") + "".join(
        draw_label(index, lines, filter_id) + "\n"
        for index, lines in VARIANTS[:shown]
    )
    return f"{draw_defs(filter_id)}\n{draw_bands()}\n{labels}"


def make_standalone(number: int, description: str) -> str:
    """A figure that stands on its own: sized in px, fonts embedded."""
    return f"""<svg width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="{escape(description)}">
  <rect width="{WIDTH}" height="{HEIGHT}" fill="{PAGE}"/>
  <style>
{font_faces()}
  </style>
{draw_body(number, "zpd-label-shadow")}</svg>
"""


def make_inline(number: int, description: str) -> str:
    """A figure for the deck: no px size, no @font-face -- it inherits the
    slide's Libre Franklin -- and a filter id unique within the page."""
    return (
        f'<svg class="zpd-loop" viewBox="0 0 {WIDTH} {HEIGHT}" '
        f'style="height:{ASIDE_HEIGHT}px;width:auto;display:block;margin-inline:auto" '
        f'fill="none" xmlns="http://www.w3.org/2000/svg" role="img" '
        f'aria-label="{escape(description)}">\n'
        f'  <rect width="{WIDTH}" height="{HEIGHT}" fill="{PAGE}"/>\n'
        f'{draw_body(number, f"zpd-label-shadow-{number}")}</svg>'
    )


# How each frame enters and leaves the reveal.js build.
FRAGMENTS = [
    "{.fragment .fade-out fragment-index=1}",
    "{.fragment .fade-in-then-out fragment-index=1}",
    "{.fragment .fade-in-then-out fragment-index=2}",
    "{.fragment .fade-in-then-out fragment-index=3}",
    "{.fragment fragment-index=4}",
]


def make_include() -> str:
    """The .r-stack, as a Quarto include, so the slide stays markup and this
    stays the source of truth."""
    frames = "\n\n".join(
        f"::: {fence}\n```{{=html}}\n{make_inline(number, DESCRIPTIONS[number])}\n```\n:::"
        for number, fence in enumerate(FRAGMENTS)
    )
    return (
        "<!-- Generated by assets/learning-theory/make_zpd_loop_figure.py.\n"
        "     Do not hand-edit; re-run the script instead. -->\n\n"
        f"::: {{.r-stack}}\n\n{frames}\n\n:::\n"
    )


BASE = "Three nested rounded rectangles in three steps of orange"
CORE = "the innermost is labelled 'Learner can do unaided'"
EDGE = "the outermost 'Learner cannot do'"
ZONE_LABEL = "the middle band 'Zone of Proximal Development'"
DESCRIPTIONS = [
    f"{BASE}, unlabelled",
    f"{BASE}; {CORE}",
    f"{BASE}; {CORE}, and {EDGE}",
    f"{BASE}; {CORE}, {EDGE}, and {ZONE_LABEL}",
    f"{BASE}; {CORE}, {EDGE}, and {ZONE_LABEL}, which is ringed in white to mark "
    "it as the target",
]


def main() -> None:
    for number in range(len(FRAGMENTS)):
        out = OUT_DIR / f"zpd-loop-v{number}.svg"
        out.write_text(make_standalone(number, DESCRIPTIONS[number]), encoding="utf-8")
        print(f"wrote {out.relative_to(OUT_DIR.parent)}")

    include = OUT_DIR / "zpd-loop-stack.md"
    include.write_text(make_include(), encoding="utf-8")
    print(f"wrote {include.relative_to(OUT_DIR.parent)}")


if __name__ == "__main__":
    main()
