#!/usr/bin/env python3
"""Generate the exercises pages under docs/ from the folders next to this file.

NOTICE: this file was largely written by an LLM (Claude Code).

Each exercise is one folder here, named `NN-slug`, containing:

    exercise.md      the prompt (frontmatter + markdown; see README.md)
    starter/         optional starter code, copied to the site as-is

The .md files are the source of truth. Run after editing one:

    python3 exercises/build-exercises-data.py

Outputs (all regenerated from scratch, never hand-edited):

  - docs/_data/exercises.yml            metadata for the index page cards
  - docs/exercises/<slug>.html          one Jekyll page per exercise
  - docs/exercises/<slug>/starter/...   copies of the starter files
  - docs/_includes/exercises-about.html the "Read more" blurb on the index

Unlike the dilemmas build in the ethics repo, the index is rendered by Liquid
from the generated _data file rather than by JavaScript from a generated .js:
with five exercises there is nothing to search or shuffle, and the schedule
page already establishes _data/ as where this site keeps its spines.
"""
import base64
import html
import json
import re
import shutil
from pathlib import Path

EXERCISES_DIR = Path(__file__).resolve().parent
DOCS_DIR = EXERCISES_DIR.parent / "docs"
PAGES_DIR = DOCS_DIR / "exercises"
DATA_OUTPUT = DOCS_DIR / "_data" / "exercises.yml"
ABOUT_SOURCE = EXERCISES_DIR / "exercises-about.md"
ABOUT_OUTPUT = DOCS_DIR / "_includes" / "exercises-about.html"

GENERATED_NOTE = "Generated by exercises/build-exercises-data.py -- do not edit by hand."

# The three AI/LLM phases of the course, named after CTA rail signal aspects
# (syllabus + FAQ). An exercise names one in its frontmatter; the layout renders
# the matching rulebook drawing. Labels and drawings live in
# docs/_data/ai_signals.yml -- keep the two in step. "tk" means not decided yet.
AI_POLICIES = {"double-red", "red-yellow", "double-yellow", "tk"}

FOLDER_RE = re.compile(r'^(\d+)-(.+)$')

# Editor and OS droppings that live inside starter/ but are not starter code.
# Jupyter writes .ipynb_checkpoints/ the moment a notebook is opened, so this is
# the normal case, not an edge case.
STARTER_IGNORE = shutil.ignore_patterns(
    ".gitkeep", ".DS_Store", ".ipynb_checkpoints", "__pycache__", "*.pyc")
IGNORED_DIRS = {".ipynb_checkpoints", "__pycache__"}


def is_starter_file(path, root):
    if path.name in (".gitkeep", ".DS_Store") or path.suffix == ".pyc":
        return False
    return not IGNORED_DIRS.intersection(path.relative_to(root).parts)


# ── Frontmatter ──────────────────────────────────────────────────────────────

def parse_frontmatter(text):
    """Minimal `key: value` frontmatter. Values are single-line strings."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    meta = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip()
    return meta, text[end + 4:].lstrip("\n")


# ── Markdown -> HTML ─────────────────────────────────────────────────────────
# A deliberately small subset: headings, paragraphs, lists, fenced and inline
# code, blockquotes, ---, links, bold, italics. Enough for a coding prompt.

def convert_inline(text):
    """Inline markdown -> HTML. `text` must already be HTML-escaped."""
    tokens = []

    def stash(fragment):
        tokens.append(fragment)
        return f"\x00{len(tokens) - 1}\x00"

    def emphasize(text):
        text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
        text = re.sub(r'\*([^*\n]+)\*', r'<em>\1</em>', text)
        return re.sub(r'(?<![\w\x00])_([^_\n]+)_(?![\w\x00])', r'<em>\1</em>', text)

    # Code spans are stashed first so nothing inside them is emphasized.
    text = re.sub(r'`([^`]+)`', lambda m: stash(f"<code>{m.group(1)}</code>"), text)
    text = re.sub(r'\[([^\]]+)\]\(([^)\s]+)\)',
                  lambda m: stash(f'<a href="{m.group(2)}">{emphasize(m.group(1))}</a>'),
                  text)
    text = emphasize(text)
    return re.sub(r'\x00(\d+)\x00', lambda m: tokens[int(m.group(1))], text)


def convert_markdown(text):
    out = []
    paragraph = []
    list_tag = None

    def flush_paragraph():
        if paragraph:
            out.append("<p>" + "<br>\n".join(paragraph) + "</p>")
            paragraph.clear()

    def close_list():
        nonlocal list_tag
        if list_tag:
            out.append(f"</{list_tag}>")
            list_tag = None

    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        stripped = line.strip()
        i += 1

        fence = re.match(r'```\s*([\w+-]*)', stripped)
        if fence:
            flush_paragraph()
            close_list()
            body = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                body.append(lines[i])
                i += 1
            i += 1  # closing fence
            lang = fence.group(1)
            attr = f' class="language-{lang}"' if lang else ""
            out.append(f"<pre><code{attr}>"
                       + html.escape("\n".join(body))
                       + "</code></pre>")
            continue

        if not stripped:
            flush_paragraph()
            close_list()
            continue

        if re.fullmatch(r'-{3,}', stripped):
            flush_paragraph()
            close_list()
            out.append("<hr>")
            continue

        heading = re.match(r'(#{1,6})\s+(.*)', stripped)
        if heading:
            flush_paragraph()
            close_list()
            level = len(heading.group(1))
            out.append(f"<h{level}>{convert_inline(html.escape(heading.group(2)))}</h{level}>")
            continue

        quote = re.match(r'>\s?(.*)', stripped)
        if quote:
            flush_paragraph()
            close_list()
            out.append(f"<blockquote><p>{convert_inline(html.escape(quote.group(1)))}</p></blockquote>")
            continue

        ordered = re.match(r'\d+\.\s+(.*)', stripped)
        unordered = re.match(r'[*-]\s+(.*)', stripped)
        if ordered or unordered:
            flush_paragraph()
            tag = "ol" if ordered else "ul"
            if list_tag != tag:
                close_list()
                out.append(f"<{tag}>")
                list_tag = tag
            item = (ordered or unordered).group(1)
            out.append(f"<li>{convert_inline(html.escape(item))}</li>")
            continue

        close_list()
        paragraph.append(convert_inline(html.escape(stripped)))

    flush_paragraph()
    close_list()
    return "\n".join(out)


# ── Notebook -> HTML preview ─────────────────────────────────────────────────
# Rendered here rather than linked out, so a student can read the starter before
# downloading it and without a Colab/nbviewer round trip. Stdlib only: a .ipynb
# is JSON, and the markdown cells go through the same converter as the prompt.

def render_output(output):
    """One cell output. Stub notebooks have none; real ones will."""
    kind = output.get("output_type")
    if kind == "stream":
        text = "".join(output.get("text", []))
        return f'<pre class="nb-stream">{html.escape(text)}</pre>'
    if kind == "error":
        text = "\n".join(output.get("traceback", []))
        # tracebacks carry ANSI colour codes; strip them rather than render them
        text = re.sub(r"\x1b\[[0-9;]*m", "", text)
        return f'<pre class="nb-error">{html.escape(text)}</pre>'
    data = output.get("data", {})
    if "image/png" in data:
        png = data["image/png"]
        if isinstance(png, list):
            png = "".join(png)
        # already base64 in the .ipynb; normalised so the data: URI is one line
        png = base64.b64encode(base64.b64decode(png)).decode("ascii")
        return f'<img class="nb-image" src="data:image/png;base64,{png}" alt="Output image">'
    if "text/plain" in data:
        text = "".join(data["text/plain"])
        return f'<pre class="nb-result">{html.escape(text)}</pre>'
    return ""


def render_notebook(path):
    """A .ipynb as a static, self-contained preview. Returns "" if unreadable,
    since a malformed starter should not take the whole site build down."""
    try:
        nb = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as err:
        print(f"  ! skipping preview for {path.name}: {err}")
        return ""

    lang = (nb.get("metadata", {}).get("language_info", {}).get("name") or "python")
    out = []
    for cell in nb.get("cells", []):
        source = "".join(cell.get("source", []))
        if not source.strip():
            continue
        if cell.get("cell_type") == "markdown":
            out.append(f'<div class="nb-cell nb-markdown">{convert_markdown(source)}</div>')
            continue
        if cell.get("cell_type") != "code":
            continue
        body = [f'<pre class="nb-source"><code class="language-{lang}">'
                f'{html.escape(source.rstrip())}</code></pre>']
        for output in cell.get("outputs", []):
            rendered = render_output(output)
            if rendered:
                body.append(rendered)
        out.append('<div class="nb-cell nb-code">' + "\n".join(body) + "</div>")
    return "\n".join(out)


# ── Build ────────────────────────────────────────────────────────────────────

def read_exercise(folder):
    match = FOLDER_RE.match(folder.name)
    if not match:
        raise SystemExit(f"Exercise folder must be named NN-slug: {folder.name}")
    source = folder / "exercise.md"
    if not source.exists():
        raise SystemExit(f"Missing {source.relative_to(EXERCISES_DIR.parent)}")

    meta, body = parse_frontmatter(source.read_text(encoding="utf-8"))
    if not meta.get("summary"):
        raise SystemExit(f"Missing 'summary:' frontmatter in {folder.name}/exercise.md")
    policy = meta.get("ai_policy", "tk").lower()
    if policy not in AI_POLICIES:
        raise SystemExit(f"{folder.name}: ai_policy must be one of {sorted(AI_POLICIES)}")

    title_match = re.search(r'^#\s+(.*)$', body, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else folder.name
    if title_match:
        body = body[:title_match.start()] + body[title_match.end():]

    starter_dir = folder / "starter"
    starter_files = sorted(
        p.relative_to(starter_dir).as_posix()
        for p in starter_dir.rglob("*")
        if p.is_file() and is_starter_file(p, starter_dir)
    ) if starter_dir.is_dir() else []

    return {
        "slug": folder.name,
        "number": int(match.group(1)),
        "title": title,
        "summary": meta["summary"],
        "topic": meta.get("topic", "TK"),
        "due": meta.get("due", "TK"),
        "ai_policy": policy,
        "starter": starter_files,
        "html": convert_markdown(body.strip()),
        "preview": {
            name: render_notebook(starter_dir / name)
            for name in starter_files if name.endswith(".ipynb")
        },
        "starter_source": starter_dir,
    }


def copy_starters(exercise):
    """Copy starter/ into docs/exercises/<slug>/starter/, replacing what's there."""
    dest = PAGES_DIR / exercise["slug"] / "starter"
    if dest.exists():
        shutil.rmtree(dest)
    if not exercise["starter"]:
        return
    shutil.copytree(exercise["starter_source"], dest, ignore=STARTER_IGNORE)
    print(f"copied {len(exercise['starter'])} starter file(s) for {exercise['slug']}")


def write_data(exercises):
    """Metadata for the index page. YAML is emitted as JSON, which it is a
    superset of, so no quoting rules have to be reimplemented here."""
    payload = [
        {k: e[k] for k in
         ("slug", "number", "title", "summary", "topic", "due", "ai_policy", "starter")}
        for e in exercises
    ]
    DATA_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DATA_OUTPUT.write_text(
        f"# {GENERATED_NOTE}\n"
        + json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {DATA_OUTPUT.relative_to(DOCS_DIR.parent)} ({len(payload)} exercises)")


def write_pages(exercises):
    """One Jekyll page per exercise, served at /exercises/<slug>/."""
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    for stale in PAGES_DIR.glob("*.html"):
        stale.unlink()

    for e in exercises:
        starters = "".join(f"\n  - {json.dumps(name)}" for name in e["starter"])
        front = (
            "---\n"
            "layout: exercise\n"
            f"permalink: /exercises/{e['slug']}/\n"
            f"number: {e['number']}\n"
            f"title: {json.dumps(e['title'], ensure_ascii=False)}\n"
            f"summary: {json.dumps(e['summary'], ensure_ascii=False)}\n"
            f"topic: {json.dumps(e['topic'], ensure_ascii=False)}\n"
            f"due: {json.dumps(e['due'], ensure_ascii=False)}\n"
            f"ai_policy: {e['ai_policy']}\n"
            + (f"starter:{starters}\n" if e["starter"] else "")
            + "---\n"
            f"<!-- {GENERATED_NOTE} -->\n"
        )
        content = e["html"]
        for name, preview in e["preview"].items():
            if not preview:
                continue
            content += (
                '\n<section class="notebook-preview">\n'
                '<details>\n'
                f'<summary>Preview <code>{name}</code></summary>\n'
                '<div class="nb">\n' + preview + '\n</div>\n'
                '</details>\n</section>'
            )
        (PAGES_DIR / f"{e['slug']}.html").write_text(front + content + "\n",
                                                     encoding="utf-8")
    print(f"wrote {len(exercises)} pages to {PAGES_DIR.relative_to(DOCS_DIR.parent)}/")


def write_about():
    _, body = parse_frontmatter(ABOUT_SOURCE.read_text(encoding="utf-8"))
    ABOUT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    ABOUT_OUTPUT.write_text(
        f"<!-- Generated from exercises/exercises-about.md -- do not edit by hand. -->\n"
        + convert_markdown(body.strip()) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {ABOUT_OUTPUT.relative_to(DOCS_DIR.parent)}")


def main():
    folders = sorted(p for p in EXERCISES_DIR.iterdir()
                     if p.is_dir() and FOLDER_RE.match(p.name))
    if not folders:
        raise SystemExit("No exercise folders found (expected NN-slug directories).")

    exercises = [read_exercise(f) for f in folders]
    numbers = [e["number"] for e in exercises]
    if len(set(numbers)) != len(numbers):
        raise SystemExit(f"Duplicate exercise numbers: {numbers}")

    for e in exercises:
        copy_starters(e)
    write_data(exercises)
    write_pages(exercises)
    write_about()


if __name__ == "__main__":
    main()
