project:
  type: book
  output-dir: book

book:
  title: "Ethics in Data Science"
  subtitle: "Social and moral considerations for responsible data scientists"
  author: "Jack Bandy"
  date: today
  repo-url: https://github.com/jackbandy/data-science-fun
  repo-branch: main
  repo-subdir: docs/ethics-in-data-science
  repo-actions: [source]
  chapters:
    - index.md
    - 01-working-toward-wisdom.md
    - 02-ethics-in-asking-questions.md
    - 03-ethics-in-obtaining-data.md
    - 04-ethics-in-understanding.md
    - 05-ethics-in-reporting-decisions-solutions.md
    - 06-conclusions.md
  appendices:
    - 07-glossary.md
    - 08-ethical-theories.md
    - 09-case-studies.md
  page-footer:
    left: |
      <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
        <img alt="Creative Commons BY-NC-SA" src="assets/cc-by-nc-sa.svg">
      </a>

bibliography: references.bib
license: "CC BY-NC-SA"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
