#!/usr/bin/env bash
# Generate TABLE.md, a table of contents for the mini-book.
#
# Reads the chapter/appendix list from _quarto.yml and pulls the chapter titles
# and section headings out of each source file.
#
# Usage: ./generate_toc.sh [depth] [output]
#   depth   deepest heading level to include (default: 2)
#   output  output file, relative to this directory (default: TABLE.md)

set -euo pipefail

# Byte-wise locale: macOS awk chokes on multibyte input (en dashes in headings).
export LC_ALL=C

BOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPTH="${1:-2}"
OUTPUT="${2:-TABLE.md}"

cd "$BOOK_DIR"

# Pull a scalar out of the top-level `book:` block of _quarto.yml.
book_field() {
  awk -v key="$1" '
    /^book:/         { inbook = 1; next }
    /^[^[:space:]#]/ { inbook = 0 }
    inbook && $0 ~ "^  " key ":" {
      sub("^  " key ":[[:space:]]*", "")
      gsub(/^"|"$/, "")
      print
      exit
    }
  ' _quarto.yml
}

# List the .md files under a `book:` sub-key (chapters or appendices).
book_files() {
  awk -v key="$1" '
    /^book:/         { inbook = 1; next }
    /^[^[:space:]#]/ { inbook = 0 }
    inbook && $0 ~ "^  " key ":" { inlist = 1; next }
    inlist && $0 ~ /^  [a-zA-Z_-]+:/ { inlist = 0 }
    inlist && $0 ~ /^[[:space:]]*-[[:space:]]*[^[:space:]]+\.md[[:space:]]*$/ {
      sub(/^[[:space:]]*-[[:space:]]*/, "")
      sub(/[[:space:]]*$/, "")
      print
    }
  ' _quarto.yml
}

# Emit "level<TAB>text" for the title and each heading in a file. The title is
# level 1 (front matter `title:` or the first H1); code fences and References
# sections are skipped.
headings() {
  awk -v depth="$DEPTH" '
    function clean(s) {
      gsub(/\[([^]]*)\]\([^)]*\)/, "\\1", s)               # links -> link text
      gsub(/\[?-?@[A-Za-z0-9_:.#$%&+?<>~\/-]+\]?/, "", s)  # pandoc citations
      gsub(/[*_`]/, "", s)                                 # emphasis / code marks
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
      gsub(/[[:space:]][[:space:]]+/, " ", s)
      return s
    }
    # Front matter: Quarto takes the chapter title from `title:` when present.
    NR == 1 && /^---[[:space:]]*$/ { front = 1; next }
    front && /^---[[:space:]]*$/   { front = 0; next }
    front {
      if (!seen_title && $0 ~ /^title:[[:space:]]*/) {
        raw = $0
        sub(/^title:[[:space:]]*/, "", raw)
        gsub(/^"|"$|^'"'"'|'"'"'$/, "", raw)
        seen_title = 1
        printf "1\t%s\n", clean(raw)
      }
      next
    }
    /^[[:space:]]*(```|~~~)/ {
      marker = substr($0, index($0, $1), 1)
      if (!fence) { fence = marker } else if (marker == fence) { fence = "" }
      next
    }
    fence { next }
    /^#{1,6}[[:space:]]/ {
      match($0, /^#+/)
      level = RLENGTH
      raw = substr($0, RLENGTH + 1)
      sub(/\{[^}]*\}[[:space:]]*$/, "", raw)   # drop pandoc attributes
      text = clean(raw)
      if (text == "" || tolower(text) == "references") next
      if (level == 1) {
        if (seen_title) next
        seen_title = 1
      } else if (level > depth) next
      printf "%d\t%s\n", level, text
    }
  ' "$1"
}

# Render one list of files read from stdin. $1 = "chapters" or "appendices".
render_section() {
  local kind="$1" file title n=0 label
  while IFS= read -r file; do
    [ -n "$file" ] || continue
    if [ ! -f "$file" ]; then
      echo "listed in _quarto.yml but missing: $file" >&2
      exit 1
    fi

    title="$(headings "$file" | awk -F'\t' '$1 == 1 { print $2; exit }')"
    [ -n "$title" ] || title="${file%.md}"

    if [ "$kind" = "appendices" ]; then
      label="$(printf "\\$(printf '%03o' $((65 + n)))"). "
    elif [ "$file" = "index.md" ]; then
      label=""
    else
      label="$n. "
    fi
    n=$((n + 1))

    printf -- '- **%s%s**\n' "$label" "$title"

    headings "$file" | awk -F'\t' '
      $1 > 1 {
        indent = ""
        for (i = 1; i < $1; i++) indent = indent "  "
        printf "%s- %s\n", indent, $2
      }'
  done
}

{
  printf '# %s\n' "$(book_field title)"
  subtitle="$(book_field subtitle)"
  [ -n "$subtitle" ] && printf '\n*%s*\n' "$subtitle"
  printf '\n<!-- Generated by generate_toc.sh. Do not edit by hand. -->\n'

  chapters="$(book_files chapters)"
  if [ -n "$chapters" ]; then
    printf '\n## Chapters\n\n'
    printf '%s\n' "$chapters" | render_section chapters
  fi

  appendices="$(book_files appendices)"
  if [ -n "$appendices" ]; then
    printf '\n## Appendices\n\n'
    printf '%s\n' "$appendices" | render_section appendices
  fi
} > "$OUTPUT"

echo "wrote $BOOK_DIR/$OUTPUT"
