#!/usr/bin/env python3
"""NOTICE: This file was substantially generated by an LLM coding agent.

Generates 0-shapes.svg: a golden-ratio rectangle holding five flat shapes
standing on a shared ground line, echoing the "abstract thought" imagery in
1-abstract-thought-inside-out_monster-verse.jpg and 2-wiki-fandom-abstract.jpeg.

Shapes, left to right (each one flat color, no outline):
    star       yellow
    square     red
    teardrop   blue   (point down / "upside down")
    broccoli   green
    lightning  purple

Every builder takes (cx, base) and draws upward from `base`, so the shapes all
stand on the same line and their differing heights stay visible.
"""

import math

# --- canvas -----------------------------------------------------------------
PHI = (1 + 5 ** 0.5) / 2
HEIGHT = 1000
WIDTH = round(HEIGHT * PHI)          # 1618
BACKGROUND = "#faf8f3"               # warm paper, like the scanned reference
BASELINE = HEIGHT * 0.66             # the ground the shapes stand on
                                     # (set so the tallest shape sits centered)

# --- palette ----------------------------------------------------------------
# each shape is one flat color, no outline
COLORS = {
    "star":      "#f2d33c",
    "square":    "#e0492c",
    "teardrop":  "#1f7fc4",
    "broccoli":  "#3faa32",
    "lightning": "#8d3fa8",
}

R = 130                              # nominal shape radius


def fmt(pts):
    return " ".join(f"{x:.2f},{y:.2f}" for x, y in pts)


# --- shape builders ---------------------------------------------------------
# each draws upward from `base`; heights differ on purpose
def star(cx, base, outer=R * 1.05, points=8):
    """Eight-spike starburst. Height 2 * outer."""
    inner = outer * 0.29
    cy = base - outer
    verts = []
    step = math.pi / points
    for i in range(points * 2):
        r = outer if i % 2 == 0 else inner
        t = -math.pi / 2 + i * step
        verts.append((cx + r * math.cos(t), cy + r * math.sin(t)))
    return f'<polygon points="{fmt(verts)}" />'


def square(cx, base, side=R * 1.45):
    """Height = side."""
    return (f'<rect x="{cx - side / 2:.2f}" y="{base - side:.2f}" '
            f'width="{side:.2f}" height="{side:.2f}" rx="10" />')


def teardrop(cx, base, r=R * 0.80):
    """Round on top, drawn to a point at the bottom. Height 2.65 * r."""
    cy = base - r * 1.65             # center of the round top
    return (
        f'<path d="M {cx:.2f},{base:.2f} '
        f'C {cx - r * 0.72:.2f},{cy + r * 0.85:.2f} '
        f'{cx - r:.2f},{cy + r * 0.45:.2f} {cx - r:.2f},{cy:.2f} '
        f'A {r:.2f},{r:.2f} 0 1 1 {cx + r:.2f},{cy:.2f} '
        f'C {cx + r:.2f},{cy + r * 0.45:.2f} '
        f'{cx + r * 0.72:.2f},{cy + r * 0.85:.2f} {cx:.2f},{base:.2f} Z" />'
    )


def broccoli(cx, base, r=R * 0.62):
    """Three circular bulges over a short stem. Height 3.77 * r."""
    stem_w, stem_len = r * 1.0, r * 1.15
    head_cy = base - stem_len - r    # center of the two outer bulges
    bulges = [(-r * 0.95, 0.0), (0.0, -r * 0.62), (r * 0.95, 0.0)]
    parts = [
        f'<circle cx="{cx + dx:.2f}" cy="{head_cy + dy:.2f}" r="{r:.2f}" />'
        for dx, dy in bulges
    ]
    parts.append(
        f'<rect x="{cx - stem_w / 2:.2f}" y="{head_cy:.2f}" '
        f'width="{stem_w:.2f}" height="{stem_len + r:.2f}" rx="6" />'
    )
    return "".join(parts)


def lightning(cx, base, h=R * 2.45, w=R * 1.6):
    """Zigzag bolt with a wide shoulder and a tapered tail. Height h."""
    cy = base - h / 2
    verts = [
        (0.10, -0.50), (-0.45, 0.02), (-0.05, 0.02),
        (-0.30, 0.50), (0.45, -0.10), (0.02, -0.10), (0.42, -0.50),
    ]
    return f'<polygon points="{fmt([(cx + x * w, cy + y * h) for x, y in verts])}" />'


# --- assemble ---------------------------------------------------------------
def build():
    order = ["star", "square", "teardrop", "broccoli", "lightning"]
    builders = {
        "star": star, "square": square, "teardrop": teardrop,
        "broccoli": broccoli, "lightning": lightning,
    }

    margin = R * 0.55
    span = WIDTH - 2 * margin

    body = []
    for i, name in enumerate(order):
        cx = margin + span * (i + 0.5) / len(order)
        shape = builders[name](cx, BASELINE)
        body.append(f'  <g fill="{COLORS[name]}">\n    {shape}\n  </g>')

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}">\n'
        f'  <rect width="{WIDTH}" height="{HEIGHT}" fill="{BACKGROUND}" />\n'
        + "\n".join(body) + "\n</svg>\n"
    )


if __name__ == "__main__":
    import pathlib
    out = pathlib.Path(__file__).with_name("0-shapes.svg")
    out.write_text(build())
    print(f"wrote {out} ({WIDTH}x{HEIGHT})")
